GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/B2b_NrDetails__c.object-meta.xml
<CustomObject>
    <description>Custom object migrated from Thango as part of Eurostar Delta migration project. Eurostar Jira ref DEIS-320</description>
    <label>Negotiated Rate</label>
    <nameField>
        <displayFormat>NR-{0000}</displayFormat>
        <label>Negotiated Rates SF Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Negotiated Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/fields/B2b_Status__c.field-meta.xml
<CustomField>
    <fullName>B2b_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>To be Extracted</fullName>
            </value>
            <value>
                <fullName>Extracted</fullName>
            </value>
            <value>
                <fullName>Integrated</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>To be Approved</fullName>
            </value>
            <value>
                <fullName>New - Default</fullName>
                <isActive>false</isActive>
                <label>New - Default</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/recordTypes/Negotiated_Rate_Continent.recordType-meta.xml
<RecordType>
    <fullName>Negotiated_Rate_Continent</fullName>
    <active>true</active>
    <label>Negotiated Rate Continent</label>
</RecordType>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/recordTypes/Negotiated_Rate_London.recordType-meta.xml
<RecordType>
    <fullName>Negotiated_Rate_London</fullName>
    <active>true</active>
    <label>Negotiated Rate London</label>
</RecordType>

GearsetPOC/force-app/main/default/classes/DLT_NegotiatedRateConstants.cls
public inherited sharing class DLT_NegotiatedRateConstants {
    
    public static final String STATUS_NEW = 'New';
    public static final String STATUS_EXTRACTED = 'Extracted';
    public static final String STATUS_INTEGRATED = 'Integrated';
    public static final String STATUS_TO_BE_EXTRACTED = 'To be Extracted';
    public static final String STATUS_TO_BE_APPROVED = 'To be Approved';

    public static final String ROUTE_PARIS_BELGIUM = 'Paris - Belgium';
    public static final String ROUTE_LONDON_PARIS= 'London - Paris';

    public static final Id CORPORATE_CONTINENT = Schema.SObjectType.B2b_NrDetails__c.getRecordTypeInfosByDeveloperName().get('Negotiated_Rate_Continent').getRecordTypeId();
    public static final Id CORPORATE_LONDON = Schema.SObjectType.B2b_NrDetails__c.getRecordTypeInfosByDeveloperName().get('Negotiated_Rate_London').getRecordTypeId();
    public static final Map<String, String> rateContractRecordTypeMap = new Map<String, String>{
            DLT_BusinessContractConstants.CORPORATE_CONTINENT => CORPORATE_CONTINENT,
            DLT_BusinessContractConstants.CORPORATE_LONDON => CORPORATE_LONDON
    };

    public static final String DISCOUNT_NEW = 'New';
    public static final String DISCOUNT_HIGHER = 'Higher';
    public static final String DISCOUNT_LOWER = 'Lower';
    public static final String DISCOUNT_SAME = 'Same';

    public static final String DEUTSCHER_BUND = 'Deutscher Bund';

    public static final Set<String> RED_ACCOUNT_TYPE_VALUES = new Set<String>{'TCF1','TCF2','COVID'};

    public static Boolean isToBeExtracted(B2b_NrDetails__c rate) {
        return rate == null ? false : rate.B2b_Status__c == STATUS_TO_BE_EXTRACTED;
    }

    public static final String APPROVAL_API_RED_NEGOTIATED_RATE = 'RED_Negotiated_Rate_AP';
    public static final String APPROVAL_COMMENT_SUBMIT = 'Submit rates with To Be Approved status';

}