GearsetPOC/force-app/main/default/objects/Special_Character_Mapping__c/Special_Character_Mapping__c.object-meta.xml
<CustomObject>
    <label>Special Character Mapping</label>
    <nameField>
        <displayFormat>SCMN-{0000000000}</displayFormat>
        <label>Special Character Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Character Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Special_Character_Mapping__c/fields/Special_Character__c.field-meta.xml
<CustomField>
    <fullName>Special_Character__c</fullName>
    <label>Special Character</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Special_Character_Mapping__c/fields/Standard_Character__c.field-meta.xml
<CustomField>
    <fullName>Standard_Character__c</fullName>
    <label>Standard Character</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/OSF_RetroTicketLining.cls
public with sharing class OSF_RetroTicketLining {
    public class FlowInput {
        @InvocableVariable(required=true) 
        public String membershipNumber;
        @InvocableVariable(required=true) 
        public String pnr;
        @InvocableVariable(required=true)
        public String tcn;
        @InvocableVariable(required=true)
        public String recordId;
        @InvocableVariable 
        public Boolean validateName;
    }

    public class FlowOutput {
        @InvocableVariable 
        public String resultMessage;
    }

    @InvocableMethod 
    public static List<FlowOutput> retroTicketLinking(List<FlowInput> params) { 
        List<FlowOutput> results = new List<FlowOutput>{new FlowOutput()};
        System.debug('### params: ' + params);
        Boolean validateName = params[0].validateName != null ? params[0].validateName : true;
        try {
            Map<String, String> mapSpecialCharToStdChar = new map<String, String>();
            for(Special_Character_Mapping__c scm : [SELECT Id, Special_Character__c, Standard_Character__c FROM Special_Character_Mapping__c]) {
                mapSpecialCharToStdChar.put(scm.Special_Character__c, scm.Standard_Character__c);
            }
            results[0].resultMessage = OSF_TicketHandler.retroClaimPoints(params[0].membershipNumber, params[0].pnr, params[0].tcn, validateName, params[0].recordId, mapSpecialCharToStdChar);
        } catch(Exception e) { results[0].resultMessage = e.getMessage(); OSF_ErrorLogHandler.logError(e, 'OSF_RetroTicketLining');
        } finally {
            OSF_ErrorLogHandler.saveErrors();
        }
        return results;
    }
   
}