GearsetPOC/force-app/main/default/objects/Passing_Point__c/Passing_Point__c.object-meta.xml
<CustomObject>
    <description>Passing Points for Train Services</description>
    <label>Passing Point</label>
    <nameField>
        <displayFormat>PP-{00000000}</displayFormat>
        <label>Passing Point Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passing Points</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Passing_Point__c/fields/Arrival_Commercial_Reason__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Commercial_Reason__c</fullName>
    <label>Arrival Commercial Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Passing_Point__c/fields/Delay_Mins_Train_Expert__c.field-meta.xml
<CustomField>
    <fullName>Delay_Mins_Train_Expert__c</fullName>
    <label>Delay Mins (Train Expert)</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Passing_Point__c/fields/PassingPoint_Arrival_Delay__c.field-meta.xml
<CustomField>
    <fullName>PassingPoint_Arrival_Delay__c</fullName>
    <label>Arrival Delay</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Passing_Point__c/fields/PassingPoint_Delay_Reason__c.field-meta.xml
<CustomField>
    <fullName>PassingPoint_Delay_Reason__c</fullName>
    <label>Delay Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>due to a cable theft</fullName>
            </value>
            <value>
                <fullName>due to a case of force majeure</fullName>
            </value>
            <value>
                <fullName>due to a delay in the food and beverage supply</fullName>
            </value>
            <value>
                <fullName>due to a failure of the rolling materiel</fullName>
            </value>
            <value>
                <fullName>due to a strike</fullName>
            </value>
            <value>
                <fullName>due to a technical incident</fullName>
            </value>
            <value>
                <fullName>due to an accident involving people</fullName>
            </value>
            <value>
                <fullName>due to an alarm signal</fullName>
            </value>
            <value>
                <fullName>due to an incident on the infrastructure</fullName>
            </value>
            <value>
                <fullName>due to an unplanned strike</fullName>
            </value>
            <value>
                <fullName>due to bad weather conditions</fullName>
            </value>
            <value>
                <fullName>due to difficulties in coordination</fullName>
            </value>
            <value>
                <fullName>due to the intervention of the authorities</fullName>
            </value>
            <value>
                <fullName>due to the presence of a suspicious object</fullName>
            </value>
            <value>
                <fullName>due to the presence of an obstacle on the tracks</fullName>
            </value>
            <value>
                <fullName>due to the presence of animals on the tracks</fullName>
            </value>
            <value>
                <fullName>due to the presence of people on the tracks</fullName>
            </value>
            <value>
                <fullName>due to track works</fullName>
            </value>
            <value>
                <fullName>due to traffic problems</fullName>
            </value>
            <value>
                <fullName>due to vandalism</fullName>
            </value>
            <value>
                <fullName>Magical incident type</fullName>
            </value>
            <value>
                <fullName>DB</fullName>
            </value>
            <value>
                <fullName>NS</fullName>
            </value>
            <value>
                <fullName>SNCB</fullName>
            </value>
            <value>
                <fullName>SNCF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Passing_Point__c/fields/Train__c.field-meta.xml
<CustomField>
    <fullName>Train__c</fullName>
    <label>Train</label>
    <referenceTo>Train__c</referenceTo>
    <relationshipLabel>Passing Points</relationshipLabel>
    <relationshipName>Passing_Points</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

GearsetPOC/force-app/main/default/objects/Passing_Point__c/fields/Train_Expert__c.field-meta.xml
<CustomField>
    <fullName>Train_Expert__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Train Expert</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Passing_Points</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Passing_Point__c/fields/UIC_Code__c.field-meta.xml
<CustomField>
    <fullName>UIC_Code__c</fullName>
    <label>UIC Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>TCN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <label>Carrier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Checked_In__c.field-meta.xml
<CustomField>
    <fullName>Checked_In__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has passenger checked in?</description>
    <label>Checked In</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Delay_mins__c.field-meta.xml
<CustomField>
    <fullName>Delay_mins__c</fullName>
    <label>Delay (mins)</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Ticket_Status__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Status__c</fullName>
    <label>Ticket Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Exchanged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Train__c.field-meta.xml
<CustomField>
    <fullName>Train__c</fullName>
    <label>Train</label>
    <referenceTo>Train__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Train_Expert__c.field-meta.xml
<CustomField>
    <fullName>Train_Expert__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Train Expert</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/UIC_Code__c.field-meta.xml
<CustomField>
    <fullName>UIC_Code__c</fullName>
    <label>UIC Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/Train__c.object-meta.xml
<CustomObject>
    <label>Train</label>
    <nameField>
        <label>Train ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <label>Carrier</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Delay_Mins_Train_Expert__c.field-meta.xml
<CustomField>
    <fullName>Delay_Mins_Train_Expert__c</fullName>
    <label>Delay Mins (Train Expert)</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Train_Expert__c.field-meta.xml
<CustomField>
    <fullName>Train_Expert__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User that filled Delay Mins (Train Expert) field.</description>
    <inlineHelpText>User that filled Delay Mins (Train Expert) field.</inlineHelpText>
    <label>Train Expert</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Trains</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/DLT_PassingPointTriggerHandler.cls
public without sharing class DLT_PassingPointTriggerHandler {
    public static Boolean isDisabled = false;

    public static void run() {
        if (!System.Trigger.isExecuting || isDisabled) { return; }

        if (System.Trigger.isBefore) {
            if (System.Trigger.isInsert) {
                fillDelayReasonFields((List<Passing_Point__c>) System.Trigger.new);
            }

            if (System.Trigger.isUpdate) {
                fillDelayReasonFields((List<Passing_Point__c>) System.Trigger.new);
                syncTrainExpertFields((Map<Id, Passing_Point__c>) System.Trigger.newMap, (Map<Id, Passing_Point__c>) System.Trigger.oldMap);
                preventDelayOverride((List<Passing_Point__c>) System.Trigger.new, (Map<Id, Passing_Point__c>) System.Trigger.oldMap);
            }
        }
        if (System.Trigger.isAfter) {
            if (System.Trigger.isInsert) {
                calculateTrainGlobalDelayReason((List<Passing_Point__c>) System.Trigger.new);
            }
            if (System.Trigger.isUpdate) {
                updateDelayOnTickets((Map<Id, Passing_Point__c>) System.Trigger.newMap, (Map<Id, Passing_Point__c>) System.Trigger.oldMap);
                calculateTrainGlobalDelayReason((List<Passing_Point__c>) System.Trigger.new, (Map<Id, Passing_Point__c>) System.Trigger.oldMap);
            }
        }
    }

    private static void syncTrainExpertFields(Map<Id, Passing_Point__c> newMap, Map<Id, Passing_Point__c> oldMap){

        if(!DLT_Constants.IS_TRAIN_EXPERT) return;

        for(Passing_Point__c pp : newMap.values()){
            if(pp.PassingPoint_Arrival_Delay__c != oldMap.get(pp.Id).PassingPoint_Arrival_Delay__c){

                pp.Delay_Mins_Train_Expert__c = Integer.valueOf(pp.PassingPoint_Arrival_Delay__c);
                pp.Train_Expert__c = UserInfo.getUserId();
            }
        }
    }

    private static void updateDelayOnTickets(Map<Id, Passing_Point__c> newMap, Map<Id, Passing_Point__c> oldMap){


        if(!DLT_Constants.IS_TRAIN_EXPERT) return;

        Set<Id> trainIds = new Set<Id>();
        Set<String> uicCodes = new Set<String>();

        Map<Id,Map<String,Passing_Point__c>> trainWithPassingPoints = new Map<Id,Map<String,Passing_Point__c>>();

        for(Passing_Point__c pp : newMap.values()){
            if(pp.PassingPoint_Arrival_Delay__c != oldMap.get(pp.Id).PassingPoint_Arrival_Delay__c){

                trainIds.add(pp.Train__c);
                uicCodes.add(pp.UIC_Code__c);

                if(!trainWithPassingPoints.containsKey(pp.Train__c)){
                    Map<String,Passing_Point__c> tempMap = new Map<String, Passing_Point__c>();
                    tempMap.put(pp.UIC_Code__c, pp);
                    trainWithPassingPoints.put(pp.Train__c, tempMap);
                }
                trainWithPassingPoints.get(pp.Train__c).put(pp.UIC_Code__c, pp);

            }
        }

        trainIds.remove(null);
        uicCodes.remove(null);
        uicCodes.remove('');

        if (trainIds.isEmpty() && uicCodes.isEmpty()) { return; }

        List<Ticket__c> ticketsToUpdate = new List<Ticket__c>();

        for(Ticket__c t : [
            SELECT Id, UIC_Code__c, Train__c
            FROM Ticket__c
            WHERE Train__c IN :trainIds
                AND UIC_Code__c IN :uicCodes
                AND Ticket_Status__c = :DLT_TicketConstants.TICKET_STATUS_ACTIVE
                AND (
                        (Train__r.Carrier__c = :DLT_TrainConstants.CARRIER_BLUE AND Checked_in__c = true)
                        OR Train__r.Carrier__c = :DLT_TrainConstants.CARRIER_RED
                    )
        ]){
            if(trainWithPassingPoints.containsKey(t.Train__c) && trainWithPassingPoints.get(t.Train__c).containsKey(t.UIC_Code__c)){
                ticketsToUpdate.add(
                    new Ticket__c (
                        Id = t.Id, 
                        Delay_mins__c = Integer.valueOf(trainWithPassingPoints.get(t.Train__c).get(t.UIC_Code__c).PassingPoint_Arrival_Delay__c),
                        Delay_Mins_Train_Expert__c = Integer.valueOf(trainWithPassingPoints.get(t.Train__c).get(t.UIC_Code__c).PassingPoint_Arrival_Delay__c),
                        Train_Expert__c = UserInfo.getUserId()
                    )
                );
            }
        }

        update ticketsToUpdate;

    }

    private static void preventDelayOverride(List<Passing_Point__c> newList, Map<Id, Passing_Point__c> oldMap){

        if(DLT_Constants.IS_TRAIN_EXPERT) return;

        for(Passing_Point__c pp : newList){

            if(pp.PassingPoint_Arrival_Delay__c != oldMap.get(pp.Id).PassingPoint_Arrival_Delay__c 
                && pp.Delay_Mins_Train_Expert__c != null){

                pp.PassingPoint_Arrival_Delay__c = String.valueOf(pp.Delay_Mins_Train_Expert__c);
            }
        }
    }

    private static void calculateTrainGlobalDelayReason(List<Passing_Point__c> newList, Map<Id, Passing_Point__c> oldMap){

        List<Id> trainIdsToCalculate = new List<Id>();

        for(Passing_Point__c pp : newList){

            if(pp.PassingPoint_Arrival_Delay__c != oldMap.get(pp.Id).PassingPoint_Arrival_Delay__c){

                trainIdsToCalculate.add(pp.Train__c);

            }
        }

        DLT_Train_Service.calculateGlobalDelayReason(trainIdsToCalculate);
    }

    private static void calculateTrainGlobalDelayReason(List<Passing_Point__c> newList){

        List<Id> trainIdsToCalculate = new List<Id>();

        for(Passing_Point__c pp : newList){

            trainIdsToCalculate.add(pp.Train__c);

        }

        DLT_Train_Service.calculateGlobalDelayReason(trainIdsToCalculate);
    }

    private static void fillDelayReasonFields(List<Passing_Point__c> newList){

        for(Passing_Point__c pp : newList){

            if(!String.isBlank(pp.Arrival_Commercial_Reason__c) && pp.PassingPoint_Delay_Reason__c != pp.Arrival_Commercial_Reason__c){

                pp.PassingPoint_Delay_Reason__c = pp.Arrival_Commercial_Reason__c;

            }
        }
    }
}