GearsetPOC/force-app/main/default/objects/Passing_Point__c/Passing_Point__c.object-meta.xml
<CustomObject>
    <description>Passing Points for Train Services</description>
    <label>Passing Point</label>
    <nameField>
        <displayFormat>PP-{00000000}</displayFormat>
        <label>Passing Point Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passing Points</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Passing_Point__c/fields/Arrival_Commercial_Reason__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Commercial_Reason__c</fullName>
    <label>Arrival Commercial Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Passing_Point__c/fields/Departure_Commercial_Reason__c.field-meta.xml
<CustomField>
    <fullName>Departure_Commercial_Reason__c</fullName>
    <label>Departure Commercial Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Passing_Point__c/fields/Departure_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date_Time__c</fullName>
    <label>Departure Date Time</label>
    <type>DateTime</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Passing_Point__c/fields/PassingPoint_Arrival_Delay__c.field-meta.xml
<CustomField>
    <fullName>PassingPoint_Arrival_Delay__c</fullName>
    <label>Arrival Delay</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Passing_Point__c/fields/PassingPoint_Delay_Reason__c.field-meta.xml
<CustomField>
    <fullName>PassingPoint_Delay_Reason__c</fullName>
    <label>Delay Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>due to a cable theft</fullName>
            </value>
            <value>
                <fullName>due to a case of force majeure</fullName>
            </value>
            <value>
                <fullName>due to a delay in the food and beverage supply</fullName>
            </value>
            <value>
                <fullName>due to a failure of the rolling materiel</fullName>
            </value>
            <value>
                <fullName>due to a strike</fullName>
            </value>
            <value>
                <fullName>due to a technical incident</fullName>
            </value>
            <value>
                <fullName>due to an accident involving people</fullName>
            </value>
            <value>
                <fullName>due to an alarm signal</fullName>
            </value>
            <value>
                <fullName>due to an incident on the infrastructure</fullName>
            </value>
            <value>
                <fullName>due to an unplanned strike</fullName>
            </value>
            <value>
                <fullName>due to bad weather conditions</fullName>
            </value>
            <value>
                <fullName>due to difficulties in coordination</fullName>
            </value>
            <value>
                <fullName>due to the intervention of the authorities</fullName>
            </value>
            <value>
                <fullName>due to the presence of a suspicious object</fullName>
            </value>
            <value>
                <fullName>due to the presence of an obstacle on the tracks</fullName>
            </value>
            <value>
                <fullName>due to the presence of animals on the tracks</fullName>
            </value>
            <value>
                <fullName>due to the presence of people on the tracks</fullName>
            </value>
            <value>
                <fullName>due to track works</fullName>
            </value>
            <value>
                <fullName>due to traffic problems</fullName>
            </value>
            <value>
                <fullName>due to vandalism</fullName>
            </value>
            <value>
                <fullName>Magical incident type</fullName>
            </value>
            <value>
                <fullName>DB</fullName>
            </value>
            <value>
                <fullName>NS</fullName>
            </value>
            <value>
                <fullName>SNCB</fullName>
            </value>
            <value>
                <fullName>SNCF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Passing_Point__c/fields/PassingPoint_Departure_Delay__c.field-meta.xml
<CustomField>
    <fullName>PassingPoint_Departure_Delay__c</fullName>
    <label>Departure Delay</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Passing_Point__c/fields/Train__c.field-meta.xml
<CustomField>
    <fullName>Train__c</fullName>
    <label>Train</label>
    <referenceTo>Train__c</referenceTo>
    <relationshipLabel>Passing Points</relationshipLabel>
    <relationshipName>Passing_Points</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/Train__c.object-meta.xml
<CustomObject>
    <label>Train</label>
    <nameField>
        <label>Train ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Delay_in_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Delay_in_Minutes__c</fullName>
    <description>The train delay in minutes</description>
    <label>Delay (mins)</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Departure_Commercial_Reason__c.field-meta.xml
<CustomField>
    <fullName>Departure_Commercial_Reason__c</fullName>
    <label>Departure Commercial Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Departure_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date_Time__c</fullName>
    <description>Train&#39;s Scheduled departure date and time</description>
    <inlineHelpText>Train&#39;s Scheduled departure date and time</inlineHelpText>
    <label>Departure DateTime</label>
    <length>28</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Destination_Commercial_Reason__c.field-meta.xml
<CustomField>
    <fullName>Destination_Commercial_Reason__c</fullName>
    <label>Destination Commercial Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Global_Delay_Reason__c.field-meta.xml
<CustomField>
    <fullName>Global_Delay_Reason__c</fullName>
    <label>Global Delay Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>due to a cable theft</fullName>
            </value>
            <value>
                <fullName>due to a case of force majeure</fullName>
            </value>
            <value>
                <fullName>due to a delay in the food and beverage supply</fullName>
            </value>
            <value>
                <fullName>due to a failure of the rolling materiel</fullName>
            </value>
            <value>
                <fullName>due to a strike</fullName>
            </value>
            <value>
                <fullName>due to a technical incident</fullName>
            </value>
            <value>
                <fullName>due to an accident involving people</fullName>
            </value>
            <value>
                <fullName>due to an alarm signal</fullName>
            </value>
            <value>
                <fullName>due to an incident on the infrastructure</fullName>
            </value>
            <value>
                <fullName>due to an unplanned strike</fullName>
            </value>
            <value>
                <fullName>due to bad weather conditions</fullName>
            </value>
            <value>
                <fullName>due to difficulties in coordination</fullName>
            </value>
            <value>
                <fullName>due to the intervention of the authorities</fullName>
            </value>
            <value>
                <fullName>due to the presence of a suspicious object</fullName>
            </value>
            <value>
                <fullName>due to the presence of an obstacle on the tracks</fullName>
            </value>
            <value>
                <fullName>due to the presence of animals on the tracks</fullName>
            </value>
            <value>
                <fullName>due to the presence of people on the tracks</fullName>
            </value>
            <value>
                <fullName>due to track works</fullName>
            </value>
            <value>
                <fullName>due to traffic problems</fullName>
            </value>
            <value>
                <fullName>due to vandalism</fullName>
            </value>
            <value>
                <fullName>Magical incident type</fullName>
            </value>
            <value>
                <fullName>DB</fullName>
            </value>
            <value>
                <fullName>NS</fullName>
            </value>
            <value>
                <fullName>SNCB</fullName>
            </value>
            <value>
                <fullName>SNCF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Global_Delay_Reason_Train_Expert__c.field-meta.xml
<CustomField>
    <fullName>Global_Delay_Reason_Train_Expert__c</fullName>
    <label>Global Delay Reason Train Expert</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/DLT_Train_Service.cls
public without sharing class DLT_Train_Service {
    
    public static void calculateGlobalDelayReason(List<Id> trainIds){

        if(DLT_Utils.isAsyncCtx()){
            calculateAndAssignGlobalDelayReason(trainIds);
        } else{
            calculateAndAssignGlobalDelayReasonInFuture(trainIds);
        }
    }

    @future
    public static void calculateAndAssignGlobalDelayReasonInFuture(List<Id> trainIds){
        calculateAndAssignGlobalDelayReason(trainIds);
    }

    public static void calculateAndAssignGlobalDelayReason(List<Id> trainIds){
        
        // create required maps

        Map<Id, List<Passing_Point__c>> trainWithPassingPoint = new Map<Id, List<Passing_Point__c>>();
        Map<Id, Train__c> trainById = new Map<Id, Train__c>();

        for (Train__c t : [
            SELECT Id, Delay_in_Minutes__c, Destination_Commercial_Reason__c
            FROM Train__c
            WHERE Id IN :trainIds
                AND Global_Delay_Reason_Train_Expert__c = null
        ]){
            trainWithPassingPoint.put(t.Id, new List<Passing_Point__c>());
            trainById.put(t.Id, t);
        }

        for (Passing_Point__c pp: [
            SELECT Id, PassingPoint_Arrival_Delay__c, PassingPoint_Departure_Delay__c, Arrival_Commercial_Reason__c, 
                Departure_Commercial_Reason__c, Train__c, PassingPoint_Delay_Reason__c
            FROM Passing_Point__c
            WHERE Train__c IN :trainById.keySet()
            ORDER BY Departure_Date_Time__c 
        ]){
            trainWithPassingPoint.get(pp.Train__c).add(pp);
        }

        // calculate Global Delay Reason

        List<Train__c> trainsToUpdate = new List<Train__c>();

        for(Id trainId : trainWithPassingPoint.keySet()){

            Map<String, Integer> delayReasonToTime = new Map<String, Integer>();
            Integer currentDelay = 0;

            // going from first to last passing point 
            for(Passing_Point__c p : trainWithPassingPoint.get(trainId)){

                if(String.isBlank(p.PassingPoint_Arrival_Delay__c)) continue; 

                // calculate delay difference 
                Integer arrivalDelayDifference = Integer.valueOf(p.PassingPoint_Arrival_Delay__c) - currentDelay;
                // update current delay
                currentDelay = Integer.valueOf(p.PassingPoint_Arrival_Delay__c);

                if(arrivalDelayDifference <= 0) continue;

                // add delay difference to correct delay reason
                if(!delayReasonToTime.containsKey(p.PassingPoint_Delay_Reason__c)){
                    delayReasonToTime.put(p.PassingPoint_Delay_Reason__c, 0);
                }
                delayReasonToTime.put(p.PassingPoint_Delay_Reason__c, delayReasonToTime.get(p.PassingPoint_Delay_Reason__c) + arrivalDelayDifference);
         
            }

            Train__c currentTrain = trainById.get(trainId);

            // final destination 
            if(currentTrain.Delay_in_Minutes__c != null){
                // difference between last passing point and destination
                Integer trainDelay = Integer.valueOf(currentTrain.Delay_in_Minutes__c) - currentDelay;

                // add delay difference to correct delay reason
                if(!delayReasonToTime.containsKey(currentTrain.Destination_Commercial_Reason__c)){
                    delayReasonToTime.put(currentTrain.Destination_Commercial_Reason__c, trainDelay);
                } else {
                    delayReasonToTime.put(currentTrain.Destination_Commercial_Reason__c, delayReasonToTime.get(currentTrain.Destination_Commercial_Reason__c) + trainDelay);
                }
            }
            
            // find biggest delay and corresponding reason
            String globalDelayReason = '';
            Integer maxDelay = 0;

            for(String reason : delayReasonToTime.keySet()){
                if(delayReasonToTime.get(reason) > maxDelay){
                    maxDelay = delayReasonToTime.get(reason);
                    globalDelayReason = reason;
                }
            }

            trainsToUpdate.add(new Train__c(Id = trainId, Global_Delay_Reason__c = globalDelayReason));

        }
        DLT_TrainTriggerHandler.isDisabled = true;
        update trainsToUpdate;
        DLT_TrainTriggerHandler.isDisabled = false;
    }

}