GearsetPOC/force-app/main/default/objects/Annual_Review__c/Annual_Review__c.object-meta.xml
<CustomObject>
    <label>Annual Review</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Review</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Annual_Review__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <label>Completed</label>
    <type>Date</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Annual_Review__c/fields/Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Review_Status__c</fullName>
    <label>Review Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Passed - Contract Extended</fullName>
            </value>
            <value>
                <fullName>Failed - Threshold Not Reached</fullName>
            </value>
            <value>
                <fullName>Failed - Credit Check Not Approved</fullName>
            </value>
            <value>
                <fullName>Failed - Digital &amp; Brand Not Compliant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Annual_Review__c/fields/Trading_Account__c.field-meta.xml
<CustomField>
    <fullName>Trading_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to B2B Account</description>
    <label>Trading Name</label>
    <referenceTo>Business_Account__c</referenceTo>
    <relationshipLabel>Annual Reviews</relationshipLabel>
    <relationshipName>Annual_Reviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/Business_Account__c.object-meta.xml
<CustomObject>
    <description>Custom Business Account object created as part of Eurostar Delta migration project. Eurostar Jira ref DEIS-281</description>
    <label>Business Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/Annual_Review_Reneg__c.field-meta.xml
<CustomField>
    <fullName>Annual_Review_Reneg__c</fullName>
    <description>date of annual review before contract expires</description>
    <label>Annual Review / Renegotiation</label>
    <type>Date</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/DLT_AnnualReviewTriggerHandler.cls
public with sharing class DLT_AnnualReviewTriggerHandler {

    public static Boolean isDisabled = false;
    
    public static void run() {
        if (!System.Trigger.isExecuting || isDisabled) { return; }

        if (System.Trigger.isBefore) {
            if (System.Trigger.isInsert) {
            }

            if (System.Trigger.isUpdate) {
            }
        }

        if (System.Trigger.isAfter) {
            if (System.Trigger.isInsert) {

            }

            if (System.Trigger.isUpdate) {
                updateRelatedBusinessAccount(Trigger.new);
            }
        }
    }

    public static void updateRelatedBusinessAccount(List<Annual_Review__c> annualReviewList){

    List<Business_Account__c> businessAccountsToUpdate = new List<Business_Account__c>();
    Map<Id,Annual_Review__c> businessAccountToAnnualReviewMap = new Map<Id,Annual_Review__c>();

        for(Annual_Review__c ar : annualReviewList){
            if(ar.Review_Status__c == DLT_AnnualReviewConstants.REVIEWSTATUS_PASSED_EXTENDED && ar.Completed__c != null){
                businessAccountToAnnualReviewMap.put(ar.Trading_Account__c, ar);
            }
        }

        for(Business_Account__c ba : [
            SELECT Id
            FROM Business_Account__c 
            WHERE Id IN :businessAccountToAnnualReviewMap.keySet()
                AND RecordTypeId = :DLT_BusinessAccountConstants.RECORD_TYPE_ID_AGENCY]){

            ba.Annual_Review_Reneg__c = businessAccountToAnnualReviewMap.get(ba.Id).Completed__c.addYears(1);
            businessAccountsToUpdate.add(ba);
        }

        if(businessAccountsToUpdate.size() > 0){
            DLT_BusinessAccountTriggerHandler.isDisabled = true;
            update businessAccountsToUpdate;
            DLT_BusinessAccountTriggerHandler.isDisabled = false;
        }
    }


}