GearsetPOC/force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>TCN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Agent_Username__c.field-meta.xml
<CustomField>
    <fullName>Agent_Username__c</fullName>
    <label>Agent Username</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Booking_Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Booking_Sales_Channel__c</fullName>
    <externalId>true</externalId>
    <label>Booking Sales Channel</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/city_code__c.field-meta.xml
<CustomField>
    <fullName>city_code__c</fullName>
    <label>city_code</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Delay_mins__c.field-meta.xml
<CustomField>
    <fullName>Delay_mins__c</fullName>
    <label>Delay (mins)</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/IATA_code__c.field-meta.xml
<CustomField>
    <fullName>IATA_code__c</fullName>
    <label>IATA_code</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/office_code__c.field-meta.xml
<CustomField>
    <fullName>office_code__c</fullName>
    <label>office_code</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Point_of_Sale_original__c.field-meta.xml
<CustomField>
    <fullName>Point_of_Sale_original__c</fullName>
    <externalId>true</externalId>
    <label>Sales channel original</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/DLT_TicketTriggerHandler.cls
public without sharing class DLT_TicketTriggerHandler {
    public static Boolean isDisabled = false;

    public static void run() {
        if (!System.Trigger.isExecuting || isDisabled) { return; }

        if (System.Trigger.isBefore) {
            if (System.Trigger.isInsert) {
                setDefaultFieldValues(Trigger.new);
            }

            if (System.Trigger.isUpdate) {
                setDefaultFieldValues(Trigger.new);
                preventDelayOverride((List<Ticket__c>) System.Trigger.new, (Map<Id, Ticket__c>) System.Trigger.oldMap);
            }
        }

        if (System.Trigger.isAfter) {
            if (System.Trigger.isInsert) {

            }

            if (System.Trigger.isUpdate) {

            }
        }
    }

    private static void setDefaultFieldValues(List<Ticket__c> tickets) {
        for (Ticket__c ticket : tickets) {
            if (String.isNotBlank(ticket.Point_of_Sale_original__c)) { continue; }

            if (DLT_TicketConstants.POS_AGENT_USERNAME_BSC_VALUES.contains(ticket.Booking_Sales_Channel__c)) {
                ticket.Point_of_Sale_original__c = ticket.Agent_Username__c;

            } else if (DLT_TicketConstants.POS_CITY_CODE_BSC_VALUES.contains(ticket.Booking_Sales_Channel__c)) {
                ticket.Point_of_Sale_original__c = ticket.city_code__c;

            } else if (DLT_TicketConstants.POS_IATA_CODE_BSC_VALUES.contains(ticket.Booking_Sales_Channel__c)) {
                ticket.Point_of_Sale_original__c = ticket.IATA_code__c;

            } else if (DLT_TicketConstants.POS_OFFICE_CODE_BSC_VALUES.contains(ticket.Booking_Sales_Channel__c)) {
                ticket.Point_of_Sale_original__c = ticket.office_code__c;
            }
        }
    }

    private static void preventDelayOverride(List<Ticket__c> newList, Map<Id, Ticket__c> oldMap){
        if (DLT_Constants.IS_TRAIN_EXPERT) { return; }

        for (Ticket__c ticket : newList) {

            if(ticket.Delay_mins__c != oldMap.get(ticket.Id).Delay_mins__c 
                && ticket.Delay_Mins_Train_Expert__c != null){

                ticket.Delay_mins__c = ticket.Delay_Mins_Train_Expert__c;
            }
        }
    }
}