GearsetPOC/force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>TCN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Train Cancelled</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Cancelled_By_Customer__c.field-meta.xml
<CustomField>
    <fullName>Cancelled_By_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ticket Cancelled</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <label>Carrier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Checked_In__c.field-meta.xml
<CustomField>
    <fullName>Checked_In__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has passenger checked in?</description>
    <label>Checked In</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Delay_mins__c.field-meta.xml
<CustomField>
    <fullName>Delay_mins__c</fullName>
    <label>Delay (mins)</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Ticket_Status__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Status__c</fullName>
    <label>Ticket Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Exchanged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Train__c.field-meta.xml
<CustomField>
    <fullName>Train__c</fullName>
    <label>Train</label>
    <referenceTo>Train__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Train_Expert__c.field-meta.xml
<CustomField>
    <fullName>Train_Expert__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Train Expert</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Train_No_Catering__c.field-meta.xml
<CustomField>
    <fullName>Train_No_Catering__c</fullName>
    <formula>Train__r.No_Catering__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Train No Catering</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Train_Unacceptable_Travel_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Train_Unacceptable_Travel_Conditions__c</fullName>
    <formula>Train__r.Unacceptable_Travel_Conditions__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Train Unacceptable Travel Conditions</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Travel_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Travel_DateTime__c</fullName>
    <description>Travel DateTime</description>
    <externalId>true</externalId>
    <label>Departure DateTime</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/UIC_Code__c.field-meta.xml
<CustomField>
    <fullName>UIC_Code__c</fullName>
    <label>UIC Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/Train__c.object-meta.xml
<CustomObject>
    <label>Train</label>
    <nameField>
        <label>Train ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Train was cancelled</description>
    <label>Cancelled</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <label>Carrier</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Delay_in_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Delay_in_Minutes__c</fullName>
    <description>The train delay in minutes</description>
    <label>Delay (mins)</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Delay_Mins_Train_Expert__c.field-meta.xml
<CustomField>
    <fullName>Delay_Mins_Train_Expert__c</fullName>
    <label>Delay Mins (Train Expert)</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Departure_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date_Time__c</fullName>
    <description>Train&#39;s Scheduled departure date and time</description>
    <inlineHelpText>Train&#39;s Scheduled departure date and time</inlineHelpText>
    <label>Departure DateTime</label>
    <length>28</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Exempt_from_Auto_Compensation__c.field-meta.xml
<CustomField>
    <fullName>Exempt_from_Auto_Compensation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exempt from Auto Compensation</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Global_Delay_Reason__c.field-meta.xml
<CustomField>
    <fullName>Global_Delay_Reason__c</fullName>
    <label>Global Delay Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>due to a cable theft</fullName>
            </value>
            <value>
                <fullName>due to a case of force majeure</fullName>
            </value>
            <value>
                <fullName>due to a delay in the food and beverage supply</fullName>
            </value>
            <value>
                <fullName>due to a failure of the rolling materiel</fullName>
            </value>
            <value>
                <fullName>due to a strike</fullName>
            </value>
            <value>
                <fullName>due to a technical incident</fullName>
            </value>
            <value>
                <fullName>due to an accident involving people</fullName>
            </value>
            <value>
                <fullName>due to an alarm signal</fullName>
            </value>
            <value>
                <fullName>due to an incident on the infrastructure</fullName>
            </value>
            <value>
                <fullName>due to an unplanned strike</fullName>
            </value>
            <value>
                <fullName>due to bad weather conditions</fullName>
            </value>
            <value>
                <fullName>due to difficulties in coordination</fullName>
            </value>
            <value>
                <fullName>due to the intervention of the authorities</fullName>
            </value>
            <value>
                <fullName>due to the presence of a suspicious object</fullName>
            </value>
            <value>
                <fullName>due to the presence of an obstacle on the tracks</fullName>
            </value>
            <value>
                <fullName>due to the presence of animals on the tracks</fullName>
            </value>
            <value>
                <fullName>due to the presence of people on the tracks</fullName>
            </value>
            <value>
                <fullName>due to track works</fullName>
            </value>
            <value>
                <fullName>due to traffic problems</fullName>
            </value>
            <value>
                <fullName>due to vandalism</fullName>
            </value>
            <value>
                <fullName>Magical incident type</fullName>
            </value>
            <value>
                <fullName>DB</fullName>
            </value>
            <value>
                <fullName>NS</fullName>
            </value>
            <value>
                <fullName>SNCB</fullName>
            </value>
            <value>
                <fullName>SNCF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Global_Delay_Reason_Train_Expert__c.field-meta.xml
<CustomField>
    <fullName>Global_Delay_Reason_Train_Expert__c</fullName>
    <label>Global Delay Reason Train Expert</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Train_Expert__c.field-meta.xml
<CustomField>
    <fullName>Train_Expert__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User that filled Delay Mins (Train Expert) field.</description>
    <inlineHelpText>User that filled Delay Mins (Train Expert) field.</inlineHelpText>
    <label>Train Expert</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Trains</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Train_handled_by_Auto_Compensation__c.field-meta.xml
<CustomField>
    <fullName>Train_handled_by_Auto_Compensation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Train handled by Auto Compensation</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/UIC_To__c.field-meta.xml
<CustomField>
    <fullName>UIC_To__c</fullName>
    <label>UIC To</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/DLT_TrainTriggerHandler.cls
public without sharing class DLT_TrainTriggerHandler {
    public static Boolean isDisabled = false;

    public static void run() {
        if (!System.Trigger.isExecuting || isDisabled) { return; }

        if (System.Trigger.isBefore) {
            if (System.Trigger.isInsert) {
            }

            if (System.Trigger.isUpdate) {
                syncTrainExpertFields((Map<Id, Train__c>) System.Trigger.newMap, (Map<Id, Train__c>) System.Trigger.oldMap);
                preventDelayOverride((List<Train__c>) System.Trigger.new, (Map<Id, Train__c>) System.Trigger.oldMap);
            }
        }

        if (System.Trigger.isAfter) {
            if (System.Trigger.isInsert) {
                calculateGlobalDelayReason((Map<Id, Train__c>) System.Trigger.newMap);
            }

            if (System.Trigger.isUpdate) {
                updateDelayOnTickets((Map<Id, Train__c>) System.Trigger.newMap, (Map<Id, Train__c>) System.Trigger.oldMap);
                createCompensations((Map<Id,Train__c>)Trigger.newMap, (Map<Id,Train__c>)Trigger.oldMap);
                calculateGlobalDelayReason((Map<Id, Train__c>) System.Trigger.newMap, (Map<Id, Train__c>) System.Trigger.oldMap);
            }
        }
    }


    private static void createCompensations(Map<Id,Train__c> newTrainMap, Map<Id,Train__c> oldTrainMap){

        List<Id> trainsToCompensateIds = new List<Id>();

        for(Train__c train : newTrainMap.values()){
            if(   !train.Exempt_from_Auto_Compensation__c 
                && oldTrainMap.get(train.Id).Exempt_from_Auto_Compensation__c 
                && !train.Train_handled_by_Auto_Compensation__c){

                trainsToCompensateIds.add(train.Id);
            }
        }

        if(trainsToCompensateIds.size() > 0){
            String s = '\'' + String.join(trainsToCompensateIds,'\',\'') + '\'';

            String query = 
            'SELECT Id, Train__c, Checked_In__c, Cancelled__c, Travel_DateTime__c, Train__r.Departure_Date_Time__c, UIC_Code__c, Cancelled_By_Customer__c, ' + 
            'Train_No_Catering__c, Train_Unacceptable_Travel_Conditions__c, Delay_mins__c, Train__r.Cancelled__c FROM Ticket__c WHERE Train__r.Cancelled__c = false  AND Train__c IN  (' + s + ')';
    
            Database.executeBatch(new CompApp_ScheduledCompensation(query), 200);
        }
        
    }

    private static void updateDelayOnTickets(Map<Id, Train__c> newMap, Map<Id, Train__c> oldMap){

        if(!DLT_Constants.IS_TRAIN_EXPERT) return;

        Map<Id, Train__c> trainMap = new Map<Id, Train__c>();
        Set<String> uicCodes = new Set<String>();

        for(Train__c train : newMap.values()){
            if(train.Delay_in_Minutes__c != oldMap.get(train.Id).Delay_in_Minutes__c){

                trainMap.put(train.Id, train);
                uicCodes.add(train.UIC_To__c);

            }
        }

        trainMap.remove(null);
        uicCodes.remove(null);
        uicCodes.remove('');

        if (trainMap.isEmpty() && uicCodes.isEmpty()) { return; }

        List<Ticket__c> ticketsToUpdate = new List<Ticket__c>();

        for(Ticket__c t : [
            SELECT Id, UIC_Code__c, Train__c
            FROM Ticket__c
            WHERE Train__c IN :trainMap.keySet()
                AND UIC_Code__c IN :uicCodes
                AND Ticket_Status__c = :DLT_TicketConstants.TICKET_STATUS_ACTIVE
                AND (
                        (Train__r.Carrier__c = :DLT_TrainConstants.CARRIER_BLUE AND Checked_in__c = true)
                        OR Train__r.Carrier__c = :DLT_TrainConstants.CARRIER_RED
                    )
        ]){
            if(trainMap.containsKey(t.Train__c) && t.UIC_Code__c == trainMap.get(t.Train__c).UIC_To__c){
                ticketsToUpdate.add(
                    new Ticket__c (
                        Id = t.Id, 
                        Delay_mins__c = trainMap.get(t.Train__c).Delay_in_Minutes__c,
                        Delay_Mins_Train_Expert__c = trainMap.get(t.Train__c).Delay_in_Minutes__c,
                        Train_Expert__c = UserInfo.getUserId()
                    )
                );
            }
        }

        update ticketsToUpdate;

    }

    private static void preventDelayOverride(List<Train__c> newList, Map<Id, Train__c> oldMap){
        
        if(DLT_Constants.IS_TRAIN_EXPERT) return;

        for(Train__c train : newList){

            if(train.Delay_in_Minutes__c != oldMap.get(train.Id).Delay_in_Minutes__c 
                && train.Delay_Mins_Train_Expert__c != null){

                train.Delay_in_Minutes__c = train.Delay_Mins_Train_Expert__c;
            }
        }
    }

    private static void syncTrainExpertFields(Map<Id, Train__c> newMap, Map<Id, Train__c> oldMap){

        if(!DLT_Constants.IS_TRAIN_EXPERT) return;

        for(Train__c train : newMap.values()){
            if(train.Delay_in_Minutes__c != oldMap.get(train.Id).Delay_in_Minutes__c){

                train.Delay_Mins_Train_Expert__c = train.Delay_in_Minutes__c;
                train.Train_Expert__c = UserInfo.getUserId();

            }

            if(train.Global_Delay_Reason__c != oldMap.get(train.Id).Global_Delay_Reason__c){

                train.Global_Delay_Reason_Train_Expert__c = train.Global_Delay_Reason__c;
                train.Train_Expert__c = UserInfo.getUserId();

            }
        }
    }

    private static void calculateGlobalDelayReason(Map<Id, Train__c> newMap, Map<Id, Train__c> oldMap){

        List<Id> trainIdsToCalculate = new List<Id>();

        for(Train__c train : newMap.values()){
            if(train.Delay_in_Minutes__c != oldMap.get(train.Id).Delay_in_Minutes__c){

                trainIdsToCalculate.add(train.Id);

            }
        }

        DLT_Train_Service.calculateGlobalDelayReason(trainIdsToCalculate);
    }

    private static void calculateGlobalDelayReason(Map<Id, Train__c> newMap){

        DLT_Train_Service.calculateGlobalDelayReason(new List<Id>(newMap.keySet()));
    }

}