GearsetPOC/force-app/main/default/objects/Update_Description_Platform_Event__e/Update_Description_Platform_Event__e.object-meta.xml
<CustomObject>
    <label>Update Description Platform Event</label>
    <pluralLabel>Update Description Platform Events</pluralLabel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Update_Description_Platform_Event__e/fields/Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Id__c</fullName>
    <label>Case Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Update_Description_Platform_Event__e/fields/Comment_Long__c.field-meta.xml
<CustomField>
    <fullName>Comment_Long__c</fullName>
    <label>Comment Long</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/UpdateDescriptionEventHelper.cls
public without sharing class UpdateDescriptionEventHelper {

    public static void updateCaseDescription(List<Update_Description_Platform_Event__e> updateEvents) {
        Set<String> caseIds = new Set<String>();
        Map<String, String> caseDescriptionByIds = new Map<String, String>();
        for (Update_Description_Platform_Event__e updateEvent :updateEvents) {
            caseIds.add(updateEvent.Case_Id__c);
            caseDescriptionByIds.put(updateEvent.Case_Id__c, updateEvent.Comment_Long__c);
        }
        List<Case> cases = [
            SELECT Id, Description
            FROM Case
            WHERE Id IN :caseIds
        ];
        String timeStamp = getCurrentDateTime();
        List<CaseComment> caseCommentsToInsert = new List<CaseComment>();
        for (Case caseItem : cases) {
            caseCommentsToInsert.add(
                new CaseComment(
                    CommentBody = timeStamp + caseDescriptionByIds.get(caseItem.Id),
                    ParentId = caseItem.Id,
                    IsPublished = true
                )
            );
        }
        if (!caseCommentsToInsert.isEmpty()) {
            insert caseCommentsToInsert;
        }
    }

    private static String getCurrentDateTime() {
        Datetime currDateTime = Datetime.now();
        String timeStamp = '[' + currDateTime.format('MM/dd/yyyy HH:mm:ss', 'Europe/London') + '] ';
        return timeStamp;
    }
}