GearsetPOC/force-app/main/default/objects/CloseResponseEmailDisabled__c/CloseResponseEmailDisabled__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CloseResponseEmailDisabled</label>
</CustomObject>

GearsetPOC/force-app/main/default/objects/CloseResponseEmailDisabled__c/fields/Disabled__c.field-meta.xml
<CustomField>
    <fullName>Disabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Disabled</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Salesforce_Support_Request__c/Salesforce_Support_Request__c.object-meta.xml
<CustomObject>
    <description>Salesforce and Marketing Cloud Support Request management</description>
    <label>Salesforce Support Request</label>
    <nameField>
        <displayFormat>SFDC-{0000}</displayFormat>
        <label>Salesforce Support Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Support Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Salesforce_Support_Request__c/fields/Associated_Jira_Id__c.field-meta.xml
<CustomField>
    <fullName>Associated_Jira_Id__c</fullName>
    <label>Associated Jira Id</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Salesforce_Support_Request__c/fields/Closed_By__c.field-meta.xml
<CustomField>
    <fullName>Closed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who set the ticket Status as Closed or Rejected</description>
    <label>Closed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Closers</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Salesforce_Support_Request__c/fields/Cumulative_Request_Age__c.field-meta.xml
<CustomField>
    <fullName>Cumulative_Request_Age__c</fullName>
    <description>To hold Request Age value until request is reopened</description>
    <label>Cumulative Request Age</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Salesforce_Support_Request__c/fields/Date_Time_Closed__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_Closed__c</fullName>
    <label>Date/Time Closed</label>
    <type>DateTime</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Salesforce_Support_Request__c/fields/Date_Time_ReOpened__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_ReOpened__c</fullName>
    <description>Support field required for proper Request Age calculation</description>
    <label>Date/Time ReOpened</label>
    <type>DateTime</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Salesforce_Support_Request__c/fields/Request_Age__c.field-meta.xml
<CustomField>
    <fullName>Request_Age__c</fullName>
    <formula>IF(OR(ISPICKVAL(Status__c, &quot;Closed&quot;),ISPICKVAL(Status__c, &quot;Rejected&quot;)), Cumulative_Request_Age__c,  
   IF(ISBLANK(Date_Time_ReOpened__c), NOW() - Date_Time_Opened__c, NOW() - Date_Time_ReOpened__c + Cumulative_Request_Age__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Request Age</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Salesforce_Support_Request__c/fields/Requester_Email__c.field-meta.xml
<CustomField>
    <fullName>Requester_Email__c</fullName>
    <label>Requester Email</label>
    <type>Email</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Salesforce_Support_Request__c/fields/Requester_Name__c.field-meta.xml
<CustomField>
    <fullName>Requester_Name__c</fullName>
    <description>Name of the requester either populated from related user record or from fromName field on InboundEmail object</description>
    <label>Requester Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Salesforce_Support_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>In progress2</fullName>
            </value>
            <value>
                <fullName>Referred to Requester</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Under Development</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Delta Freeze</fullName>
            </value>
            <value>
                <fullName>Pending Internal Information</fullName>
            </value>
            <value>
                <fullName>Pending Team Resource</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected - other</fullName>
            </value>
            <value>
                <fullName>Rejected - request inaccurate</fullName>
            </value>
            <value>
                <fullName>Rejected - already exists</fullName>
            </value>
            <value>
                <fullName>Rejected - duplicate</fullName>
            </value>
            <value>
                <fullName>Rejected - inaccurate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Salesforce_Support_Request__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Ticket Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Salesforce_Support_Request__c/fields/ThreadID__c.field-meta.xml
<CustomField>
    <fullName>ThreadID__c</fullName>
    <formula>&quot;{&quot; &amp; LEFT($Organization.Id,5) &amp; SUBSTITUTE(RIGHT($Organization.Id,11), &quot;0&quot;, &quot;&quot; )&amp; &quot;._&quot; &amp; LEFT(Id,5) &amp; SUBSTITUTE(Left(RIGHT(Id,10), 5), &quot;0&quot;, &quot;&quot;) &amp; RIGHT(Id,5) &amp; &quot;}&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ThreadID</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Salesforce_Support_Request__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Change Request</fullName>
            </value>
            <value>
                <fullName>Bug Request</fullName>
            </value>
            <value>
                <fullName>New Issue</fullName>
            </value>
            <value>
                <fullName>Already Flagged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Salesforce_Support_Request__c/recordTypes/Bug.recordType-meta.xml
<RecordType>
    <fullName>Bug</fullName>
    <active>true</active>
    <description>To report something is broken</description>
    <label>Bug</label>
</RecordType>

GearsetPOC/force-app/main/default/objects/Salesforce_Support_Request__c/recordTypes/Salesforce_Change_Request.recordType-meta.xml
<RecordType>
    <fullName>Salesforce_Change_Request</fullName>
    <active>true</active>
    <description>Salesforce Change Request</description>
    <label>Salesforce Change Request</label>
</RecordType>

GearsetPOC/force-app/main/default/objects/Salesforce_Support_Request__c/recordTypes/Salesforce_Support.recordType-meta.xml
<RecordType>
    <fullName>Salesforce_Support</fullName>
    <active>true</active>
    <description>Salesforce Support Requests</description>
    <label>Salesforce Support</label>
</RecordType>

GearsetPOC/force-app/main/default/classes/SalesforceSupportRequestUtils.cls
public without sharing class SalesforceSupportRequestUtils {

    public static final Id CHANGE_REQUEST_QUEUE_ID;
    public static final Id BUG_QUEUE_ID;
    public static final String CHANGE_REQUEST_TYPE = 'Change Request';
    public static final String BUG_REQUEST_TYPE = 'Bug Request';
    public static final Id SALESFORCE_CHANGE_REQUEST_RECORD_TYPE_ID;
    public static final Id SALESFORCE_SUPPORT_REQUEST_RECORD_TYPE_ID;
    public static final Id SALESFORCE_BUG_REQUEST_RECORD_TYPE_ID;

    static {
        List<RecordType> recordTypes = [SELECT Id, DeveloperName
                FROM RecordType
                WHERE SobjectType = 'Salesforce_Support_Request__c' AND
                      (DeveloperName = 'Salesforce_Support' OR
                       DeveloperName = 'Salesforce_Change_Request')
        ];
        for (RecordType nextrecordType : recordTypes) {
            if (nextrecordType.DeveloperName.contains('Salesforce_Support')) SALESFORCE_SUPPORT_REQUEST_RECORD_TYPE_ID = nextrecordType.Id;
            if (nextrecordType.DeveloperName.contains('Salesforce_Change_Request')) SALESFORCE_CHANGE_REQUEST_RECORD_TYPE_ID = nextrecordType.Id;
            //if (nextrecordType.DeveloperName.contains('Salesforce_Bug_Request')) SALESFORCE_BUG_REQUEST_RECORD_TYPE_ID = nextrecordType.Id;
        }
        List<Group> queues = [SELECT Id, DeveloperName
                              FROM Group
                              WHERE (DeveloperName = 'Salesforce_Change_Request_Queue' OR
                              DeveloperName = 'Salesforce_Bug_Queue') AND
                              Type='Queue'];
        system.debug(queues);
        for (Group queue : queues) {
            if (queue.DeveloperName.contains('Salesforce_Change_Request_Queue')) CHANGE_REQUEST_QUEUE_ID = queue.Id;
            if (queue.DeveloperName.contains('Salesforce_Bug_Queue')) BUG_QUEUE_ID = queue.Id;
        }
    }

    public static void handleBeforeInsert(List<Salesforce_Support_Request__c> newList) {
        for (Salesforce_Support_Request__c nextReq : newList) {
            if (nextReq.RecordTypeId == SALESFORCE_CHANGE_REQUEST_RECORD_TYPE_ID && !DLT_SFSupportRequestConstants.feedbackRecordTypeIds.contains(nextReq.RecordTypeId)) {
                nextReq.Type__c = CHANGE_REQUEST_TYPE;
                nextReq.OwnerId = CHANGE_REQUEST_QUEUE_ID;
            }
//            if (nextReq.RecordTypeId == SALESFORCE_BUG_REQUEST_RECORD_TYPE_ID) {
//                nextReq.Type__c = BUG_REQUEST_TYPE;
//                nextReq.OwnerId = BUG_QUEUE_ID;
//            }
        }
    }

    public static void handleBeforeUpdate(Map<Id, Salesforce_Support_Request__c> oldMap, Map<Id, Salesforce_Support_Request__c> newMap) {
        List<Messaging.SingleEmailMessage> closedEmailsForSend = new List<Messaging.SingleEmailMessage>();
        List<Salesforce_Support_Request__c> requestsRequiredJira = new List<Salesforce_Support_Request__c>();
        for (Id nextReqId : oldMap.keyset()) {
            Salesforce_Support_Request__c oldReq = oldMap.get(nextReqId);
            Salesforce_Support_Request__c newReq = newMap.get(nextReqId);

            if(DLT_SFSupportRequestConstants.feedbackRecordTypeIds.contains(newReq.RecordTypeId)) { continue; }

            if (oldReq.Type__c != newReq.Type__c)  {
                if (newReq.Type__c == CHANGE_REQUEST_TYPE) {
                    newReq.RecordTypeId = SALESFORCE_CHANGE_REQUEST_RECORD_TYPE_ID;
                }
                //if (newReq.Type__c == BUG_REQUEST_TYPE) {
                //    newReq.RecordTypeId = SALESFORCE_BUG_REQUEST_RECORD_TYPE_ID;
                //}
            }
            if (oldReq.RecordTypeId != newReq.RecordTypeId)  {
                if (newReq.RecordTypeId == SALESFORCE_CHANGE_REQUEST_RECORD_TYPE_ID) {
                    newReq.OwnerId = CHANGE_REQUEST_QUEUE_ID;
                }
                //if (newReq.RecordTypeId == SALESFORCE_BUG_REQUEST_RECORD_TYPE_ID) {
                //    newReq.OwnerId = BUG_QUEUE_ID;
                //}
            }
            if (oldReq.Status__c != newReq.Status__c && (newReq.Status__c == 'Closed' || newReq.Status__c == 'Rejected'))  {
                newReq.Cumulative_Request_Age__c = oldReq.Request_Age__c;
                newReq.Date_Time_Closed__c = Datetime.now();
                newReq.Closed_By__c = UserInfo.getUserId();
                if (newReq.Status__c == 'Closed') {
                    closedEmailsForSend.add(buildOnRequestCloseResponseEmail(newReq));
                }
            }
            if (oldReq.Status__c != newReq.Status__c && (oldReq.Status__c == 'Closed' || oldReq.Status__c == 'Rejected'))  {
                newReq.Date_Time_ReOpened__c = Datetime.now();
            }
            if (newReq.RecordTypeId == SALESFORCE_CHANGE_REQUEST_RECORD_TYPE_ID &&
               (newReq.Associated_Jira_Id__c == null ||
                newReq.Associated_Jira_Id__c == '' ||
                newReq.Associated_Jira_Id__c == JiraConnectorUtils.OPERATION_FAILED) &&
                oldReq.Status__c != newReq.Status__c && newReq.Status__c == 'Backlog') {
                requestsRequiredJira.add(newReq);
            }
        }
        CloseResponseEmailDisabled__c isDisabled = CloseResponseEmailDisabled__c.getInstance('Disabled');
        if (isDisabled != null) {
            if (closedEmailsForSend.size() > 0 && isDisabled.Disabled__c == false) Messaging.sendEmail(closedEmailsForSend);
        }

        //create jira only for single record updates
        if (newMap.keyset().size() == 1 && requestsRequiredJira.size() == 1) {
            createIssue(requestsRequiredJira[0].Id);
        }
    }

    @future(callout=true)
    public static void createIssue(Id requestId) {
        List<Salesforce_Support_Request__c> targetRequests = [
                SELECT Subject__c, Description__c, Associated_Jira_Id__c
                FROM Salesforce_Support_Request__c
                WHERE Id = : requestId
                LIMIT 1
        ];

        if (targetRequests.size() > 0 && (targetRequests[0].Associated_Jira_Id__c == JiraConnectorUtils.OPERATION_FAILED) ||
                                          targetRequests[0].Associated_Jira_Id__c == '' ||
                                          targetRequests[0].Associated_Jira_Id__c == null) {

            targetRequests[0].Associated_Jira_Id__c = JiraConnectorUtils.createIssue(targetRequests[0]);
            if (targetRequests[0].Associated_Jira_Id__c != JiraConnectorUtils.OPERATION_FAILED)
                update targetRequests[0];
        }
    }

    public static void sendAutoResponseEmail(Salesforce_Support_Request__c baseRequest) {
        Messaging.SingleEmailMessage resultMessage = new Messaging.SingleEmailMessage();
        List<Contact> contacts = [SELECT Id FROM Contact WHERE Email = : baseRequest.Requester_Email__c];
        if (contacts.size() > 0) {
            Id templateId = [SELECT Id from EmailTemplate WHERE DeveloperName='Salesforce_Support_Auto_Response' LIMIT 1].Id;
            resultMessage.setTargetObjectId(contacts[0].Id);
            resultMessage.setTemplateId(templateId);
            resultMessage.setWhatId(baseRequest.Id);
        } else {
            resultMessage.setToAddresses(new List<String>{baseRequest.Requester_Email__c});
            resultMessage.setSubject('Thanks for your email.');
            String body = 'Hi ' + baseRequest.Requester_Name__c + ',\r\n\r\nThanks for your email, we have received your request. This is your request no ' + baseRequest.Name + '.\r\n\r\nIf you have any additional questions or information in regards to your issue, please reply to this email.\r\n\r\nWe will respond as soon as soon as possible.\r\n\r\n\r\n\r\nRegards,\r\n\r\nThe Salesforce team\r\n\r\n' + baseRequest.ThreadID__c;
            resultMessage.setPlainTextBody(body);
        }
        resultMessage.setSaveAsActivity(false);
        Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{resultMessage});

    }

    public static Messaging.SingleEmailMessage buildOnRequestCloseResponseEmail(Salesforce_Support_Request__c baseRequest) {
        Messaging.SingleEmailMessage resultMessage = new Messaging.SingleEmailMessage();
        List<Contact> contacts = [SELECT Id FROM Contact WHERE Email = : baseRequest.Requester_Email__c];
        if (contacts.size() > 0) {
            Id templateId = [SELECT Id from EmailTemplate WHERE DeveloperName='Salesforce_Support_On_Request_Close_Auto_Notification' LIMIT 1].Id;
            resultMessage.setTargetObjectId(contacts[0].Id);
            resultMessage.setTemplateId(templateId);
            resultMessage.setWhatId(baseRequest.Id);
        } else {
            resultMessage.setToAddresses(new List<String>{baseRequest.Requester_Email__c});
            resultMessage.setSubject('Thanks for your email.');
            String body = 'Hi ' + baseRequest.Requester_Name__c + ',\r\n\r\nThanks for your email, we have received your request. This is your request no ' + baseRequest.Name + '.\r\n\r\nIf you have any additional questions or information in regards to your issue, please reply to this email.\r\n\r\nWe will respond as soon as soon as possible.\r\n\r\n\r\n\r\nRegards,\r\n\r\nThe Salesforce team\r\n\r\n' + baseRequest.ThreadID__c;
            resultMessage.setPlainTextBody(body);
        }
        resultMessage.setSaveAsActivity(false);

        return resultMessage;
    }
}