GearsetPOC/force-app/main/default/objects/B2b_AccountPCC__c/B2b_AccountPCC__c.object-meta.xml
<CustomObject>
    <description>Custom object migrated from Thango as part of Eurostar Delta migration project. Eurostar Jira ref DEIS-225</description>
    <label>Account PCC</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Account PCC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account PCC&#39;s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/B2b_AccountPCC__c/fields/Active_PCC_Codes__c.field-meta.xml
<CustomField>
    <fullName>Active_PCC_Codes__c</fullName>
    <label>Active PCC Codes</label>
    <summaryFilterItems>
        <field>B2b_AccountPCCCode__c.Active__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>B2b_AccountPCCCode__c.B2b_AccountPCC__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_AccountPCC__c/fields/B2b_Account__c.field-meta.xml
<CustomField>
    <fullName>B2b_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Business_Account__c</referenceTo>
    <relationshipLabel>Account PCC Names</relationshipLabel>
    <relationshipName>Account_PCC_Names</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_AccountPCC__c/fields/B2b_Delete__c.field-meta.xml
<CustomField>
    <fullName>B2b_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Do you want to delete this PCC for this Account?</inlineHelpText>
    <label>Delete</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_AccountPCC__c/fields/PCC_Code_Name__c.field-meta.xml
<CustomField>
    <fullName>PCC_Code_Name__c</fullName>
    <formula>B2b_OfficeId__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PCC Code</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_AccountPCCCode__c/B2b_AccountPCCCode__c.object-meta.xml
<CustomObject>
    <description>Junction Object delivered to support New Corporate Offer Project May /June 2024</description>
    <label>Account PCC Code</label>
    <nameField>
        <displayFormat>APC- {000000}</displayFormat>
        <label>Account PCC Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account PCC Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/B2b_AccountPCCCode__c/fields/B2b_AccountPCC__c.field-meta.xml
<CustomField>
    <fullName>B2b_AccountPCC__c</fullName>
    <label>Account PCC</label>
    <referenceTo>B2b_AccountPCC__c</referenceTo>
    <relationshipLabel>Account PCC Codes</relationshipLabel>
    <relationshipName>Account_PCC_Codes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/B2b_NrDetails__c.object-meta.xml
<CustomObject>
    <description>Custom object migrated from Thango as part of Eurostar Delta migration project. Eurostar Jira ref DEIS-320</description>
    <label>Negotiated Rate</label>
    <nameField>
        <displayFormat>NR-{0000}</displayFormat>
        <label>Negotiated Rates SF Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Negotiated Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/fields/Account_PCC_s__c.field-meta.xml
<CustomField>
    <fullName>Account_PCC_s__c</fullName>
    <label>Account PCC’s</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>this is to Support the Negotiated Rates List Views</description>
    <formula>CASESAFEID(ContractID__r.AccountId__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AccountId</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/fields/B2b_Account__c.field-meta.xml
<CustomField>
    <fullName>B2b_Account__c</fullName>
    <formula>HYPERLINK(ContractID__r.AccountId__c, ContractID__r.AccountId__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/fields/B2b_Status__c.field-meta.xml
<CustomField>
    <fullName>B2b_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>To be Extracted</fullName>
            </value>
            <value>
                <fullName>Extracted</fullName>
            </value>
            <value>
                <fullName>Integrated</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>To be Approved</fullName>
            </value>
            <value>
                <fullName>New - Default</fullName>
                <isActive>false</isActive>
                <label>New - Default</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/fields/ContractID__c.field-meta.xml
<CustomField>
    <fullName>ContractID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Business_Contract__c</referenceTo>
    <relationshipLabel>Negotiated Rates</relationshipLabel>
    <relationshipName>Negotiated_Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/fields/PCC_Changed__c.field-meta.xml
<CustomField>
    <fullName>PCC_Changed__c</fullName>
    <label>PCC Changed</label>
    <type>Date</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/fields/PCC_Codes__c.field-meta.xml
<CustomField>
    <fullName>PCC_Codes__c</fullName>
    <label>PCC Codes</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/fields/PCC_Extract__c.field-meta.xml
<CustomField>
    <fullName>PCC_Extract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PCC Extract</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/Business_Account__c.object-meta.xml
<CustomObject>
    <description>Custom Business Account object created as part of Eurostar Delta migration project. Eurostar Jira ref DEIS-281</description>
    <label>Business Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/Account_PCC__c.field-meta.xml
<CustomField>
    <fullName>Account_PCC__c</fullName>
    <label># Account PCC</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/FCE_Continent__c.field-meta.xml
<CustomField>
    <fullName>FCE_Continent__c</fullName>
    <label>FCE Continent</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/FCE_London__c.field-meta.xml
<CustomField>
    <fullName>FCE_London__c</fullName>
    <label>FCE London</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/GDS_Code__c.field-meta.xml
<CustomField>
    <fullName>GDS_Code__c</fullName>
    <label>GDS Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/GND_BE_Continent__c.field-meta.xml
<CustomField>
    <fullName>GND_BE_Continent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Start with 40 and then click search</inlineHelpText>
    <label>GND BE Continent</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Corp_Tracking_Type_and_Code__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>GND_Belgium_Continent</value>
        </filterItems>
        <filterItems>
            <field>Corp_Tracking_Type_and_Code__c.B2b_IsUsed__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Corp_Tracking_Type_and_Code__c.B2b_Account__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Corp_Tracking_Type_and_Code__c</referenceTo>
    <relationshipLabel>Business Accounts (GND BE Continent)</relationshipLabel>
    <relationshipName>Business_Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/GND_BE_London__c.field-meta.xml
<CustomField>
    <fullName>GND_BE_London__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GND BE London</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Corp_Tracking_Type_and_Code__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>GND_Belgium_London</value>
        </filterItems>
        <filterItems>
            <field>Corp_Tracking_Type_and_Code__c.B2b_IsUsed__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Corp_Tracking_Type_and_Code__c.B2b_Account__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Corp_Tracking_Type_and_Code__c</referenceTo>
    <relationshipLabel>Business Accounts (GND London Continent)</relationshipLabel>
    <relationshipName>Business_Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/GND_NL_Continent__c.field-meta.xml
<CustomField>
    <fullName>GND_NL_Continent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GND NL Continent</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Corp_Tracking_Type_and_Code__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>GND_The_Netherlands_Continent</value>
        </filterItems>
        <filterItems>
            <field>Corp_Tracking_Type_and_Code__c.B2b_IsUsed__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Corp_Tracking_Type_and_Code__c.B2b_Account__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Corp_Tracking_Type_and_Code__c</referenceTo>
    <relationshipLabel>Business Accounts (GND NL Continent)</relationshipLabel>
    <relationshipName>Business_Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Contract__c/Business_Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Business Contract object created as part of Eurostar Delta migration project. Eurostar Jira ref DEIS-283</description>
    <label>Business Contract</label>
    <nameField>
        <displayFormat>CO-{000000}</displayFormat>
        <label>Contract Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Business_Contract__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Business_Account__c</referenceTo>
    <relationshipLabel>Business Contracts (Account Name)</relationshipLabel>
    <relationshipName>Business_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Contract__c/fields/B2b_Status__c.field-meta.xml
<CustomField>
    <fullName>B2b_Status__c</fullName>
    <label>Status (delete)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/NR_to_Account_PCC__c/NR_to_Account_PCC__c.object-meta.xml
<CustomObject>
    <description>This is to support the extracts of Negotiated Rates that reference the Account PCC’s.</description>
    <label>NR to Account PCC</label>
    <nameField>
        <label>PCC Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NR to Account PCCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/NR_to_Account_PCC__c/fields/Account_PCC__c.field-meta.xml
<CustomField>
    <fullName>Account_PCC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account PCC</label>
    <referenceTo>B2b_AccountPCC__c</referenceTo>
    <relationshipLabel>NR to Account PCCs</relationshipLabel>
    <relationshipName>NR_to_Account_PCCs</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/NR_to_Account_PCC__c/fields/Negotiated_Rate__c.field-meta.xml
<CustomField>
    <fullName>Negotiated_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Negotiated Rate</label>
    <referenceTo>B2b_NrDetails__c</referenceTo>
    <relationshipLabel>NR to Account PCCs</relationshipLabel>
    <relationshipName>NR_to_Account_PCCs</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/DLT_AccountPccTriggerHandler.cls
public without sharing class DLT_AccountPccTriggerHandler {
    public static Boolean isDisabled = false;

    public static void run() {
        if (!System.Trigger.isExecuting || isDisabled) { return; }

        if (System.Trigger.isBefore) {
            if (System.Trigger.isInsert) {
            }

            if (System.Trigger.isUpdate) {
                handlePccDelete((Map<Id, B2b_AccountPCC__c>) System.Trigger.oldMap, System.Trigger.new);
            }

            if(Trigger.isDelete) {
                deleteNrToAccountPcc(System.Trigger.old);
                handlePccDelete(System.Trigger.old);
            }
        }

        if (System.Trigger.isAfter) {
            if (System.Trigger.isInsert) {
                handlePccInsert(System.Trigger.new);
            }

            if (System.Trigger.isUpdate) {
                handlePccFieldUpdate((Map<Id, B2b_AccountPCC__c>) System.Trigger.oldMap, System.Trigger.new);
            }
        }
    }

    private static void deleteNrToAccountPcc(List<B2b_AccountPCC__c> accountPCC) {

        List<NR_to_Account_PCC__c> junctionToDelete = [
            SELECT Id
            FROM NR_to_Account_PCC__c
            WHERE Account_PCC__c IN :accountPCC
        ];

        if(!junctionToDelete.isEmpty()) {
            delete junctionToDelete;
        }
    }

    private static void handlePccDelete(List<B2b_AccountPCC__c> oldPCCs) {
        adjustPccNumber(oldPCCs);
    }

    private static void handlePccInsert(List<B2b_AccountPCC__c> newPCCs) {
        Map<Id, B2b_AccountPCC__c> accountToPccMap = new Map<Id, B2b_AccountPCC__c>();
        for (B2b_AccountPCC__c newPCC : newPCCs) {
            if (isRecordTypeOperational(newPCC)) {
                accountToPccMap.put(newPCC.B2b_Account__c, newPCC);
            }
        }
        updateActiveRatePccData(accountToPccMap);
        adjustPccNumber(newPCCs);
        DLT_BusinessAccountService.iterateMissingAccPccCodesCount(accountToPccMap.keySet());
    }

    private static void handlePccFieldUpdate(Map<Id, B2b_AccountPCC__c> oldPCCs, List<B2b_AccountPCC__c> newPCCs) {
        Set<Id> filteredDeletedIds = new Set<Id>();
        Set<Id> filteredDeletedAccountPccIds = new Set<Id>();
        Set<Id> accIdsOfAccPccsWithNoCodes = new Set<Id>();
        Map<Id, B2b_AccountPCC__c> accountToPccMap = new Map<Id, B2b_AccountPCC__c>();
        for (B2b_AccountPCC__c updatedAccountPCC : newPCCs) {
            if (isRecordTypeChangedToDeleted(oldPCCs, updatedAccountPCC)) {
                filteredDeletedIds.add(updatedAccountPCC.B2b_Account__c);
                filteredDeletedAccountPccIds.add(updatedAccountPCC.Id);
            }
            if (isRecordTypeChangedToOperational(oldPCCs, updatedAccountPCC)) {
                accountToPccMap.put(updatedAccountPCC.B2b_Account__c, updatedAccountPCC);
            }
            if (updatedAccountPCC.Active_PCC_Codes__c == 0) {
                accIdsOfAccPccsWithNoCodes.add(updatedAccountPCC.B2b_Account__c);
            }
        }

        updateNegotiatedRatePccData(filteredDeletedIds);
        updateActiveRatePccData(accountToPccMap);
        adjustPccNumber(newPCCs);
        deactivateAccountPccCodes(filteredDeletedAccountPccIds);
        DLT_BusinessAccountService.updateMissingAccPccCodesCount(accIdsOfAccPccsWithNoCodes);
    }

    private static void handlePccDelete(Map<Id, B2b_AccountPCC__c> oldPCCs, List<B2b_AccountPCC__c> newPCCs) {
        for (B2b_AccountPCC__c updatedAccountPCC : newPCCs) {
            if (isDeletedChanged(oldPCCs, updatedAccountPCC)) {
                handleDeleteChanged(updatedAccountPCC);
            }
        }
    }

    // ========================= HELPERS =========================

    private static void deactivateAccountPccCodes(Set<Id> accountPccIds) {
        if (accountPccIds.isEmpty()) { return; }

        List<B2b_AccountPCCCode__c> codes = [
            SELECT Active__c
            FROM B2b_AccountPCCCode__c
            WHERE B2b_AccountPCC__c IN :accountPccIds
        ];

        for (B2b_AccountPCCCode__c code : codes) {
            code.Active__c = false;
        }

        update codes;
    }

    private static void updateActiveRatePccData(Map<Id, B2b_AccountPCC__c> accountToPccMap) {
        Map<Id, List<B2b_NrDetails__c>> accountToRatesMap = new Map<Id, List<B2b_NrDetails__c>>();
        List<B2b_NrDetails__c> rates = getConnectedToPccRates(accountToPccMap.keySet());

        for (B2b_NrDetails__c rate : rates) {
            rate.Account_PCC_s__c = '';
            if (accountToRatesMap.get(rate.ContractID__r.AccountId__c) == null) {
                accountToRatesMap.put(rate.ContractID__r.AccountId__c, new List<B2b_NrDetails__c>());
            }
            accountToRatesMap.get(rate.ContractID__r.AccountId__c).add(rate);
            setPccData(rate);
        }

        B2b_AccountPCC__c pcc;
        List<B2b_NrDetails__c> negotiatedRates;
        List<NR_to_Account_PCC__c> neAccountPCCs = new List<NR_to_Account_PCC__c>();
        for (Id accId : accountToPccMap.keySet()) {
            pcc = accountToPccMap.get(accId);
            negotiatedRates = accountToRatesMap.get(accId);
            if (negotiatedRates == null || negotiatedRates.isEmpty() || pcc?.Id == null) {
                continue;
            }
            for (B2b_NrDetails__c negotiatedRate : negotiatedRates) {
                DLT_NegotiatedRateTriggerHandler.skipPccUpdatedIds.add(negotiatedRate.Id);
                neAccountPCCs.add(
                    new NR_to_Account_PCC__c(
                        Negotiated_Rate__c = negotiatedRate.Id,
                        Account_PCC__c = pcc.Id
                    )
                );
                negotiatedRate.Account_PCC_s__c
                    += negotiatedRate.Account_PCC_s__c == '' ? pcc.Name : ';' + pcc.Name;

                negotiatedRate.PCC_Codes__c 
                    += String.isBlank(negotiatedRate.PCC_Codes__c) ? pcc.PCC_Code_Name__c : ';' + pcc.PCC_Code_Name__c;

                negotiatedRate.PCC_Codes__c = negotiatedRate.PCC_Codes__c.removeStart('null');
            }
        }

        insert neAccountPCCs;

        update rates;
    }

    private static void updateNegotiatedRatePccData(Set<Id> accountIds) {
        if (accountIds == null || accountIds.isEmpty()) {
            return;
        }

        List<B2b_NrDetails__c> rates = getConnectedToPccRates(accountIds);

        for (B2b_NrDetails__c rate : rates) {
            setPccData(rate);
        }

        update rates;
    }

    private static void setPccData(B2b_NrDetails__c rate) {
        rate.PCC_Extract__c = true;
        rate.B2b_Status__c = DLT_NegotiatedRateConstants.STATUS_TO_BE_EXTRACTED;
        rate.PCC_Changed__c = System.today();
    }

    private static void adjustPccNumber(List<B2b_AccountPCC__c> pccs) {
        Set<Id> businessIds = new Set<Id>();
        for (B2b_AccountPCC__c pcc : pccs) {
            businessIds.add(pcc.B2b_Account__c);
        }

        List<Business_Account__c> businessAccounts = [
            SELECT
                (SELECT Id
                    FROM Account_PCC_Names__r
                    WHERE RecordTypeId =: DLT_AccountPccConstants.RECORD_TYPE_OPERATIONAL
                )
            FROM Business_Account__c
            WHERE Id IN :businessIds
        ];

        for (Business_Account__c businessAccount : businessAccounts) {
            businessAccount.Account_PCC__c = businessAccount.Account_PCC_Names__r.size();
        }

        update businessAccounts;
    }

    private static void handleDeleteChanged(B2b_AccountPCC__c accountPCC) {
        if (accountPCC.B2b_Delete__c) {
            accountPCC.recordTypeId = DLT_AccountPccConstants.RECORD_TYPE_DELETED;
        } else {
            accountPCC.recordTypeId = DLT_AccountPccConstants.RECORD_TYPE_OPERATIONAL;
        }
    }

    private static Boolean isRecordTypeOperational(B2b_AccountPCC__c pcc) {
        return pcc?.recordTypeId == DLT_AccountPccConstants.RECORD_TYPE_OPERATIONAL;
    }

    private static Boolean isRecordTypeDeleted(B2b_AccountPCC__c pcc) {
        return pcc?.recordTypeId == DLT_AccountPccConstants.RECORD_TYPE_DELETED;
    }

    private static Boolean isRecordTypeChangedToOperational(Map<Id, B2b_AccountPCC__c> oldPCCs, B2b_AccountPCC__c newPCC) {
        return isRecordTypeOperational(newPCC) && oldPCCs?.get(newPCC.Id)?.recordTypeId != newPCC?.recordTypeId;
    }

    private static Boolean isRecordTypeChangedToDeleted(Map<Id, B2b_AccountPCC__c> oldPCCs, B2b_AccountPCC__c newPCC) {
        return isRecordTypeDeleted(newPCC) && oldPCCs?.get(newPCC.Id)?.recordTypeId != newPCC?.recordTypeId;
    }

    private static Boolean isDeletedChanged(Map<Id, B2b_AccountPCC__c> oldPCCs, B2b_AccountPCC__c newPCC) {
        return oldPCCs?.get(newPCC.Id)?.B2b_Delete__c != newPCC?.B2b_Delete__c;
    }

    private static List<B2b_NrDetails__c> getConnectedToPccRates(Set<Id> accountIds) {
        return [
            SELECT Id, ContractID__r.AccountId__c, Account_PCC_s__c, PCC_Codes__c
            FROM B2b_NrDetails__c
            WHERE ContractID__c IN
                (SELECT Id
                FROM Business_Contract__c
                WHERE AccountId__c IN :accountIds
                    AND (AccountId__r.FCE_Continent__c != NULL OR AccountId__r.GND_BE_Continent__c != NULL
                        OR AccountId__r.GND_NL_Continent__c != NULL OR AccountId__r.GDS_Code__c != NULL
                        OR AccountId__r.FCE_London__c != NULL OR AccountId__r.GND_BE_London__c != NULL
                        OR AccountId__r.GND_NL_London__c != NULL OR AccountId__r.Corporate_Code__c != NULL
                        OR AccountId__r.No_Continent_Account_CTC__c > 0
                    )
                )
                AND (B2b_RouteEndDate__c = NULL OR B2b_RouteEndDate__c > TODAY)
        ];
    }
}