GearsetPOC/force-app/main/default/objects/B2b_AccountPCC__c/B2b_AccountPCC__c.object-meta.xml
<CustomObject>
    <description>Custom object migrated from Thango as part of Eurostar Delta migration project. Eurostar Jira ref DEIS-225</description>
    <label>Account PCC</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Account PCC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account PCC&#39;s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/B2b_AccountPCC__c/fields/B2b_Account__c.field-meta.xml
<CustomField>
    <fullName>B2b_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Business_Account__c</referenceTo>
    <relationshipLabel>Account PCC Names</relationshipLabel>
    <relationshipName>Account_PCC_Names</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_AccountPCCCode__c/B2b_AccountPCCCode__c.object-meta.xml
<CustomObject>
    <description>Junction Object delivered to support New Corporate Offer Project May /June 2024</description>
    <label>Account PCC Code</label>
    <nameField>
        <displayFormat>APC- {000000}</displayFormat>
        <label>Account PCC Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account PCC Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/B2b_AccountPCCCode__c/fields/B2b_AccountPCC__c.field-meta.xml
<CustomField>
    <fullName>B2b_AccountPCC__c</fullName>
    <label>Account PCC</label>
    <referenceTo>B2b_AccountPCC__c</referenceTo>
    <relationshipLabel>Account PCC Codes</relationshipLabel>
    <relationshipName>Account_PCC_Codes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_AccountPCCCode__c/fields/Corp_Tracking_Type_And_Code__c.field-meta.xml
<CustomField>
    <fullName>Corp_Tracking_Type_And_Code__c</fullName>
    <label>Corporate Code</label>
    <referenceTo>Corp_Tracking_Type_and_Code__c</referenceTo>
    <relationshipLabel>Account PCC Codes</relationshipLabel>
    <relationshipName>Account_PCC_Codes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/B2b_NrDetails__c.object-meta.xml
<CustomObject>
    <description>Custom object migrated from Thango as part of Eurostar Delta migration project. Eurostar Jira ref DEIS-320</description>
    <label>Negotiated Rate</label>
    <nameField>
        <displayFormat>NR-{0000}</displayFormat>
        <label>Negotiated Rates SF Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Negotiated Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>this is to Support the Negotiated Rates List Views</description>
    <formula>CASESAFEID(ContractID__r.AccountId__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AccountId</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/fields/B2b_Account__c.field-meta.xml
<CustomField>
    <fullName>B2b_Account__c</fullName>
    <formula>HYPERLINK(ContractID__r.AccountId__c, ContractID__r.AccountId__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/fields/B2b_RouteEndDate__c.field-meta.xml
<CustomField>
    <fullName>B2b_RouteEndDate__c</fullName>
    <label>Route End Date</label>
    <type>Date</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/fields/B2b_Status__c.field-meta.xml
<CustomField>
    <fullName>B2b_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>To be Extracted</fullName>
            </value>
            <value>
                <fullName>Extracted</fullName>
            </value>
            <value>
                <fullName>Integrated</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>To be Approved</fullName>
            </value>
            <value>
                <fullName>New - Default</fullName>
                <isActive>false</isActive>
                <label>New - Default</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/fields/ContractID__c.field-meta.xml
<CustomField>
    <fullName>ContractID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Business_Contract__c</referenceTo>
    <relationshipLabel>Negotiated Rates</relationshipLabel>
    <relationshipName>Negotiated_Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Contract__c/Business_Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Business Contract object created as part of Eurostar Delta migration project. Eurostar Jira ref DEIS-283</description>
    <label>Business Contract</label>
    <nameField>
        <displayFormat>CO-{000000}</displayFormat>
        <label>Contract Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Business_Contract__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Business_Account__c</referenceTo>
    <relationshipLabel>Business Contracts (Account Name)</relationshipLabel>
    <relationshipName>Business_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Contract__c/fields/B2b_Status__c.field-meta.xml
<CustomField>
    <fullName>B2b_Status__c</fullName>
    <label>Status (delete)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Contract__c/fields/End_of_Contract__c.field-meta.xml
<CustomField>
    <fullName>End_of_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Manually set by the Account Manager to confirm the contract has ended</description>
    <label>End of Contract</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Corp_Tracking_Type_and_Code__c/Corp_Tracking_Type_and_Code__c.object-meta.xml
<CustomObject>
    <label>Corporate Tracking</label>
    <nameField>
        <label>Corporate Tracking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corporate Trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Corp_Tracking_Type_and_Code__c/fields/B2b_Account__c.field-meta.xml
<CustomField>
    <fullName>B2b_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Business_Account__c</referenceTo>
    <relationshipLabel>Corporate Trackings</relationshipLabel>
    <relationshipName>Corporate_Trackings</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/AccountPccCodeTriggerHandler.cls
public without sharing class AccountPccCodeTriggerHandler {
    public static Boolean isDisabled = false;
    public static void run() {
        if (!System.Trigger.isExecuting || isDisabled) { return; }
        if (System.Trigger.isAfter) {
            if (System.Trigger.isInsert) {
                updateRelatedNegotiatedRates(Trigger.new);
                updateRelatedBusinessAccounts(Trigger.new, null);
            }

            if (System.Trigger.isUpdate) {
                updateRelatedNegotiatedRates(Trigger.new, (Map<Id, B2b_AccountPCCCode__c>) Trigger.oldMap);
                updateRelatedBusinessAccounts(Trigger.new, (Map<Id, B2b_AccountPCCCode__c>) Trigger.oldMap);
            }

            if (System.Trigger.isDelete) {
                updateRelatedNegotiatedRates(Trigger.old);
            }
        }
    }

    private static void updateRelatedBusinessAccounts(List<B2b_AccountPCCCode__c> accountPccCodeList, Map<Id, B2b_AccountPCCCode__c> oldAccountPccCodeMap) {
        Set<Id> accountPccIds = new Set<Id>();
        Map<Id, Integer> codeIdsInAssignmentProcess = new Map<Id, Integer>();

        for (B2b_AccountPCCCode__c accountPccCode : accountPccCodeList) {
            if (oldAccountPccCodeMap == null || accountPccCode.Active__c != oldAccountPccCodeMap.get(accountPccCode.Id).Active__c) {
                accountPccIds.add(accountPccCode.B2b_AccountPCC__c);

                // count how many codes activated and deactivated to recalculate values from rollup fields
                if (!codeIdsInAssignmentProcess.containsKey(accountPccCode.Corp_Tracking_Type_and_Code__c)) {
                    codeIdsInAssignmentProcess.put(accountPccCode.Corp_Tracking_Type_and_Code__c, accountPccCode.Active__c ? 1 : -1);
                } else {
                    Integer currNum = accountPccCode.Active__c ?
                                      codeIdsInAssignmentProcess.get(accountPccCode.Corp_Tracking_Type_and_Code__c) + 1 :
                                      codeIdsInAssignmentProcess.get(accountPccCode.Corp_Tracking_Type_and_Code__c) - 1;
                    codeIdsInAssignmentProcess.put(accountPccCode.Corp_Tracking_Type_and_Code__c, currNum);
                }
            }
        }

        Set<Id> businessAccountIds = getBusinessAccountIds(accountPccIds);
        DLT_BusinessAccountService.updateMissingAccPccCodesCount(businessAccountIds, codeIdsInAssignmentProcess);
    }

    private static Set<Id> getBusinessAccountIds(Set<Id> accountPccIds) {
        Set<Id> businessAccountIds = new Set<Id>();
        for (B2b_AccountPCC__c accountPcc : [SELECT B2b_Account__c FROM B2b_AccountPCC__c WHERE Id IN : accountPccIds]) {
            businessAccountIds.add(accountPcc.B2b_Account__c);
        }
        return businessAccountIds;
    }

    private static void updateRelatedNegotiatedRates(List<B2b_AccountPCCCode__c> accountPccCodeList, Map<Id, B2b_AccountPCCCode__c> oldAccountPccCodeMap) {
        List<B2b_AccountPCCCode__c> accountPccCodeChangedList = new List<B2b_AccountPCCCode__c>();
        for (B2b_AccountPCCCode__c accountPccCode : accountPccCodeList) {
            if(accountPccCode.Active__c != oldAccountPccCodeMap.get(accountPccCode.Id).Active__c) {
                accountPccCodeChangedList.add(accountPccCode);
            }
        }
        if(!accountPccCodeChangedList.isEmpty()) {
            updateRelatedNegotiatedRates(accountPccCodeChangedList);
        }
    }
    private static void updateRelatedNegotiatedRates(List<B2b_AccountPCCCode__c> accountPccCodeList) {
        Set<Id> accountPccIds = new Set<Id>();
        for (B2b_AccountPCCCode__c accountPccCode : accountPccCodeList) {
            accountPccIds.add(accountPccCode.B2b_AccountPCC__c);
        }
        List<B2b_AccountPCC__c> accountPccList = [
            SELECT B2b_Account__c 
            FROM B2b_AccountPCC__c 
            WHERE Id IN : accountPccIds
        ];
        Set<Id> accountIds = new Set<Id>();
        for (B2b_AccountPCC__c accountPcc : accountPccList) {
            accountIds.add(accountPcc.B2b_Account__c);
        }
        
        List<B2b_NrDetails__c> rates = [
            SELECT ContractID__r.AccountId__c
            FROM B2b_NrDetails__c
            WHERE ContractID__r.AccountId__c IN : accountIds 
                AND ContractID__r.End_of_Contract__c = false
                AND (B2b_RouteEndDate__c = null
                    OR B2b_RouteEndDate__c = TODAY
                    OR B2b_RouteEndDate__c > TODAY)
        ];

        if (rates.isEmpty()) { return; }

        for (B2b_NrDetails__c rate : rates) {
            rate.B2b_Status__c = DLT_NegotiatedRateConstants.STATUS_TO_BE_EXTRACTED;
        }

        update rates;
    }
}