GearsetPOC/force-app/main/default/objects/Application_Audit__c/Application_Audit__c.object-meta.xml
<CustomObject>
    <label>Application Audit</label>
    <nameField>
        <displayFormat>AA-{0000}</displayFormat>
        <label>Application Audit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Application_Audit__c/fields/Contract_Start__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start__c</fullName>
    <label>Contract Start</label>
    <type>Date</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Application_Audit__c/fields/Trading_Account__c.field-meta.xml
<CustomField>
    <fullName>Trading_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Trading Name</label>
    <referenceTo>Business_Account__c</referenceTo>
    <relationshipLabel>Application Audits</relationshipLabel>
    <relationshipName>Application_Audits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/Business_Account__c.object-meta.xml
<CustomObject>
    <description>Custom Business Account object created as part of Eurostar Delta migration project. Eurostar Jira ref DEIS-281</description>
    <label>Business Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/Annual_Review_Reneg__c.field-meta.xml
<CustomField>
    <fullName>Annual_Review_Reneg__c</fullName>
    <description>date of annual review before contract expires</description>
    <label>Annual Review / Renegotiation</label>
    <type>Date</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/DLT_ApplicationAuditTriggerHandler.cls
public with sharing class DLT_ApplicationAuditTriggerHandler {

    public static Boolean isDisabled = false;
    
    public static void run() {
        if (!System.Trigger.isExecuting || isDisabled) { return; }

        if (System.Trigger.isBefore) {
            if (System.Trigger.isInsert) {
            }

            if (System.Trigger.isUpdate) {
            }
        }

        if (System.Trigger.isAfter) {
            if (System.Trigger.isInsert) {
                updateRelatedBusinessAccount(Trigger.new);
            }

            if (System.Trigger.isUpdate) {
            }
        }
    }

    public static void updateRelatedBusinessAccount(List<Application_Audit__c> appAuditList){

    List<Business_Account__c> businessAccountsToUpdate = new List<Business_Account__c>();

        for(Application_Audit__c aa : appAuditList){
            if(aa.Contract_Start__c != null){
                businessAccountsToUpdate.add(new Business_Account__c( 
                    Id = aa.Trading_Account__c,
                    Annual_Review_Reneg__c = aa.Contract_Start__c.addYears(1)
                ));
            }
        }

        if(businessAccountsToUpdate.size() > 0){
            DLT_BusinessAccountTriggerHandler.isDisabled = true;
            update businessAccountsToUpdate;
            DLT_BusinessAccountTriggerHandler.isDisabled = false;
        }
    }


}