GearsetPOC/force-app/main/default/objects/Case/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <defaultValue>CASE($User.Train_Service__c,
&quot;Red&quot;,&quot;Red&quot;,
&quot;Blue&quot;,&quot;Blue&quot;,
&quot;Purple&quot;)</defaultValue>
    <label>Carrier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Train__c.field-meta.xml
<CustomField>
    <fullName>Train__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Train at the origin of the case</description>
    <inlineHelpText>Train at the origin of the case</inlineHelpText>
    <label>Disruption Train</label>
    <referenceTo>Train__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <displayFormat>C{000000000}</displayFormat>
        <label>Compensation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <formula>IF( AND(NOT( ISBLANK( Train__c )), NOT( ISBLANK( Train__r.Carrier__c )), NOT(Train__r.Carrier__c == &#39;Purple&#39;))  , 
Train__r.Carrier__c, 
IF( AND(NOT( ISBLANK(  Ticket__c )) ,NOT( TEXT( Ticket__r.Carrier__c ) == &#39;&#39;), NOT(TEXT(Ticket__r.Carrier__c) == &#39;Purple&#39;))  , 
TEXT(Ticket__r.Carrier__c), 
IF( AND(NOT( ISBLANK(  Case__c )) ,NOT( TEXT( Case__r.Carrier__c ) == &#39;&#39;), NOT(TEXT(Case__r.Carrier__c) == &#39;Purple&#39;))  , 
TEXT(Case__r.Carrier__c), 
IF( AND(NOT( ISBLANK(  CreatedById )) , NOT( TEXT( CreatedBy.Train_Service__c  ) == &#39;&#39;),  NOT(TEXT(CreatedBy.Train_Service__c ) == &#39;Purple&#39;)) ,
TEXT(CreatedBy.Train_Service__c ),
&#39;Blue&#39;))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Carrier</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Carrier_was_defaulted__c.field-meta.xml
<CustomField>
    <fullName>Carrier_was_defaulted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Carrier was defaulted</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Compensation</relationshipLabel>
    <relationshipName>Compensations</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Claim_Status__c.field-meta.xml
<CustomField>
    <fullName>Claim_Status__c</fullName>
    <label>Claim Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Claimed</fullName>
            </value>
            <value>
                <fullName>Error Occured</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Is_Online_Compensation__c.field-meta.xml
<CustomField>
    <fullName>Is_Online_Compensation__c</fullName>
    <description>Created to Support Marketing Cloud Synchronisation: https://eurostar.atlassian.net/browse/DECS-1467</description>
    <formula>RecordType.DeveloperName = &quot;Online&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Online Compensation</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Compensations</relationshipLabel>
    <relationshipName>Compensations</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Train__c.field-meta.xml
<CustomField>
    <fullName>Train__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Train</label>
    <referenceTo>Train__c</referenceTo>
    <relationshipLabel>Compensations</relationshipLabel>
    <relationshipName>Compensations</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>TCN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <label>Carrier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Train__c.field-meta.xml
<CustomField>
    <fullName>Train__c</fullName>
    <label>Train</label>
    <referenceTo>Train__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/Train__c.object-meta.xml
<CustomObject>
    <label>Train</label>
    <nameField>
        <label>Train ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <label>Carrier</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/DLT_CompensationTriggerHandler.cls
public without sharing class DLT_CompensationTriggerHandler {
    public static Boolean isDisabled = false;

    public static void run() {
        if (!System.Trigger.isExecuting || isDisabled) { return; }

        if (System.Trigger.isBefore) {
            if (System.Trigger.isInsert) {
                setInitialValues(Trigger.new);
            }

            if (System.Trigger.isUpdate) {
            }
        }

        if (System.Trigger.isAfter) {
            if (System.Trigger.isInsert) {
                checkIfCarrierIsDeafult(new List<Id>(Trigger.newMap.keySet()));
            }

            if (System.Trigger.isUpdate) {
                updateRelatedCases(Trigger.newMap.keySet());
            }
        }
    }

    private static void updateRelatedCases(Set<Id> compensationIds){

        if(DLT_Utils.isAsyncCtx()){
            DLT_CompensationService.updateRelatedCases(compensationIds);
        }
        else{
            System.enqueueJob(new DLT_CompensationTriggerQueHelper(
                DLT_CompensationTriggerQueHelper.Mode.UPDATE_RELATED_CASES_AFTER_COMPENSATION_UPDATE,
                compensationIds
            ));
        }
    }

    private static void setInitialValues(List<Compensation__c> compensationsToModify) {
        for (Compensation__c comp : compensationsToModify) {

            if (comp.recordTypeId == DLT_CompensationConstants.RECORD_TYPE_ID_POINTS) {
                comp.Claim_Status__c = DLT_CompensationConstants.COMP_CLAIM_STATUS_CLAIMED;
            }

            if(comp.RecordTypeId == DLT_CompensationConstants.RECORD_TYPE_ID_ONLINE){
                comp.Is_Online_Compensation__c = true;
            }
        }
    }

    public static void checkIfCarrierIsDeafult(List<Id> compensations){

        List<Compensation__c> compensationsWithDefault = [
            SELECT Id, Train__r.Carrier__c, Ticket__r.Carrier__c, Case__r.Carrier__c, CreatedBy.Train_Service__c, Train__c, Ticket__c, Case__c
            FROM Compensation__c 
            WHERE Id IN :compensations
                AND RecordTypeId = :DLT_CompensationConstants.RECORD_TYPE_ID_VOUCHER
            ];

        for(Compensation__c c : compensationsWithDefault){
        
            c.Carrier_was_defaulted__c = (c.Train__c != null && c.Train__r.Carrier__c != null && c.Train__r.Carrier__c != DLT_CaseConstants.CARRIER_PURPLE) ? false : 
                ((c.Ticket__c != null && c.Ticket__r.Carrier__c != null && c.Ticket__r.Carrier__c != DLT_CaseConstants.CARRIER_PURPLE) ? false : 
                    ((c.Case__c != null && c.Case__r.Carrier__c != null && c.Case__r.Carrier__c != DLT_CaseConstants.CARRIER_PURPLE) ? false :
                        ((c.CreatedBy.Train_Service__c != null && c.CreatedBy.Train_Service__c != DLT_CaseConstants.CARRIER_PURPLE) ? false : true)));

        }
        DLT_CompensationTriggerHandler.isDisabled = true;
        update compensationsWithDefault;
        DLT_CompensationTriggerHandler.isDisabled = false;

    }
}