GearsetPOC/force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Travel</fullName>
            </value>
            <value>
                <fullName>At The Station</fullName>
            </value>
            <value>
                <fullName>Onboard</fullName>
            </value>
            <value>
                <fullName>Post Travel</fullName>
            </value>
            <value>
                <fullName>Webform case - please review</fullName>
            </value>
            <value>
                <fullName>Club Eurostar</fullName>
            </value>
            <value>
                <fullName>Phone Case - please complete</fullName>
            </value>
            <value>
                <fullName>System - please review</fullName>
            </value>
            <value>
                <fullName>Document request</fullName>
            </value>
            <value>
                <fullName>Subscriptions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Customer_Struggle__c.field-meta.xml
<CustomField>
    <fullName>Customer_Struggle__c</fullName>
    <label>Customer Struggle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Can&#39;t Get Seats Together</fullName>
            </value>
            <value>
                <fullName>Couldn&#39;t Find</fullName>
            </value>
            <value>
                <fullName>Couldn&#39;t Find The Right Meal</fullName>
            </value>
            <value>
                <fullName>Customer error</fullName>
            </value>
            <value>
                <fullName>Customer giving feedback</fullName>
            </value>
            <value>
                <fullName>Customer Room Booking</fullName>
            </value>
            <value>
                <fullName>Didn&#39;t Know This Was Online</fullName>
            </value>
            <value>
                <fullName>Didn&#39;t Receive A Confirmation</fullName>
            </value>
            <value>
                <fullName>Didn&#39;t understand</fullName>
            </value>
            <value>
                <fullName>Didn&#39;t Understand Compensation</fullName>
            </value>
            <value>
                <fullName>Didn&#39;t Understand The Seat Plan</fullName>
            </value>
            <value>
                <fullName>Don&#39;t Understand How To Do This Online</fullName>
            </value>
            <value>
                <fullName>Don&#39;t Understand Refund Options</fullName>
            </value>
            <value>
                <fullName>Don&#39;t Understand Terms &amp; Conditions</fullName>
            </value>
            <value>
                <fullName>Don&#39;t Understand The Price Or Fees</fullName>
            </value>
            <value>
                <fullName>Don&#39;t Want To Do This Online</fullName>
            </value>
            <value>
                <fullName>Don&#39;t Want To Use Website Or No Access To Website</fullName>
            </value>
            <value>
                <fullName>Eurostar Error</fullName>
            </value>
            <value>
                <fullName>Failed To Add Meal</fullName>
            </value>
            <value>
                <fullName>Form Of Payment Not Online</fullName>
            </value>
            <value>
                <fullName>Needed A Recap Or Reassurance</fullName>
            </value>
            <value>
                <fullName>Need More Information</fullName>
            </value>
            <value>
                <fullName>No self service option</fullName>
            </value>
            <value>
                <fullName>Not An Online Product</fullName>
            </value>
            <value>
                <fullName>Not An Online Product Or Not Refundable Online</fullName>
            </value>
            <value>
                <fullName>Outside Booking Horizon</fullName>
            </value>
            <value>
                <fullName>Overbooked Seat</fullName>
            </value>
            <value>
                <fullName>Phone Case - please complete</fullName>
            </value>
            <value>
                <fullName>Point Of Sale Prevents Self Service</fullName>
            </value>
            <value>
                <fullName>System - please review</fullName>
            </value>
            <value>
                <fullName>Webform case - please review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>Special Assistance</fullName>
            </value>
            <value>
                <fullName>Packages or Hotels</fullName>
            </value>
            <value>
                <fullName>Eurodespatch</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>No Customer</fullName>
            </value>
            <value>
                <fullName>Phone - please complete</fullName>
            </value>
            <value>
                <fullName>Social media - please review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Date_Queued__c.field-meta.xml
<CustomField>
    <fullName>Date_Queued__c</fullName>
    <description>Date and time when case was assigned to queue last time</description>
    <label>Date Queued</label>
    <type>DateTime</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Exclude_Delete__c.field-meta.xml
<CustomField>
    <fullName>Exclude_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exclude/Delete</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Initial_Reason_For_Contact__c.field-meta.xml
<CustomField>
    <fullName>Initial_Reason_For_Contact__c</fullName>
    <label>Initial Reason For Contact</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy or Book</fullName>
            </value>
            <value>
                <fullName>Change</fullName>
            </value>
            <value>
                <fullName>Cancel or Refund</fullName>
            </value>
            <value>
                <fullName>Info or Advice or Confirmation</fullName>
            </value>
            <value>
                <fullName>Disruption or Compensation</fullName>
            </value>
            <value>
                <fullName>Phone Case - please complete</fullName>
            </value>
            <value>
                <fullName>Package_Outbound_Calling</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Standalone hotel add on request</fullName>
            </value>
            <value>
                <fullName>Package add on request</fullName>
            </value>
            <value>
                <fullName>Disruption</fullName>
            </value>
            <value>
                <fullName>Package hotel exchange</fullName>
            </value>
            <value>
                <fullName>Standalone hotel exchange</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Standalone hotel refund</fullName>
            </value>
            <value>
                <fullName>Customer Room Booking</fullName>
            </value>
            <value>
                <fullName>Social media - please review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <label>Topic</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accessibility</fullName>
            </value>
            <value>
                <fullName>Additional Charges</fullName>
            </value>
            <value>
                <fullName>Amenities</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>Assistance dog</fullName>
            </value>
            <value>
                <fullName>Bikes</fullName>
            </value>
            <value>
                <fullName>Booking Confirmation</fullName>
            </value>
            <value>
                <fullName>Brexit</fullName>
            </value>
            <value>
                <fullName>Catering</fullName>
            </value>
            <value>
                <fullName>Check-In Or Security</fullName>
            </value>
            <value>
                <fullName>Children &amp; Infants</fullName>
            </value>
            <value>
                <fullName>Club Eurostar</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Connections</fullName>
            </value>
            <value>
                <fullName>Credit Notes</fullName>
            </value>
            <value>
                <fullName>Destination Info</fullName>
            </value>
            <value>
                <fullName>Disruption</fullName>
            </value>
            <value>
                <fullName>Documents Or Paperwork</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>General feedback</fullName>
            </value>
            <value>
                <fullName>Health and Safety</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>Invoices</fullName>
            </value>
            <value>
                <fullName>Lounge</fullName>
            </value>
            <value>
                <fullName>Luggage</fullName>
            </value>
            <value>
                <fullName>Medical Supplies</fullName>
            </value>
            <value>
                <fullName>Musical Instruments</fullName>
            </value>
            <value>
                <fullName>Names</fullName>
            </value>
            <value>
                <fullName>Onboard experience</fullName>
            </value>
            <value>
                <fullName>Phone Case - please complete</fullName>
            </value>
            <value>
                <fullName>Webform case - please review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/What_Is_The_Question__c.field-meta.xml
<CustomField>
    <fullName>What_Is_The_Question__c</fullName>
    <label>What Is The Question?</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Topic__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aachen</fullName>
            </value>
            <value>
                <fullName>Aime-La-Plagne</fullName>
            </value>
            <value>
                <fullName>Aix-en-Provence</fullName>
            </value>
            <value>
                <fullName>Albertville</fullName>
            </value>
            <value>
                <fullName>Amsterdam Centraal</fullName>
            </value>
            <value>
                <fullName>Antwerp</fullName>
            </value>
            <value>
                <fullName>Ashford International</fullName>
            </value>
            <value>
                <fullName>Avignon</fullName>
            </value>
            <value>
                <fullName>Bourg-Saint-Maurice</fullName>
            </value>
            <value>
                <fullName>Brussels Midi/Zuid</fullName>
            </value>
            <value>
                <fullName>Calas-Frethun</fullName>
            </value>
            <value>
                <fullName>Chambery</fullName>
            </value>
            <value>
                <fullName>Cologne</fullName>
            </value>
            <value>
                <fullName>Disneyland Paris</fullName>
            </value>
            <value>
                <fullName>Dortmund</fullName>
            </value>
            <value>
                <fullName>Duisburg</fullName>
            </value>
            <value>
                <fullName>Düsseldorf</fullName>
            </value>
            <value>
                <fullName>Düsseldorf Airport</fullName>
            </value>
            <value>
                <fullName>Ebbsfleet International</fullName>
            </value>
            <value>
                <fullName>Essen</fullName>
            </value>
            <value>
                <fullName>Feedback submitted</fullName>
            </value>
            <value>
                <fullName>How Do I Get It?</fullName>
            </value>
            <value>
                <fullName>How do I use it?</fullName>
            </value>
            <value>
                <fullName>I&#39;ve lost something</fullName>
            </value>
            <value>
                <fullName>I have lost something?</fullName>
            </value>
            <value>
                <fullName>I need to reset my password</fullName>
            </value>
            <value>
                <fullName>Is There A Cost?</fullName>
            </value>
            <value>
                <fullName>Landry</fullName>
            </value>
            <value>
                <fullName>Liege</fullName>
            </value>
            <value>
                <fullName>Lille Europe</fullName>
            </value>
            <value>
                <fullName>Phone Case - please complete</fullName>
            </value>
            <value>
                <fullName>Webform case - please review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/classes/PhoneCaseTriggerHandler.cls
public with sharing class PhoneCaseTriggerHandler {
    public static final Id CUSTOMER_CARE_QUEUE_ID;
    public static final Id CUSTOMER_CARE_FRENCH_QUEUE_ID;
    public static final Id CUSTOMER_CARE_DUTCH_QUEUE_ID;
    public static final String CUSTOMER_CARE_QUEUE_NAME        = 'ECC_Customer_Care';
    public static final String CUSTOMER_CARE_FRENCH_QUEUE_NAME = 'Customer_Care_French';
    public static final String CUSTOMER_CARE_DUTCH_QUEUE_NAME  = 'Customer_Care_Dutch';

    static {
        List<Group> queues = [SELECT Id, DeveloperName
                              FROM Group
                              WHERE (DeveloperName = :CUSTOMER_CARE_QUEUE_NAME OR
                                     DeveloperName = :CUSTOMER_CARE_FRENCH_QUEUE_NAME OR
                                     DeveloperName = :CUSTOMER_CARE_DUTCH_QUEUE_NAME) AND
                                     Type='Queue'];

        for (Group queue : queues) {
            if (queue.DeveloperName.equals(CUSTOMER_CARE_QUEUE_NAME)) CUSTOMER_CARE_QUEUE_ID = queue.Id;
            if (queue.DeveloperName.equals(CUSTOMER_CARE_FRENCH_QUEUE_NAME)) CUSTOMER_CARE_FRENCH_QUEUE_ID = queue.Id;
            if (queue.DeveloperName.equals(CUSTOMER_CARE_DUTCH_QUEUE_NAME)) CUSTOMER_CARE_DUTCH_QUEUE_ID = queue.Id;
        }
    }

    public static void afterUpdate(List<Case> newCases, Map<Id, Case> oldCases) {

        String errorText = 'Please review and complete to continue.';
        for(Case newCase: newCases){
            System.debug('Owner' + newCase.OwnerId);
            System.debug(newCase.Exclude_Delete__c == oldCases.get(newCase.Id).Exclude_Delete__c);
            System.debug(newCase.Origin == 'Phone' || newCase.Origin == 'Web');
            System.debug(!(newCase.OwnerId == CUSTOMER_CARE_QUEUE_ID || newCase.OwnerId == CUSTOMER_CARE_FRENCH_QUEUE_ID || newCase.OwnerId == CUSTOMER_CARE_DUTCH_QUEUE_ID) && newCase.Origin != 'Web');
            System.debug(newCase.Subject == oldCases.get(newCase.Id).Subject );
            System.debug( newCase.Date_Queued__c == oldCases.get(newCase.Id).Date_Queued__c);
            if(newCase.Exclude_Delete__c == oldCases.get(newCase.Id).Exclude_Delete__c 
                && (newCase.Origin == 'Phone') 
                && !((newCase.OwnerId == CUSTOMER_CARE_QUEUE_ID || newCase.OwnerId == CUSTOMER_CARE_FRENCH_QUEUE_ID || newCase.OwnerId == CUSTOMER_CARE_DUTCH_QUEUE_ID) && newCase.Origin != 'Web') 
                && newCase.Subject == oldCases.get(newCase.Id).Subject 
                && newCase.Subject != 'Duplicate'
                && newCase.Date_Queued__c == oldCases.get(newCase.Id).Date_Queued__c
                && newCase.Status == 'Closed') {
                    if(newCase.What_Is_The_Question__c == 'Phone Case - please complete' || newCase.What_Is_The_Question__c == 'Webform case - please review') {
                        newCase.addError('What_Is_The_Question__c', errorText);  
                    }
                    if(newCase.Topic__c == 'Phone Case - please complete' || newCase.Topic__c == 'Webform case - please review') {
                        newCase.addError('Topic__c', errorText);  
                    }
                    if(newCase.Category__c == 'Phone Case - please complete' || newCase.Category__c == 'Webform case - please review') {
                        newCase.addError('Category__c', errorText);  
                    }	
                    if(newCase.Customer_Struggle__c == 'Phone Case - please complete' || newCase.Customer_Struggle__c == 'Webform case - please review') {
                        newCase.addError('Customer_Struggle__c', errorText);  
                    }
                    if(newCase.Customer_Type__c == 'Phone - please complete' || newCase.Customer_Type__c == 'Webform case - please review') {
                        newCase.addError('Customer_Type__c', errorText);  
                    }
                    if(newCase.Initial_Reason_For_Contact__c == 'Phone Case - please complete' || newCase.Initial_Reason_For_Contact__c == 'Webform case - please review') {
                        newCase.addError('Initial_Reason_For_Contact__c', errorText);       
                    }
                    if(newCase.Journey_Type_Product__c == 'Webform case - please review') {
                        newCase.addError('Journey_Type_Product__c', errorText);       
                    }
            }
        }
    }
}