GearsetPOC/force-app/main/default/objects/Case/fields/Class_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Class_of_Service__c</fullName>
    <label>Class of Service</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard Premier</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Business Premier</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>Comfort</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <formula>IF(
   CONTAINS(TEXT(Origin), &quot;Email&quot;), Image(&quot;/servlet/servlet.FileDownload?file=015b0000000KFiH&quot;,&quot;Email&quot;,25,25),
   Case(Origin,
      &quot;Mobile Feedback&quot;,Image(&quot;/servlet/servlet.FileDownload?file=015b0000000KFiH&quot;,&quot;Email&quot;   ,25,25),
      &quot;Web&quot;         ,Image(&quot;/servlet/servlet.FileDownload?file=015b0000000KFi2&quot;,&quot;Web&quot;     ,25,25),
      &quot;Disruption Web&quot;, Image(&quot;/servlet/servlet.FileDownload?file=015b0000001YPDx&quot;,&quot;Disruption Web&quot;     ,25,25),
      &quot;Letter&quot;      ,Image(&quot;/servlet/servlet.FileDownload?file=015b0000000KFiv&quot;,&quot;Letter&quot;  ,25,25),
      &quot;Phone&quot;       ,Image(&quot;/servlet/servlet.FileDownload?file=015b0000000KFhn&quot;,&quot;Phone&quot;   ,25,25),
      &quot;Facebook&quot;    ,Image(&quot;/servlet/servlet.FileDownload?file=015b0000000KFgB&quot;,&quot;Facebook&quot;,25,25),
      &quot;Twitter&quot;     ,Image(&quot;/servlet/servlet.FileDownload?file=015b0000000KHkq&quot;,&quot;Twitter&quot; ,25,25),
      &quot;Qubit&quot;       ,Image(&quot;/servlet/servlet.FileDownload?file=015b0000000KHkW&quot;,&quot;Qubit&quot;   ,25,25),
      &quot;Chat&quot;        ,Image(&quot;/servlet/servlet.FileDownload?file=015b00000024vKQ&quot;,&quot;Chat&quot;   ,25,25),
      &quot;Commercial Support&quot;,Image(&quot;/servlet/servlet.FileDownload?file=015b0000000KFiH&quot;,&quot;Email&quot;,25,25),
      null
   )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Origin</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <label>PNR</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Train__c.field-meta.xml
<CustomField>
    <fullName>Train__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Train at the origin of the case</description>
    <inlineHelpText>Train at the origin of the case</inlineHelpText>
    <label>Disruption Train</label>
    <referenceTo>Train__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Stations__c/Stations__c.object-meta.xml
<CustomObject>
    <description>Eurostar&#39;s stations</description>
    <label>Station</label>
    <nameField>
        <label>Stations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Stations__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checked if the Stations is used by Eurostar
Unchecked if not</description>
    <inlineHelpText>Checked if the Stations is used by Eurostar
Unchecked if not</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Stations__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GBR</fullName>
                <label>United Kingdom</label>
            </value>
            <value>
                <fullName>FRA</fullName>
                <label>France</label>
            </value>
            <value>
                <fullName>BEL</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>DEU</fullName>
                <label>Germany</label>
            </value>
            <value>
                <fullName>NLD</fullName>
                <label>Netherlands</label>
            </value>
            <value>
                <fullName>CHE</fullName>
                <label>Switzerland</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Stations__c/fields/Dutch_Station_Name__c.field-meta.xml
<CustomField>
    <fullName>Dutch_Station_Name__c</fullName>
    <description>Dutch translation of station name</description>
    <label>Dutch Station Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Stations__c/fields/nl_Station_Name__c.field-meta.xml
<CustomField>
    <fullName>nl_Station_Name__c</fullName>
    <description>Dutch translation of station name</description>
    <label>Dutch Station Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>TCN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Booker__c.field-meta.xml
<CustomField>
    <fullName>Booker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booker</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tickets (Booker)</relationshipLabel>
    <relationshipName>TicketList</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Booking_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Booking_DateTime__c</fullName>
    <description>Booking DateTime</description>
    <externalId>true</externalId>
    <label>Booking DateTime</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Booking_DateTime_Format__c.field-meta.xml
<CustomField>
    <fullName>Booking_DateTime_Format__c</fullName>
    <formula>DATETIMEVALUE
(
   MID(Booking_DateTime__c,7,4)+&quot;-&quot;+
   MID(Booking_DateTime__c,4,2)+&quot;-&quot;+
   MID(Booking_DateTime__c,1,2)+&quot; &quot;+
   MID(Booking_DateTime__c,12,8)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Booking DateTime (formatted)</label>
    <type>DateTime</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Class_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Class_of_Service__c</fullName>
    <label>Class of Service</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <color>#F3D904</color>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Standard Premier</fullName>
                <color>#339999</color>
                <label>Standard Premier</label>
            </value>
            <value>
                <fullName>Business Premier</fullName>
                <color>#2F5D85</color>
                <label>Business Premier</label>
            </value>
            <value>
                <fullName>Premium</fullName>
                <color>#FF0000</color>
                <label>Premium</label>
            </value>
            <value>
                <fullName>Comfort</fullName>
                <color>#FF9900</color>
                <label>Comfort</label>
            </value>
            <value>
                <fullName>Eurostar Premier</fullName>
            </value>
            <value>
                <fullName>Eurostar Plus</fullName>
            </value>
            <value>
                <fullName>Eurostar Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Connecting_Destination__c.field-meta.xml
<CustomField>
    <fullName>Connecting_Destination__c</fullName>
    <formula>IF(CreatedBy.FirstName = &quot;KAFKA&quot;,Non_Eurostar_Destination__c,IF(NOT(ISBLANK(Non_Eurostar_Destination__c)),Non_Eurostar_Destination__c,

IF(ABS_Any_Belgian_Station__c=true,&quot;ABS (Any Belgian Station)&quot;,

&quot;&quot;

)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Connecting Destination</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country</description>
    <label>Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Departure_Date_Time_Format__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date_Time_Format__c</fullName>
    <formula>DATETIMEVALUE(MID(Travel_DateTime__c,7,4)+&quot;-&quot;+MID(Travel_DateTime__c,4,2)+&quot;-&quot;+MID(Travel_DateTime__c,1,2)+&quot; &quot;+MID(Travel_DateTime__c,12,8))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Warning: the Time value might be not correct, as is depends on the departure timezones and the salesforce users timezones.</inlineHelpText>
    <label>Departure DateTime (formatted)</label>
    <type>DateTime</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <description>Destination Station</description>
    <label>Destination</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Non_Eurostar_Destination__c.field-meta.xml
<CustomField>
    <fullName>Non_Eurostar_Destination__c</fullName>
    <label>Journey Destination</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Non_Eurostar_Origin__c.field-meta.xml
<CustomField>
    <fullName>Non_Eurostar_Origin__c</fullName>
    <label>Journey Origin</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>Origin Station</description>
    <label>Origin</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/PAX_Type__c.field-meta.xml
<CustomField>
    <fullName>PAX_Type__c</fullName>
    <label>PAX Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/PAX_Type_Description__c.field-meta.xml
<CustomField>
    <fullName>PAX_Type_Description__c</fullName>
    <description>S3 product description</description>
    <label>PAX Type Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/PAX_Type_Filter__c.field-meta.xml
<CustomField>
    <fullName>PAX_Type_Filter__c</fullName>
    <label>PAX Type Filter</label>
    <type>TextArea</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <label>PNR</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Train__c.field-meta.xml
<CustomField>
    <fullName>Train__c</fullName>
    <label>Train</label>
    <referenceTo>Train__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/Train__c.object-meta.xml
<CustomObject>
    <label>Train</label>
    <nameField>
        <label>Train ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Departure_Date_Time_Format__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date_Time_Format__c</fullName>
    <description>Similar to that same field on the Ticket, issues with Timezones.</description>
    <formula>DATETIMEVALUE(MID(Name,8,19))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Departure DateTime (do not use)</label>
    <type>DateTime</type>
</CustomField>

GearsetPOC/force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

GearsetPOC/force-app/main/default/classes/cu_CaseUpdateHelper.cls
public without sharing class cu_CaseUpdateHelper {

    private static Set<string> cachedStationNames;

    // get ticket for Case by PNR filled
    public static List<Ticket__c> getTicketsByCase(List<string> listOfPNR){
        List<Ticket__c> listTickets = new list<Ticket__c>();
        if(!listOfPNR.isEmpty()){
            listTickets = [SELECT Id, Class_of_Service__c, PNR__c, PAX_Type__c, Train__c, Destination__c, Origin__c ,
                                    Booker__c 
                                FROM Ticket__c where PNR__c in :listOfPNR];
        }

        return listTickets;

    }

    //Destination__c, Origin__c, Booking_DateTime__c, Booking_DateTime_Format__c
    public static Map<string, List<Ticket__c>> getTicketsWithBookingByPNR(list<string> listOfPNR, Date caseDateCreation ){
        Map<string, List<Ticket__c>> mapTickets = new Map<string, List<Ticket__c>>();
        Map<String, Ticket__c> mostRecentTicketbyPnr = new Map<String, Ticket__c>();

        if(!listOfPNR.isEmpty()){
            List<Ticket__c> listTickets = [SELECT Id, Class_of_Service__c, PNR__c, PAX_Type__c, PAX_Type_Description__c, Train__c, 
                                Destination__c, Origin__c, Booking_DateTime_Format__c, Connecting_Destination__c,
                                Non_Eurostar_Origin__c, Non_Eurostar_Destination__c, PAX_Type_Filter__c, Booker__c, Departure_Date_Time_Format__c 
                                FROM Ticket__c where PNR__c in :listOfPNR
                                ];

            for (Ticket__c ticket : listTickets) {
                List<Ticket__c> tickets = new List<Ticket__c>();
                if (mapTickets.containsKey(ticket.PNR__c)){
                    tickets = mapTickets.get(ticket.PNR__c);
                }
                tickets.add(ticket);
                mapTickets.put(ticket.PNR__c, tickets);

                if (mostRecentTicketbyPnr.containsKey(ticket.PNR__c)) {
                    if (mostRecentTicketbyPnr.get(ticket.PNR__c).Departure_Date_Time_Format__c < ticket.Departure_Date_Time_Format__c) {
                        mostRecentTicketbyPnr.put(ticket.PNR__c,ticket);
                    }
                }else {
                    mostRecentTicketbyPnr.put(ticket.PNR__c,ticket);
                }
            }

            for (String pnr : mostRecentTicketbyPnr.keySet()) {
                Ticket__c mostRecentTicket = mostRecentTicketbyPnr.get(pnr);

                List<Ticket__c> filteredTickets = new List<Ticket__c>(); 
                filteredTickets.add(mostRecentTicket);

                for (Ticket__c ticketItem : mapTickets.get(pnr)) {
                    if (mostRecentTicket.Booker__c == ticketItem.Booker__c && mostRecentTicket.Booking_DateTime_Format__c == ticketItem.Booking_DateTime_Format__c) {
                        filteredTickets.add(ticketItem);
                    }
                }

                mapTickets.put(pnr, filteredTickets);
            }
        }

        return mapTickets;
    }

    public static Set<string> getStationNamesBelgiumAndDutch(){
        if (cachedStationNames != null) { return cachedStationNames; }

        cachedStationNames = new Set<string>();

        List<Stations__c> listOfStations = [
            SELECT Id, Name, Dutch_Station_Name__c, nl_Station_Name__c, Active__c, Country__c
            FROM Stations__c
            WHERE country__c in ('DEU', 'BEL')
        ];

        for (Stations__c station : listOfStations) {
            cachedStationNames.add(station.Name);

            if(string.isNotBlank(station.Dutch_Station_Name__c)) {
                cachedStationNames.add(station.Dutch_Station_Name__c);
            }

            if (string.isNotBlank(station.nl_Station_Name__c)) {
                cachedStationNames.add(station.nl_Station_Name__c);
            }

        }

        return cachedStationNames;
    }
}