GearsetPOC/force-app/main/default/objects/Case/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>Currency which the write off was processed in</description>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nothing Pending</fullName>
            </value>
            <value>
                <fullName>Customer Responded</fullName>
            </value>
            <value>
                <fullName>Case Comment Received</fullName>
            </value>
            <value>
                <fullName>Compensation pending</fullName>
            </value>
            <value>
                <fullName>Compensation rejected</fullName>
            </value>
            <value>
                <fullName>Compensation approved</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Advisor</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Application Support</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Train Manager</fullName>
            </value>
            <value>
                <fullName>On Board Services</fullName>
            </value>
            <value>
                <fullName>Board Member</fullName>
            </value>
            <value>
                <fullName>Control Room</fullName>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>GDPR</fullName>
            </value>
            <value>
                <fullName>Station Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Voucher_Amount__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Amount__c</fullName>
    <label>Voucher Amount</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <displayFormat>C{000000000}</displayFormat>
        <label>Compensation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Compensation</relationshipLabel>
    <relationshipName>Compensations</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Comp_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Comp_Approval_Status__c</fullName>
    <label>Comp Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Payment_Currency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Currency__c</fullName>
    <label>Payment Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/classes/DLT_CompensationService.cls
public inherited sharing class DLT_CompensationService {
    
    public static void updateRelatedCases(Set<Id> compensationIds) {
        Map<Id,Case> casesToUpdate = new Map<Id,Case>();

        for (Compensation__c comp : [
            SELECT Id, Case__c, Case__r.Status, Comp_Approval_Status__c, RecordType.Name, Payment_Currency__c, Payment_Amount__c, Case__r.Sub_Status__c
            FROM Compensation__c
            WHERE Id IN :compensationIds
                AND Case__c != null
                AND ((
                        Comp_Approval_Status__c = :DLT_CompensationConstants.COMP_APPROVAL_STATUS_AWAITING
                        AND Case__r.Sub_Status__c != :DLT_CaseConstants.SUB_STATUS_COMPENSATION_PENDING
                    )
                    OR (
                        Comp_Approval_Status__c = :DLT_CompensationConstants.COMP_APPROVAL_STATUS_APPROVED
                        AND Case__r.Sub_Status__c != :DLT_CaseConstants.SUB_STATUS_COMPENSATION_APPROVED
                    )
                    OR (
                        Comp_Approval_Status__c = :DLT_CompensationConstants.COMP_APPROVAL_STATUS_REJECTED
                        AND Case__r.Sub_Status__c != :DLT_CaseConstants.SUB_STATUS_COMPENSATION_REJECTED
                    )
                    OR RecordType.Name = :DLT_CompensationConstants.COMP_RECORDTYPE_VOUCHER
                )
        ]) {

            if ((
                comp.Comp_Approval_Status__c == DLT_CompensationConstants.COMP_APPROVAL_STATUS_AWAITING
                && comp.Case__r.Sub_Status__c != DLT_CaseConstants.SUB_STATUS_COMPENSATION_PENDING
            )
            || (
                comp.Comp_Approval_Status__c == DLT_CompensationConstants.COMP_APPROVAL_STATUS_APPROVED
                && comp.Case__r.Sub_Status__c != DLT_CaseConstants.SUB_STATUS_COMPENSATION_APPROVED
            )
            || (
                comp.Comp_Approval_Status__c == DLT_CompensationConstants.COMP_APPROVAL_STATUS_REJECTED
                && comp.Case__r.Sub_Status__c != DLT_CaseConstants.SUB_STATUS_COMPENSATION_REJECTED
            )) {
                casesToUpdate.put(
                    comp.Case__c,
                    new Case(
                        Id = comp.Case__c,
                        Status = DLT_CaseConstants.STATUS_AWAITING_INTERNAL,
                        Sub_Status__c = DLT_CaseConstants.APPROVAL_STATUS_TO_SUBSTATUS_MAP.get(comp.Comp_Approval_Status__c)
                    )
                );
            }

            if (comp.RecordType.Name == DLT_CompensationConstants.COMP_RECORDTYPE_VOUCHER) {
                if (casesToUpdate.containsKey(comp.Case__c)) {
                    casesToUpdate.get(comp.Case__c).Voucher_Amount__c = comp.Payment_Amount__c;
                    casesToUpdate.get(comp.Case__c).Currency__c = comp.Payment_Currency__c;
                } else {
                    casesToUpdate.put(
                        comp.Case__c,
                        new Case(
                            Id = comp.Case__c,
                            Voucher_Amount__c = comp.Payment_Amount__c,
                            Currency__c = comp.Payment_Currency__c
                        )
                    );
                }
            }

        }

        if (!casesToUpdate.isEmpty()) {
            DLT_CaseTriggerHandler.isDisabled = true;

            update casesToUpdate.values();

            DLT_CaseTriggerHandler.isDisabled = false;
        }
    }
}