GearsetPOC/force-app/main/default/objects/Case/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
            <value>
                <fullName>English (UK)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <label>TemplateId</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Contact/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <label>Preferred Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English (UK)</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/DLT_Settings__c/DLT_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Delta Settings</label>
</CustomObject>

GearsetPOC/force-app/main/default/objects/DLT_Settings__c/fields/Eurostar_Customer_Care_OrgWideEmail_Name__c.field-meta.xml
<CustomField>
    <fullName>Eurostar_Customer_Care_OrgWideEmail_Name__c</fullName>
    <defaultValue>&#39;Eurostar Customer Care&#39;</defaultValue>
    <label>Eurostar Customer Care OrgWideEmail Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/EmailServiceController.cls
public without sharing class EmailServiceController {

    public static List<OrgWideEmailAddress> fromAddress = new List<OrgWideEmailAddress>();

    public static Messaging.SingleEmailMessage createEmail(Case caseItem) {
        String templateDevName = 'cu_' + caseItem.TemplateId__c;
        if (caseItem.Preferred_Language__c == 'French') {
            templateDevName = templateDevName + '_fr';
        }
        if (caseItem.Preferred_Language__c == 'Dutch') {
            templateDevName = templateDevName + '_nl';
        }
        if (caseItem.Preferred_Language__c == 'German') {
            templateDevName = templateDevName + '_de';
        }
        List<EmailTemplate> template = [
            SELECT Id, HtmlValue, Body, Subject
            FROM EmailTemplate
            WHERE DeveloperName =: templateDevName
            LIMIT 1
        ];
        if (fromAddress.isEmpty()) {
            fromAddress = [
                SELECT Id, Address, DisplayName
                FROM OrgWideEmailAddress
                WHERE DisplayName = :DLT_Settings__c.getInstance().Eurostar_Customer_Care_OrgWideEmail_Name__c
                LIMIT 1
            ];
        }
        Messaging.SingleEmailMessage emailMessage = new Messaging.SingleEmailMessage();
        if (!template.isEmpty()) {
            String emailHTMLBody = template[0].HtmlValue;
            String plainTextBody = template[0].Body;
            String emailSubject = template[0].Subject;

            if (String.isNotBlank(caseItem.Customer_Name__c)) {
                emailHTMLBody = emailHTMLBody.replace('{!Contact.FirstName}', caseItem.Customer_Name__c);
            } else {
                emailHTMLBody = emailHTMLBody.replace('{!Contact.FirstName}', '');
            }
            emailHTMLBody = emailHTMLBody.replace('{CaseUrl}', HashController.createLink(caseItem.Id));
            emailHTMLBody = emailHTMLBody.replace('{!CaseUrl}', HashController.createLink(caseItem.Id));
            if(emailSubject != null) emailSubject = emailSubject.replace('{!Case.CaseNumber}', caseItem.CaseNumber);

            // if (!String.isNotBlank(plainTextBody)) {
            //     if (plainTextBody.containsIgnoreCase('{!Contact.FirstName}')) {
            //         plainTextBody = plainTextBody.replace('{!Contact.FirstName}', caseItem.Customer_Name__c);
            //     }
            //     if (plainTextBody.containsIgnoreCase('{CaseUrl}')) {
            //         plainTextBody = plainTextBody.replace('{CaseUrl}', HashController.createLink(caseItem.Id));
            //     }
            //     emailMessage.setPlainTextBody(plainTextBody);
            // }

            emailMessage.setHtmlBody(emailHTMLBody);
            emailMessage.setTargetObjectId(UserInfo.getUserId());
            emailMessage.setTreatTargetObjectAsRecipient(false);
            emailMessage.setSubject(emailSubject);
            if (Test.isRunningTest()) {
                fromAddress = new List<OrgWideEmailAddress>();
            }
            if (!fromAddress.isEmpty()) {
                emailMessage.setOrgWideEmailAddressId(fromAddress[0].Id);
            }
            emailMessage.setToAddresses(new String[] { caseItem.Email__c.trim() });
        } else {
            System.debug('Email error. No template with this developer name: ' + templateDevName);
        }

        return emailMessage;
    }

    public static void sendEmails(List<Messaging.SingleEmailMessage> emailMessages) {
        Messaging.reserveSingleEmailCapacity(emailMessages.size());
        try {
            Messaging.SendEmailResult[] resultMail = Messaging.sendEmail(emailMessages);
        } catch(System.EmailException ex) {
            System.debug('Case error: ' + ex.getMessage());
        }
    }

}