GearsetPOC/force-app/main/default/objects/Case_Report__c/Case_Report__c.object-meta.xml
<CustomObject>
    <description>For Case Management Reporting Snapshots</description>
    <label>Case Report</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Case Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Reports</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Case_Report__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Reports</relationshipLabel>
    <relationshipName>Case_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case_Report__c/fields/Case_Owner_Queue_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Owner_Queue_Name__c</fullName>
    <label>Case Owner Queue Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case_Report__c/fields/Case_Owner_User__c.field-meta.xml
<CustomField>
    <fullName>Case_Owner_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Owner User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Case_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case_Report__c/fields/Last_Modified_By__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Modified By</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Case Reports (Last Modified By)</relationshipLabel>
    <relationshipName>Case_ReportsLMB</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/DLT_CaseReportTriggerHandler.cls
public without sharing class DLT_CaseReportTriggerHandler {
    public static Boolean isDisabled = false;

    public static void run() {
        if (!System.Trigger.isExecuting || isDisabled) { return; }

        if (System.Trigger.isBefore) {
            if (System.Trigger.isInsert) {
                fillLookupFields(Trigger.new);
            }

            if (System.Trigger.isUpdate) {

            }
        }

        if (System.Trigger.isAfter) {
            if (System.Trigger.isInsert) {

            }

            if (System.Trigger.isUpdate) {

            }
        }
    }

    private static void fillLookupFields(List<Case_Report__c> newRecords){

        List<Id> caseIds = new List<Id>();

        for(Case_Report__c cr : newRecords){
            caseIds.add(cr.Case__c);
        }

        Map<Id,Case> relatedCases = new Map<Id,Case>([
            SELECT Id, OwnerId, Owner.Name, Owner.Type, LastModifiedById 
            FROM Case 
            WHERE Id 
            IN :caseIds
        ]);

        for(Case_Report__c caseReport : newRecords){

            if(!relatedCases.containsKey(caseReport.Case__c)) continue;

            Case currentCase = relatedCases.get(caseReport.Case__c);

            caseReport.Last_Modified_By__c = currentCase.LastModifiedById;

            if(currentCase.Owner.Type == 'Queue'){
                caseReport.Case_Owner_Queue_Name__c = currentCase.Owner.Name;
            }
            else{
                caseReport.Case_Owner_User__c = currentCase.OwnerId;
            }
        }
    }
}