GearsetPOC/force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Booking consisting of all tickets sharing a PNR. 
The name associated with the booking will be the lead passenger&#39;s one. 
Booking has been assigned as an External ID for Ticket.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Booking__c/fields/Booker__c.field-meta.xml
<CustomField>
    <fullName>Booker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booker</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Booking__c/fields/JAC_Travel_Ref__c.field-meta.xml
<CustomField>
    <fullName>JAC_Travel_Ref__c</fullName>
    <label>JAC Travel Ref</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <label>PNR</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Train__c.field-meta.xml
<CustomField>
    <fullName>Train__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Train at the origin of the case</description>
    <inlineHelpText>Train at the origin of the case</inlineHelpText>
    <label>Disruption Train</label>
    <referenceTo>Train__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>TCN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Booker__c.field-meta.xml
<CustomField>
    <fullName>Booker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booker</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tickets (Booker)</relationshipLabel>
    <relationshipName>TicketList</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Train Cancelled</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Checked_In__c.field-meta.xml
<CustomField>
    <fullName>Checked_In__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has passenger checked in?</description>
    <label>Checked In</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Departure_Date_Time_Format__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date_Time_Format__c</fullName>
    <formula>DATETIMEVALUE(MID(Travel_DateTime__c,7,4)+&quot;-&quot;+MID(Travel_DateTime__c,4,2)+&quot;-&quot;+MID(Travel_DateTime__c,1,2)+&quot; &quot;+MID(Travel_DateTime__c,12,8))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Warning: the Time value might be not correct, as is depends on the departure timezones and the salesforce users timezones.</inlineHelpText>
    <label>Departure DateTime (formatted)</label>
    <type>DateTime</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <label>PNR</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/PNR_Ticket__c.field-meta.xml
<CustomField>
    <fullName>PNR_Ticket__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Upsert external Id field for ticket loads</description>
    <externalId>true</externalId>
    <label>PNR-Ticket</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Retimed__c.field-meta.xml
<CustomField>
    <fullName>Retimed__c</fullName>
    <formula>IF( ISBLANK(Original_Travel_DateTime__c), false, IF(Travel_DateTime__c=Original_Travel_DateTime__c, false,true) )</formula>
    <label>Departure retimed?</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Train__c.field-meta.xml
<CustomField>
    <fullName>Train__c</fullName>
    <label>Train</label>
    <referenceTo>Train__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Train_Number__c.field-meta.xml
<CustomField>
    <fullName>Train_Number__c</fullName>
    <formula>MID(Train__r.Name,2,4)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Train Number</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Travel_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Travel_DateTime__c</fullName>
    <description>Travel DateTime</description>
    <externalId>true</externalId>
    <label>Departure DateTime</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/Train__c.object-meta.xml
<CustomObject>
    <label>Train</label>
    <nameField>
        <label>Train ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Train was cancelled</description>
    <label>Cancelled</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Delay_in_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Delay_in_Minutes__c</fullName>
    <description>The train delay in minutes</description>
    <label>Delay (mins)</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Departure_Date_Time_Format__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date_Time_Format__c</fullName>
    <description>Similar to that same field on the Ticket, issues with Timezones.</description>
    <formula>DATETIMEVALUE(MID(Name,8,19))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Departure DateTime (do not use)</label>
    <type>DateTime</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Train_Number__c.field-meta.xml
<CustomField>
    <fullName>Train_Number__c</fullName>
    <description>ID number of the train</description>
    <inlineHelpText>ID number of the train</inlineHelpText>
    <label>Train Number</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/S3PassengerAPIService.cls
public without sharing class S3PassengerAPIService {

    public static final String HOTEL_ONLY = 'HOTEL_ONLY';
    public static final String TRAIN_ONLY = 'TRAIN_ONLY';
    public static final String TRAIN_AND_HOTEL = 'TRAIN_AND_HOTEL';

    public static final String NO_REFUND = 'NO_REFUND';
    public static final String REFUND_TO_VOUCHER = 'REFUND_TO_VOUCHER';
    public static final String FULL_REFUND = 'FULL_REFUND';

    public static List<Object> aops;
    public static Map<String, Map<String, Object>> aopsById = new Map<String, Map<String, Object>>();

    private static String getAccessToken() {
        String token = '';
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('https://api.eurostar-uat-acc.cloud.sqills.com/oauth/v2/token');
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json');

        request.setBody('{' +
            '"grant_type": "https://com.sqills.s3.oauth.agent",' +
            '"username": "sf.contactus",' +
            '"password": "ConTACTuS@2022",' +
            '"client_id": "4lsgn8x9ozr939ow3422mb0qubk789cj31wzk93227xiuyga99"' +
        '}');
        HttpResponse response = http.send(request);

        if (response.getStatusCode() == 200) {
            Map<String, Object> results = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
            token = (String) results.get('access_token');
        } else {
            System.debug('The status code returned was not expected: ' + response.getStatusCode() + ' ' + response.getStatus());
            System.debug(response.getBody());
        }
        return token;
    }

    public static HttpResponse getAOP() {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('https://api.eurostar-uat-acc.cloud.sqills.com/api/v3/fare/management/aftersales-override-profiles' + '?page_size=100');
        request.setMethod('GET');

        String token = getAccessToken();
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('Authorization', 'Bearer ' + token);
        HttpResponse response = http.send(request);

        if (response.getStatusCode() == 200) {
            Map<String, Object> results = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
            aops = (List<Object>) results.get('aftersales_override_profiles');
            if (String.isNotBlank((String) results.get('next_page'))) {
                getNextAOPs(token, (String) results.get('next_page'));
            }
            for (Object aop: aops) {
                Map<String, Object> aopWithFields = (Map<String, Object>) aop;
                aopsById.put((String) aopWithFields.get('id'), aopWithFields);
            }
        } else {
            System.debug('The status code returned was not expected: ' + response.getStatusCode() + ' ' + response.getStatus());
            System.debug(response.getBody());
        }
        return response;
    }

    private static void getNextAOPs(String token, String nextUrl) {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(nextUrl);
        request.setMethod('GET');

        request.setHeader('Content-Type', 'application/json');
        request.setHeader('Authorization', 'Bearer ' + token);
        HttpResponse response = http.send(request);

        if (response.getStatusCode() == 200) {
            Map<String, Object> results = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
            aops.addAll((List<Object>) results.get('aftersales_override_profiles'));
            if (String.isNotBlank((String) results.get('next_page')) && !Test.isRunningTest()) {
                getNextAOPs(token, (String) results.get('next_page'));
            }
        } else {
            System.debug('The status code returned was not expected: ' + response.getStatusCode() + ' ' + response.getStatus());
            System.debug(response.getBody());
        }
    }

    public static cu_Utils.PnrDetails getAOPByPNR(String pnr) {
        cu_Utils.PnrDetails pnrItem = new cu_Utils.PnrDetails(pnr, false, '', false, false, false, false, false, '', '', false, false);
        if (String.isBlank(pnr)) {
            pnrItem.error = 'cu_ErrorPNR';
            return pnrItem;
        }
        List<Booking__c> booking = [
            SELECT Id, Booker__c, PNR__c
            FROM Booking__c
            WHERE PNR__c =: pnrItem.pnr.trim()
                OR JAC_Travel_Ref__c =: pnrItem.pnr.trim()
        ];
        List<Ticket__c> ticket = [
            SELECT Id, PNR__c, PNR_Ticket__c, Booker__c, Retimed__c, Train__r.Name,
                Departure_Date_Time_Format__c, Train_Number__c, Travel_DateTime__c,
                Train__r.Delay_in_Minutes__c, Checked_In__c, Cancelled__c
            FROM Ticket__c
            WHERE PNR__c =: pnrItem.pnr.trim()
            ORDER BY CreatedDate DESC
        ];

        Map<String, Object> aop = new Map<String, Object>();
        if (!ticket.isEmpty()) {
            getAOP();
            for (Ticket__c ticketItem : ticket) {
                if (!aop.containsKey('reason')) {
                    for (Map<String, Object> aopWithFields : aopsById.values()) {
                        String serviceNames = '';
                        List<Object> aopWithFieldsList = new List<Object>();
                        if (aopWithFields.containsKey('services')) {
                            aopWithFieldsList = (List<Object>) aopWithFields.get('services');
                        }
                        if (!aopWithFieldsList.isEmpty()) {
                            String startDate = (String) aopWithFields.get('start_date');
                            if (startDate.equalsIgnoreCase(ticketItem.Train__r.Name.substringBetween(' '))) {
                                for (Object service : aopWithFieldsList) {
                                    Map<String, Object> serviceItem = (Map<String, Object>) service;
                                    for (Object serviceName : serviceItem.values()) {
                                        serviceNames = serviceNames + ' ' + (String) serviceName;
                                    }
                                }
                                if (serviceNames.containsIgnoreCase(ticketItem.Train_Number__c)) {
                                    aop = aopWithFields;
                                    break;
                                }
                            }
                        }
                    }
                }
            }
        }

        if (booking.isEmpty() && ticket.isEmpty()) {
            pnrItem.error = 'cu_ErrorPNR';
            return pnrItem;
        }

        List<Case> openCases = CaseService.getExistingCasesByPNR(pnr);
        if (!openCases.isEmpty()) {
            pnrItem.error = 'cu_ErrorCaseExists';
        }

        // only train tickets have AOP
        if (!booking.isEmpty() && ticket.isEmpty()) {
            pnrItem.bookingType = HOTEL_ONLY;
        }
        if (booking.isEmpty() && !ticket.isEmpty()) {
            pnrItem.bookingType = TRAIN_ONLY;
        }
        if (!booking.isEmpty() && !ticket.isEmpty()) {
            pnrItem.bookingType = TRAIN_AND_HOTEL;
        }
        if (aop != null) {
            if (aop.containsKey('reason')) {
                pnrItem.isDisrupted = true;
                String reason = (String) aop.get('reason');
                if (reason.containsIgnoreCase('FREE')) {
                    pnrItem.cancelOption = NO_REFUND;
                }
                if (reason.containsIgnoreCase('VOUCHER')) {
                    pnrItem.cancelOption = REFUND_TO_VOUCHER;
                    pnrItem.isRefundable = true;
                }
                if (reason.containsIgnoreCase('PRR')) {
                    pnrItem.cancelOption = FULL_REFUND;
                    pnrItem.isRefundable = true;
                }
                if (reason.containsIgnoreCase('EXCHANGE')) {
                    pnrItem.isExchangable = true;
                }
            }

            if (aop.containsKey('description')) {
                pnrItem.isDisrupted = true;
                String description = (String) aop.get('description');
                if (description.containsIgnoreCase('FEE') || description.containsIgnoreCase('FFE') || description.containsIgnoreCase('FREE')) {
                    pnrItem.isFree = true;
                }
            }

            Boolean isDelayed = false;
            if (!aop.containsKey('description') && !aop.containsKey('reason')) {
                if (!ticket.isEmpty()) {
                    for (Ticket__c ticketItem : ticket) {
                        if (ticketItem.Cancelled__c) {
                            pnrItem.isCancelled = true;
                        }
                        if ((ticketItem.Train__r.Delay_in_Minutes__c > 60) && !isDelayed) {
                            pnrItem.isDelayed = true;
                            pnrItem.isDisrupted = true;
                            isDelayed = true;
                        }
                    }
                }
            }
        }
        return pnrItem;
    }
}