GearsetPOC/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Invoice of a Subscription</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Invoice__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <description>Format = YYYY0XXXX (YYYY = year, XXXX = number 1 to 9999). Generated upon confirmation of the Invoice.</description>
    <label>Invoice Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>&#39;&#39;Pro Forma&#39; sent to the client for payment via Bank Transfer. &#39;Confirmed&#39; once the payment is received and validated.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pro Forma</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Invoice__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Subscription which the Invoice has been issued for</description>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Invoice__c/fields/Subscription_VAT_Number__c.field-meta.xml
<CustomField>
    <fullName>Subscription_VAT_Number__c</fullName>
    <label>VAT Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Invoice__c/fields/Total_Amount_excl_VAT__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_excl_VAT__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Amount of the related Subscription, excluding taxes</description>
    <label>Total Amount (excl VAT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Invoice__c/fields/Total_Amount_incl_VAT__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_incl_VAT__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Amount to be paid for the related Subscription</description>
    <label>Total Amount (incl VAT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Invoice__c/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total VAT amount applied to the Subscription which the Invoice is made for</description>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Invoice__c/fields/VAT_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number__c</fullName>
    <description>VAT Number of the Account which the Invoice is issued to (when relevant).</description>
    <formula>Subscription__r.VAT_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VAT Number</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>Thalys The Pass Subscriptions</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Subscription__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subscription_Status</valueSetName>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Subscription__c/fields/TECH_VAT__c.field-meta.xml
<CustomField>
    <fullName>TECH_VAT__c</fullName>
    <formula>IF(
	OR(
		VAT_Country_Code__c = &#39;BE&#39; &amp;&amp; Exempt_from_VAT__c,
		TECH_isIntraCommunautaire__c,
VAT_Country_Code__c != &#39;BE&#39; &amp;&amp; VAT_Number__c != &#39;N/A&#39;
	),
	0,
	(0.21/1.21) * TECH_Total_Amount_Factor__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Subscription__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <description>Total Amount to be paid, based on the VAT policy, the Subscription Type Amount and the related Promo.</description>
    <formula>IF ( (VAT_Country_Code__c = &quot;BE&quot;),
(TECH_Total_Amount_Factor__c / TECH_VAT_Applied_Factor__c),

IF (TECH_isIntraCommunautaire__c = TRUE || VAT_Number__c &lt;&gt; &quot;N/A&quot;,
TECH_Total_Amount_Factor__c,

TECH_Total_Amount_Factor__c / TECH_VAT_Applied_Factor__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount (VAT Incl)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Subscription__c/fields/Total_Amount_VAT_excl__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_VAT_excl__c</fullName>
    <formula>IF( VAT_Country_Code__c = &quot;BE&quot;, TECH_Total_Amount_Factor__c/1.21,

IF( TECH_isIntraCommunautaire__c = TRUE || VAT_Number__c &lt;&gt; &quot;N/A&quot;, 

TECH_Total_Amount_Factor__c,

TECH_Total_Amount_Factor__c/1.21))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount (VAT excl)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Subscription__c/fields/VAT_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Number__c</fullName>
    <label>VAT Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/globalValueSets/Subscription_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Expired</fullName>
    </customValue>
    <customValue>
        <fullName>New</fullName>
    </customValue>
    <masterLabel>Subscription Status</masterLabel>
</GlobalValueSet>

GearsetPOC/force-app/main/default/classes/DLT_InvoiceTriggerHandler.cls
public without sharing class DLT_InvoiceTriggerHandler {
    public static Boolean isDisabled = false;

    public static void run() {
        if (!System.Trigger.isExecuting || isDisabled) { return; }

        List<Invoice__c> filteredInvoices;
        if(!System.Trigger.isDelete){
            filteredInvoices = filterRecords((List<Invoice__c>) System.Trigger.new);
        }

        if (System.Trigger.isBefore) {
            if (System.Trigger.isInsert) {
                setSubscriptionDependentFields(filteredInvoices);
                assignInvoiceNumber(filteredInvoices);
            }

            if (System.Trigger.isUpdate) {
                setSubscriptionDependentFields(filteredInvoices, (Map<Id, Invoice__c>) System.Trigger.oldMap);
                assignInvoiceNumber(filteredInvoices);
            }
        }

        if (System.Trigger.isAfter) {
            if (System.Trigger.isInsert) {
            }

            if (System.Trigger.isUpdate) {

            }
        }
    }

    private static void assignInvoiceNumber(List<Invoice__c> invoices){

        String numberFormat = System.Today().Year() + DLT_InvoiceConstants.NUMBER_PREFIX;
        String numberFormatSearch = '%' + numberFormat + '%';

        List<Invoice__c> existingInvoices = [
            SELECT Invoice_Number__c 
            FROM Invoice__c 
            WHERE Invoice_Number__c  != null 
                AND Invoice_Number__c LIKE :numberFormatSearch
            ORDER BY Invoice_Number__c DESC 
            LIMIT 1];
            
        Integer biggestNumber = existingInvoices.size() > 0 ?
            Integer.valueOf(existingInvoices[0].Invoice_Number__c.right(4)) :
            0;

        for(Invoice__c invoice : invoices){

            if(!String.isBlank(invoice.Invoice_Number__c) || invoice.Status__c != DLT_InvoiceConstants.STATUS_CONFIRMED) continue;

            biggestNumber++;    
            String currentNumber = ('000' + String.valueOf(biggestNumber)).right(4);

            invoice.Invoice_Number__c = numberFormat + currentNumber;
    
        }
    }

    private static void setSubscriptionDependentFields(List<Invoice__c> invoices){

        Map<Id, Subscription__c> subscriptionMap = getSubscriptionMap(invoices);

        for(Invoice__c invoice : invoices){
            if(invoice.Subscription__c == null) continue;

            fillSubscriptionDependentFields(invoice, subscriptionMap);
        }
    }

    private static void setSubscriptionDependentFields(List<Invoice__c> invoices, Map<Id, Invoice__c> invoiceOldMap){

        Map<Id, Subscription__c> subscriptionMap = getSubscriptionMap(invoices);

        for(Invoice__c invoice : invoices){
            if(invoice.Subscription__c == null || invoiceOldMap.get(invoice.Id).Subscription__c == invoice.Subscription__c) continue;

            fillSubscriptionDependentFields(invoice, subscriptionMap);        
        }
    }

    private static Map<Id, Subscription__c> getSubscriptionMap(List<Invoice__c> invoices){

        List<Id> relatedSubscriptionIds = new List<Id>();

        for(Invoice__c invoice : invoices){
            if(invoice.Subscription__c == null) continue;

            relatedSubscriptionIds.add(invoice.Subscription__c);
        }

        Map<Id, Subscription__c> subscriptionMap = new Map<Id, Subscription__c>([
            SELECT Id, Total_Amount_VAT_excl__c, TECH_VAT__c, Total_Amount__c, VAT_Number__c 
            FROM Subscription__c 
            WHERE Id IN :relatedSubscriptionIds]);

        return subscriptionMap;
    }

    private static void fillSubscriptionDependentFields(Invoice__c invoice, Map<Id, Subscription__c> subscriptionMap){

        invoice.Total_Amount_excl_VAT__c = subscriptionMap.get(invoice.Subscription__c).Total_Amount_VAT_excl__c;
        invoice.VAT__c = subscriptionMap.get(invoice.Subscription__c).TECH_VAT__c;
        invoice.Total_Amount_incl_VAT__c = subscriptionMap.get(invoice.Subscription__c).Total_Amount__c;
        invoice.Subscription_VAT_Number__c = subscriptionMap.get(invoice.Subscription__c).VAT_Number__c;

    }

    private static List<Invoice__c> filterRecords(List<Invoice__c> invoices){

        if(DLT_Constants.IS_LAMBDA_USER) return invoices;

        List<Invoice__c> filteredInvoices = new List<Invoice__c>();

        for(Invoice__c invoice : invoices){
            if(invoice.Invoice_Number__c == null){
                filteredInvoices.add(invoice);
            }
        }

        return filteredInvoices;
    }
}