GearsetPOC/force-app/main/default/objects/Compensation_Incident_Rules__c/Compensation_Incident_Rules__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Compensation Incident Rules</label>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Compensation_Incident_Rules__c/fields/Class_Of_Service__c.field-meta.xml
<CustomField>
    <fullName>Class_Of_Service__c</fullName>
    <label>Class Of Service</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation_Incident_Rules__c/fields/Compensation_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Compensation_Percentage__c</fullName>
    <label>Compensation Percentage</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation_Incident_Rules__c/fields/Delay_Minutes_From__c.field-meta.xml
<CustomField>
    <fullName>Delay_Minutes_From__c</fullName>
    <label>Delay Minutes From</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation_Incident_Rules__c/fields/Delay_Minutes_To__c.field-meta.xml
<CustomField>
    <fullName>Delay_Minutes_To__c</fullName>
    <label>Delay Minutes To</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation_Incident_Rules__c/fields/Incident_Type__c.field-meta.xml
<CustomField>
    <fullName>Incident_Type__c</fullName>
    <label>Incident Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation_Incident_Rules__c/fields/Travel_Date_From__c.field-meta.xml
<CustomField>
    <fullName>Travel_Date_From__c</fullName>
    <label>Travel Date From</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation_Incident_Rules__c/fields/Travel_Date_To__c.field-meta.xml
<CustomField>
    <fullName>Travel_Date_To__c</fullName>
    <label>Travel Date To</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Incidents__c/Incidents__c.object-meta.xml
<CustomObject>
    <label>Incident SF</label>
    <nameField>
        <displayFormat>IN{000000}</displayFormat>
        <label>Incidents Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incidents SF</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Incidents__c/fields/Compensation_Rule_Id__c.field-meta.xml
<CustomField>
    <fullName>Compensation_Rule_Id__c</fullName>
    <description>This is the Id for the compensation rule applicable for this incident. You should not modify this manually</description>
    <label>Compensation Rule Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Incidents__c/fields/Incident_Type__c.field-meta.xml
<CustomField>
    <fullName>Incident_Type__c</fullName>
    <label>Incident Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Air Conditioning</fullName>
            </value>
            <value>
                <fullName>Detrainment/Transbordement</fullName>
            </value>
            <value>
                <fullName>No Meal BP</fullName>
            </value>
            <value>
                <fullName>No Meal SP</fullName>
            </value>
            <value>
                <fullName>Not full Service BP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Incidents__c/fields/Train__c.field-meta.xml
<CustomField>
    <fullName>Train__c</fullName>
    <label>Train</label>
    <referenceTo>Train__c</referenceTo>
    <relationshipName>Incidents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/Train__c.object-meta.xml
<CustomObject>
    <label>Train</label>
    <nameField>
        <label>Train ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Delay_in_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Delay_in_Minutes__c</fullName>
    <description>The train delay in minutes</description>
    <label>Delay (mins)</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <formula>DATEVALUE(Departure_Date_Time_Format__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Departure Date (formatted)</label>
    <type>Date</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Incidents__c.field-meta.xml
<CustomField>
    <fullName>Incidents__c</fullName>
    <description>Count of the number of incidents related to the train.</description>
    <inlineHelpText>Count of the number of incidents related to the train.</inlineHelpText>
    <label>Incidents</label>
    <summaryForeignKey>Incidents__c.Train__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Train_Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Train_Departure_Date__c</fullName>
    <description>This give the date part od Departure Date Time files as a date data type.. Can be used as filter in queries</description>
    <formula>DATEVALUE( MID( Departure_Date_Time__c , 7,4)+&quot;-&quot;+MID( Departure_Date_Time__c , 4,2) + &quot;-&quot; + MID( Departure_Date_Time__c , 1,2)  )</formula>
    <label>Train Departure_Date</label>
    <type>Date</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Train_Number__c.field-meta.xml
<CustomField>
    <fullName>Train_Number__c</fullName>
    <description>ID number of the train</description>
    <inlineHelpText>ID number of the train</inlineHelpText>
    <label>Train Number</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/CompApp_IncidentCompUtils.cls
public without sharing class CompApp_IncidentCompUtils {	
    private static Map<Id, Compensation_Incident_Rules__c> incidentCompRules;
    
    public static Compensation_Incident_Rules__c getIncidentCompensationRule(Id ruleid){ 
        if (incidentCompRules==null){
            incidentCompRules = new Map<Id, Compensation_Incident_Rules__c>();
           
            For(Compensation_Incident_Rules__c rule:   [ SELECT class_of_service__c,   delay_minutes_from__c, delay_minutes_to__c, Compensation_Percentage__c 
                                                        from Compensation_Incident_Rules__c ]){
                                                            incidentCompRules.put(rule.Id, rule);
			}
            
        } 
        return incidentCompRules.get(ruleid);
         
    }

    public static void getIncidentCompensationRule(final List<Incidents__c> newObjects){
        List<ID> trainids = new List<ID>();
        Train__c train;
        Map<Id, Train__c> trainMap = new Map<Id, Train__c>();
        for(Incidents__c i: newObjects){
            trainids.add(i.Train__c);
        }
        for(Train__c t:[SELECT id, train_departure_date__c, departure_date__c, Delay_in_Minutes__c , train_number__c FROM Train__c where Id IN :trainids]){
            trainMap.put(t.id, t);
        }
        List<Compensation_Incident_Rules__c> ruleList = [SELECT name, travel_date_from__c, travel_date_to__c, class_of_service__c, 
                                                   					incident_type__c, delay_minutes_from__c, delay_minutes_to__c, Compensation_Percentage__c 
                                                   			FROM Compensation_Incident_Rules__c 
                                                            /*WHERE travel_date_from__c<=:train.train_departure_date__c 
                                                             		AND travel_date_to__c>=:train.train_departure_date__c
                                                         			AND incident_type__c= :i.Incident_Type__c*/
                                                 			ORDER BY travel_date_from__c, delay_minutes_from__c];
        for(Incidents__c i: newObjects){ 
            i.Compensation_Rule_Id__c = null;
            train = trainMap.get(i.train__c);
             if (ruleList!=null && ruleList.size()>0)
                 for(Compensation_Incident_Rules__c r:ruleList){
                     if(!(r.travel_date_from__c<=train.train_departure_date__c && 
                          r.travel_date_to__c>=train.train_departure_date__c   && 
                          r.incident_type__c== i.Incident_Type__c)){
                           //Rule not matching
                           //Move to next rule
                           continue;   
                          }
                         
                     System.debug('Found Rule:' + r.name+'Train :'+train.train_number__c+',Delay:'+train.Delay_in_Minutes__c);
                     if (r.delay_minutes_from__c!=null){
                         if (train.Delay_in_Minutes__c==null){
                             i.Compensation_Rule_Id__c = r.Id;
                             break;
                         }
                         else{
                             if (train.Delay_in_Minutes__c>=r.delay_minutes_from__c && train.Delay_in_Minutes__c<=r.delay_minutes_to__c ){
                                i.Compensation_Rule_Id__c = r.Id;
                                break;                             
                             }
                         }
                            
                     }
                     else{
                          i.Compensation_Rule_Id__c = r.Id;
                           break;
                     }
                 }  
        }
    }
    
}