GearsetPOC/force-app/main/default/objects/Preference__c/Preference__c.object-meta.xml
<CustomObject>
    <label>Preference</label>
    <nameField>
        <label>Preference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Preference__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Marketing Preferences</relationshipLabel>
    <relationshipName>Preferences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Preference__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <defaultValue>&quot;Email&quot;</defaultValue>
    <description>The preffered method to be contacted.</description>
    <label>Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Push</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Preference__c/fields/Consent__c.field-meta.xml
<CustomField>
    <fullName>Consent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the customer gave consent to be contacted about preference.</description>
    <label>Consent</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Preference__c/fields/DateTimeFrom__c.field-meta.xml
<CustomField>
    <fullName>DateTimeFrom__c</fullName>
    <description>The effective from date.</description>
    <label>DateTimeFrom</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Preference__c/fields/DateTimeTo__c.field-meta.xml
<CustomField>
    <fullName>DateTimeTo__c</fullName>
    <description>The effective to date.</description>
    <label>DateTimeTo</label>
    <type>DateTime</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Preference__c/fields/Entity_opt_in__c.field-meta.xml
<CustomField>
    <fullName>Entity_opt_in__c</fullName>
    <defaultValue>&quot;EIL&quot;</defaultValue>
    <label>Entity Opt In</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Eurostar_Limited</valueSetName>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Preference__c/fields/Preference__c.field-meta.xml
<CustomField>
    <fullName>Preference__c</fullName>
    <description>The type of marketing communication to receive.</description>
    <label>Preference</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trains_opt_in__c</fullName>
                <label>Trains</label>
            </value>
            <value>
                <fullName>Hotels_opt_in__c</fullName>
                <label>Hotels</label>
            </value>
            <value>
                <fullName>Trips_opt_in__c</fullName>
                <label>Trips</label>
            </value>
            <value>
                <fullName>Club_Eurostar_opt_in__c</fullName>
                <label>Club Eurostar</label>
            </value>
            <value>
                <fullName>EnrichmentAndProfiling_opt_in__c</fullName>
                <label>Enrichment And Profiling</label>
            </value>
            <value>
                <fullName>Preferred_Language__pc</fullName>
                <label>Language</label>
            </value>
            <value>
                <fullName>Unsubscribed_all_opt_in__c</fullName>
                <label>Unsubscribed all</label>
            </value>
            <value>
                <fullName>Business_travel_opt_in__c</fullName>
                <label>Business travel</label>
            </value>
            <value>
                <fullName>Newsletter THI</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
            <value>
                <fullName>Eurostar for Agents</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Preference__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>The reason of the signup.</description>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Newsletter</fullName>
            </value>
            <value>
                <fullName>Preference center update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Preference__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Where the consent was made from.</description>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>preference center</fullName>
            </value>
            <value>
                <fullName>agent</fullName>
            </value>
            <value>
                <fullName>Eurostar.com-Accounts</fullName>
            </value>
            <value>
                <fullName>Eurostar.com-Booking Path</fullName>
            </value>
            <value>
                <fullName>Eurostar.com-BPA In Path Dropouts</fullName>
            </value>
            <value>
                <fullName>Eurostar.com-Newsletter Signups</fullName>
            </value>
            <value>
                <fullName>Eurostar.com-Disney Competition</fullName>
            </value>
            <value>
                <fullName>Snap.Eurostar.com</fullName>
            </value>
            <value>
                <fullName>Vouchers.Eurostar.com</fullName>
            </value>
            <value>
                <fullName>Mobile App-Accounts</fullName>
            </value>
            <value>
                <fullName>Onboard Entertainment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/globalValueSets/Eurostar_Limited.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EIL</fullName>
    </customValue>
    <customValue>
        <fullName>EHL</fullName>
    </customValue>
    <customValue>
        <fullName>Thalys</fullName>
    </customValue>
    <masterLabel>Eurostar_Limited</masterLabel>
</GlobalValueSet>

GearsetPOC/force-app/main/default/classes/PreferenceConstants.cls
public without sharing class PreferenceConstants {
    public static final String OBJECT_NAME                  = Preference__c.getSObjectType().getDescribe().getName();

    public static final String FIELD_NAME_DATE_TIME_FROM    = String.valueOf(Preference__c.DateTimeFrom__c);
    public static final String FIELD_NAME_ENTITY_OPT_IN     = String.valueOf(Preference__c.Entity_opt_in__c);
    public static final String FIELD_NAME_DATE_TIME_TO      = String.valueOf(Preference__c.DateTimeTo__c);
    public static final String FIELD_NAME_PREFERENCE        = String.valueOf(Preference__c.Preference__c);
    public static final String FIELD_NAME_ACCOUNT           = String.valueOf(Preference__c.Account__c);
    public static final String FIELD_NAME_CONSENT           = String.valueOf(Preference__c.Consent__c);
    public static final String FIELD_NAME_CHANNEL           = String.valueOf(Preference__c.Channel__c);
    public static final String FIELD_NAME_REASON            = String.valueOf(Preference__c.Reason__c);
    public static final String FIELD_NAME_SOURCE            = String.valueOf(Preference__c.Source__c);
    public static final String FIELD_NAME_NAME              = String.valueOf(Preference__c.Name);
    public static final String FIELD_NAME_ID                = String.valueOf(Preference__c.Id);

    public static final String CUSTOM_SETTING_ERROR_EMAIL   = 'PreferenceProcessErrorEmail';

    public static final String REGEX_VALID_ID               = '[a-zA-Z0-9]{15}|[a-zA-Z0-9]{18}';

    public static final String DYNAMIC_QUERY_TEMPLATE       = 'SELECT {0} FROM {1} WHERE {2} <= {3}';

    public final static String FULL_DATETIME_FORMAT         = 'yyyy-MM-dd\'T\'HH:mm:ss\'Z\'';
    public final static String CUSTOM_FIELD_PREFIX          = '__c';
    public final static String JOIN_COMMA                   = ', ';
    public final static String SPACE                        = ' ';

    public final static Datetime EXPIRATION_DATE_TWO_YEAR_AGO = System.now().addYears(-2);

    public static final String[] QUERY_FIELDS = new String[] {
        PreferenceConstants.FIELD_NAME_ID
    };

    public static final String EXPIRED_PREFERENCES_DELETION_TITLE = 'Preferences Records History Maintenance';

    public static final String SCHEDULED_CRON_EVERY_DAY     = '0 0 0 1/1 * ? *';
    public static final String SCHEDULED_CRON_EVERY_2_H     = '0 0 0/2 1/1 * ? *';
    public static final String SCHEDULED_CRON_EVERY_15_M    = '0 15 * * * ? *';

    public static final Integer BATCH_CHUNK_SIZE = 200;

    // NOTE: {0} AsyncApexJob.TotalJobItems, {1} Preference_Constants.BATCH_CHUNK_SIZE, {2} AsyncApexJob.NumberOfErrors
    public static final String BATCH_PROCESSING_RESULT_EMAIL_TEMPLATE = '{0} batches of {1} records processed. {2} batches containing failures.';

    // NOTE: {0} sObject name, {1} Errors
    public static final String ERRORS_DURING_INSERT_TEMPLATE    = 'The errors occurs during the {0} records inserting.\n\nErrors:\n\n {1}';
    public static final String ERRORS_DURING_INSERT_SUBJECT     = 'The errors occurs during the records inserting';

    public static final String TEST_DEFAULT_EMAIL_ADDRESS       = 'slavadonnikov@gmail.com';
}