GearsetPOC/force-app/main/default/objects/Loyalty_Tier_History__c/Loyalty_Tier_History__c.object-meta.xml
<CustomObject>
    <label>Loyalty Tier History</label>
    <nameField>
        <displayFormat>LTH-{0000000000}</displayFormat>
        <label>Loyalty Tier History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty Tier History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Loyalty_Tier_History__c/fields/ChangeReasonType__c.field-meta.xml
<CustomField>
    <fullName>ChangeReasonType__c</fullName>
    <label>ChangeReasonType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Loyalty_Tier_History__c/fields/Loyalty_Program_Member__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Program_Member__c</fullName>
    <label>Loyalty Program Member</label>
    <referenceTo>LoyaltyProgramMember</referenceTo>
    <relationshipLabel>Loyalty Tier History</relationshipLabel>
    <relationshipName>Loyalty_Tier_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Loyalty_Tier_History__c/fields/New_Tier__c.field-meta.xml
<CustomField>
    <fullName>New_Tier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Tier</label>
    <referenceTo>LoyaltyTier</referenceTo>
    <relationshipLabel>Loyalty Tier History</relationshipLabel>
    <relationshipName>Loyalty_Tier_History</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Loyalty_Tier_History__c/fields/Old_Tier__c.field-meta.xml
<CustomField>
    <fullName>Old_Tier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Old Tier</label>
    <referenceTo>LoyaltyTier</referenceTo>
    <relationshipLabel>Loyalty Tier History (Old Tier)</relationshipLabel>
    <relationshipName>Loyalty_Tier_History1</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Loyalty_Tier_History__c/fields/TierChangeReason__c.field-meta.xml
<CustomField>
    <fullName>TierChangeReason__c</fullName>
    <label>Tier Change Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/LoyaltyMemberTier/fields/CurrentTierDateTime__c.field-meta.xml
<CustomField>
    <fullName>CurrentTierDateTime__c</fullName>
    <label>CurrentTierDateTime</label>
    <type>DateTime</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/LoyaltyMemberTier/fields/PreviousTierDateTime__c.field-meta.xml
<CustomField>
    <fullName>PreviousTierDateTime__c</fullName>
    <label>PreviousTierDateTime</label>
    <type>DateTime</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/OSF_LoyaltyMemberTier_TriggerHandler.cls
//Devops testing

/*********************************************************************************************************
Class Name      : OSF_LoyaltyMemberTier_TriggerHandler
Description     : Class to handle LoyaltyMemberTier trigger functionality
Developer       : Vasile Paraschiv
Date            : 
Version         : 1.0
*********************************************************************************************************
History
*********************************************************************************************************
Date            Developer           Version      Description
*********************************************************************************************************/
public with sharing class OSF_LoyaltyMemberTier_TriggerHandler {
    //set previous and current tier change dates
    public static void setTierDates(List<LoyaltyMemberTier> newList, Map<Id, LoyaltyMemberTier> oldMap) {
        if (!OSF_Utility.isActive('OSF_LoyaltyMemberTier_TriggerHandler', 'setTierDates') && !Test.isRunningTest()) {
            return;
        }
        try {
            for(LoyaltyMemberTier lmt : newList) {
                if(oldMap != null && (oldMap.containsKey(lmt.Id) && oldMap.get(lmt.Id).LoyaltyTierId != lmt.LoyaltyTierId)) {
                    if (lmt.PreviousTierDateTime__c == null) {
                        lmt.PreviousTierDateTime__c = lmt.CreatedDate;
                        lmt.CurrentTierDateTime__c = Datetime.now();
                    } else {
                        lmt.PreviousTierDateTime__c = lmt.CurrentTierDateTime__c;
                        lmt.CurrentTierDateTime__c = Datetime.now();
                    }
                }
            }
        } catch(Exception e) {
            System.debug(e.getMessage());
        }   
    }
    public static void createHistoryRecord(List<LoyaltyMemberTier> newList, Map<Id, LoyaltyMemberTier> oldMap) {
        if (!OSF_Utility.isActive('OSF_LoyaltyMemberTier_TriggerHandler', 'createHistoryRecord') && !Test.isRunningTest()) {
            return;
        }
        List<Loyalty_Tier_History__c> lstLMTHistory = new List<Loyalty_Tier_History__c>();
        try {
            for(LoyaltyMemberTier lmt : newList) {
             if ((oldMap != null && (oldMap.containsKey(lmt.Id) && oldMap.get(lmt.Id).LoyaltyTierId != lmt.LoyaltyTierId)) || oldMap == null || !oldMap.containsKey(lmt.Id) ) {
                Loyalty_Tier_History__c lmtHistory = new Loyalty_Tier_History__c();
                    lmtHistory.New_Tier__c = lmt.LoyaltyTierId;
                    if (oldMap != null && oldMap.containsKey(lmt.Id)) {
                        lmtHistory.Old_Tier__c = oldMap.get(lmt.Id).LoyaltyTierId;
                    }
                    lmtHistory.FromTierStartDate__c = lmt.PreviousTierDateTime__c == null ? Datetime.now() : lmt.PreviousTierDateTime__c;
                    lmtHistory.ToTierStartDate__c = lmt.CurrentTierDateTime__c == null ? Datetime.now() : lmt.CurrentTierDateTime__c;
                    lmtHistory.Loyalty_Program_Member__c = lmt.LoyaltyMemberId;
                    lmtHistory.TierChangeReason__c = lmt.ReasonForChange;
                    lmtHistory.ChangeReasonType__c = lmt.ChangeReasonType;
                    lstLMTHistory.add(lmtHistory);
               }
            }
            if (lstLMTHistory.size() > 0) {
                insert lstLMTHistory;
            }
        } catch(Exception e) {
            system.debug('ex'+e);
            OSF_ErrorLogHandler.logError(e, 'OSF_LoyaltyMemberTier_TriggerHandler');
        } finally {
            OSF_ErrorLogHandler.saveErrors();
        }
    }
}