GearsetPOC/force-app/main/default/objects/LiveChatTranscript/fields/SurveyTaken__c.field-meta.xml
<CustomField>
    <fullName>SurveyTaken__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Taken</label>
    <referenceTo>SurveyTaker__c</referenceTo>
    <relationshipLabel>Live Chat Transcripts</relationshipLabel>
    <relationshipName>Live_Chat_Transcripts</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/SurveyTaker__c/SurveyTaker__c.object-meta.xml
<CustomObject>
    <label>Survey Taken</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys Taken</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/SurveyTaker__c/fields/LiveChatKey__c.field-meta.xml
<CustomField>
    <fullName>LiveChatKey__c</fullName>
    <label>LiveChatKey</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/SurveyTakerTrigger_Handler.cls
public with sharing class SurveyTakerTrigger_Handler {
    public void updateTranscript(List<SurveyTaker__c> surveyTakers) {
        Map<String, SurveyTaker__c> surveyTakerByChatKey = new Map<String, SurveyTaker__c>();
        for (SurveyTaker__c surveyTaker : surveyTakers) {
            if (surveyTaker.LiveChatKey__c != null) {
                surveyTakerByChatKey.put(surveyTaker.LiveChatKey__c, surveyTaker);
            }
        }
        
        if (!surveyTakerByChatKey.isEmpty()) {
            List<LiveChatTranscript> transcripts = new List<LiveChatTranscript>([
                SELECT Id, ChatKey, SurveyTaken__c 
                FROM LiveChatTranscript
                WHERE ChatKey IN :surveyTakerByChatKey.keySet()
            ]);
            
            if (!transcripts.isEmpty()) {
                for (LiveChatTranscript transcript : transcripts) {
                    if (transcript.ChatKey != null) {
                        SurveyTaker__c st = surveyTakerByChatKey.get(transcript.ChatKey);
                        if (st != null && st.LiveChatKey__c != null && transcript.SurveyTaken__c == null) {
                            transcript.SurveyTaken__c = st.Id;
                        }
                    }
                }
                update transcripts;
            }
        }
    }
    
}