GearsetPOC/force-app/main/default/objects/Event/recordTypes/Dog_Approval_Event.recordType-meta.xml
<RecordType>
    <fullName>Dog_Approval_Event</fullName>
    <active>true</active>
    <label>Dog Approval Event</label>
</RecordType>

GearsetPOC/force-app/main/default/objects/Guide_assistance_dog__c/Guide_assistance_dog__c.object-meta.xml
<CustomObject>
    <label>Guide &amp; assistance dog</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Guide &amp; assistance dog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Guide &amp; assistance dogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Guide_assistance_dog__c/fields/Contact_email__c.field-meta.xml
<CustomField>
    <fullName>Contact_email__c</fullName>
    <label>Contact email</label>
    <type>Email</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Guide_assistance_dog__c/fields/Is_Dog_Microchipped__c.field-meta.xml
<CustomField>
    <fullName>Is_Dog_Microchipped__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Dog Microchipped</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Guide_assistance_dog__c/fields/Is_Dog_Tattooed__c.field-meta.xml
<CustomField>
    <fullName>Is_Dog_Tattooed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Dog Tattooed</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Guide_assistance_dog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Under review</fullName>
            </value>
            <value>
                <fullName>Needs corrections</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Waiting for signature</fullName>
                <isActive>false</isActive>
                <label>Waiting for signature</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>TCN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Booker__c.field-meta.xml
<CustomField>
    <fullName>Booker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booker</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tickets (Booker)</relationshipLabel>
    <relationshipName>TicketList</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Cancelled_By_Customer__c.field-meta.xml
<CustomField>
    <fullName>Cancelled_By_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ticket Cancelled</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <formula>IF(ISBLANK(ETAP_Email__c), IF(ISBLANK(Email__c), Booker__r.PersonEmail, Email__c), ETAP_Email__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Best of ETAP Email &gt; Ticket Email &gt; Booker Email</inlineHelpText>
    <label>Contact_Email</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Departure_Date_Time_Format__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date_Time_Format__c</fullName>
    <formula>DATETIMEVALUE(MID(Travel_DateTime__c,7,4)+&quot;-&quot;+MID(Travel_DateTime__c,4,2)+&quot;-&quot;+MID(Travel_DateTime__c,1,2)+&quot; &quot;+MID(Travel_DateTime__c,12,8))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Warning: the Time value might be not correct, as is depends on the departure timezones and the salesforce users timezones.</inlineHelpText>
    <label>Departure DateTime (formatted)</label>
    <type>DateTime</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <description>Destination Station</description>
    <label>Destination</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <label>PNR</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/Eins_EventTriggerHandler.cls
public without sharing class Eins_EventTriggerHandler {

    public static void updateDogAssistanceEvent(List<Event> dogEvents) {
        Map<Id, Event> oldDogEvents = new Map<Id, Event>();
        updateDogAssistanceEvent(dogEvents, oldDogEvents);
    }

    public static void updateDogAssistanceEvent(List<Event> dogEvents, Map<Id, Event> oldDogEvents) {
        String recordTypeId = Schema.SObjectType.Event.getRecordTypeInfosByDeveloperName().get('Dog_Approval_Event').getRecordTypeId();
        List<Event> dogApprovalEvents = new List<Event>();
        for (Event eventItem : dogEvents) {
            if (eventItem.RecordTypeId == recordTypeId) {
                dogApprovalEvents.add(eventItem);
            }
        }
        if (!dogApprovalEvents.isEmpty()) {
            Set<String> dogFormIds = new Set<String>();
            Set<String> ticketIds = new Set<String>();
            for (Event dogEvent : dogEvents) {
                if (String.isNotBlank(dogEvent.WhatId)) {
                    dogFormIds.add(dogEvent.WhatId);
                }
                if (String.isNotBlank(dogEvent.Ticket__c)) {
                    ticketIds.add(dogEvent.Ticket__c);
                }
            }

            Map<Id, Guide_assistance_dog__c> dogAssistances = new Map<Id, Guide_assistance_dog__c>([
                SELECT Id, Status__c, Is_Dog_Tattooed__c, Is_Dog_Microchipped__c
                FROM Guide_assistance_dog__c
                WHERE Id IN : dogFormIds
            ]);

            List<Ticket__c> tickets = [
                SELECT Id, Destination__c, Departure_Date_Time_Format__c, PNR__c, Booker__c, Contact_Email__c
                FROM Ticket__c
                WHERE Id IN : ticketIds
            ];
            Map<String, Ticket__c> ticketsByIds = new Map<String, Ticket__c>();
            for (Ticket__c ticket : tickets) {
                ticketsByIds.put(ticket.Id, ticket);
            }

            for (Event dogEvent : dogEvents) {
                if (dogAssistances.get(dogEvent.WhatId) != null) {
                    if (dogAssistances.get(dogEvent.WhatId).Status__c == 'Approved') {
                        dogEvent.Has_the_dog_been_approved_to_travel__c = true;
                    }

                    dogEvent.Was_the_dog_tattooed_before__c = dogAssistances.get(dogEvent.WhatId).Is_Dog_Tattooed__c;
                    dogEvent.Has_the_dog_got_a_microchip__c = dogAssistances.get(dogEvent.WhatId).Is_Dog_Microchipped__c;

                    if (ticketsByIds.get(dogEvent.Ticket__c) != null) {
                        dogEvent.IsAllDayEvent = false;
                        dogEvent.DurationInMinutes = 60;
                        dogEvent.ActivityDateTime = ticketsByIds.get(dogEvent.Ticket__c).Departure_Date_Time_Format__c;
                        dogEvent.At_which_station_will_they_alight__c = ticketsByIds.get(dogEvent.Ticket__c).Destination__c;
                        dogEvent.StartDateTime = ticketsByIds.get(dogEvent.Ticket__c).Departure_Date_Time_Format__c;
                        dogEvent.EndDateTime = ticketsByIds.get(dogEvent.Ticket__c).Departure_Date_Time_Format__c.addHours(1);
                        dogEvent.PNR__c = ticketsByIds.get(dogEvent.Ticket__c).PNR__c;
                    }
                    
                }
            }

            Eins_SendEmailController.sendEmails(dogEvents, oldDogEvents, false);
        }
    }

    public static void updateDogAssistanceEvent(List<Ticket__c> tickets, Map<Id, Ticket__c> oldTickets) {
        List<Ticket__c> ticketsWithUpdates = new List<Ticket__c>();
        for (Ticket__c ticketItem : tickets) {
            if (
                (ticketItem.Departure_Date_Time_Format__c != oldTickets.get(ticketItem.Id).Departure_Date_Time_Format__c) ||
                (ticketItem.PNR__c != oldTickets.get(ticketItem.Id).PNR__c) ||
                (ticketItem.Destination__c != oldTickets.get(ticketItem.Id).Destination__c) ||
                (ticketItem.Cancelled_By_Customer__c != oldTickets.get(ticketItem.Id).Cancelled_By_Customer__c)
            ) {
                ticketsWithUpdates.add(ticketItem);
            }
        }
        if (!ticketsWithUpdates.isEmpty()) {
            String recordTypeId = Schema.SObjectType.Event.getRecordTypeInfosByDeveloperName().get('Dog_Approval_Event').getRecordTypeId();
            Set<String> ticketIds = new Set<String>();
            Map<String, Ticket__c> ticketsByIds = new Map<String, Ticket__c>();
            for (Ticket__c ticket : tickets) {
                if (String.isNotBlank(ticket.Id)) {
                    ticketIds.add(ticket.Id);
                    ticketsByIds.put(ticket.Id, ticket);
                }
            }
    
            List<Event> relatedEvents = [
                SELECT Id, External_email_addresses__c, At_which_station_will_they_alight__c, StartDateTime,
                    EndDateTime, CreatedDate, LastModifiedDate, Subject, Description, PNR__c, Has_the_dog_been_approved_to_travel__c,
                    Does_the_dog_have_documents__c, Is_the_name_of_the_owner_the_same__c, Has_the_dog_got_a_microchip__c,
                    Was_the_dog_tattooed_before__c, Ticket__c
                FROM Event
                WHERE Ticket__c IN : ticketIds
                    AND RecordTypeId = :recordTypeId
            ];
    
            List<Event> updatedEvents = new List<Event>();
            for (Event dogEvent : relatedEvents) {
                if (String.isNotBlank(dogEvent.Ticket__c) && ticketsByIds.get(dogEvent.Ticket__c) != null) {
                    dogEvent.At_which_station_will_they_alight__c = ticketsByIds.get(dogEvent.Ticket__c).Destination__c;
                    dogEvent.StartDateTime = ticketsByIds.get(dogEvent.Ticket__c).Departure_Date_Time_Format__c;
                    dogEvent.EndDateTime = ticketsByIds.get(dogEvent.Ticket__c).Departure_Date_Time_Format__c.addHours(1);
                    if (ticketsByIds.get(dogEvent.Ticket__c).Cancelled_By_Customer__c) {
                        if (String.isNotBlank(dogEvent.Description)) {
                            dogEvent.Description = 'Cancelled by Customer. ' + dogEvent.Description;
                        }
                        dogEvent.Description = 'Cancelled by Customer.';
                    }
                    updatedEvents.add(dogEvent);
                }
            }
    
            if (!updatedEvents.isEmpty()) {
                try {
                    update updatedEvents;
                } catch(Exception e) {
                    System.debug(e);
                }
            }
        }
    }

    public static void cancelDogAssistanceEvent(List<Event> dogEvents) {
        Eins_SendEmailController.sendEmails(dogEvents, new Map<Id, Event>(), true);
    }
}