GearsetPOC/force-app/main/default/objects/BAF_Adjustment_Request__c/BAF_Adjustment_Request__c.object-meta.xml
<CustomObject>
    <label>BAF Adjustment Request</label>
    <nameField>
        <displayFormat>BAF-{000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BAF Adjustment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/BAF_Adjustment_Request__c/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Business_Account__c.ParentId__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Business_Account__c</referenceTo>
    <relationshipLabel>BAF Adjustment Requests</relationshipLabel>
    <relationshipName>BAF_Adjustment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/BAF_Adjustment_Request__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>BAF Adjustment Requests</relationshipLabel>
    <relationshipName>BAF_Adjustment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/BAF_Adjustment_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/Business_Account__c.object-meta.xml
<CustomObject>
    <description>Custom Business Account object created as part of Eurostar Delta migration project. Eurostar Jira ref DEIS-281</description>
    <label>Business Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Case/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Business_Account__c.ParentId__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Business_Account__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/BAFAdjustmentTriggerHandler.cls
public with sharing class BAFAdjustmentTriggerHandler {

    public static BAFAdjustmentTriggerHandler instance;
    public static BAFAdjustmentTriggerHandler getInstance() {
        if (instance == null) {
            instance = new BAFAdjustmentTriggerHandler();
        }
        return instance;
    } 

    public void onAfterInsert(List<BAF_Adjustment_Request__c> newObjects, Map<Id, BAF_Adjustment_Request__c> oldObjectsMap) {
        setCaseBusinessAccount(newObjects, oldObjectsMap);
    }

    public void setCaseBusinessAccount(List<BAF_Adjustment_Request__c> newObjects, Map<Id, BAF_Adjustment_Request__c> oldObjectsMap) {
        List<Case> caseRecords = new List<Case>(); 
        list<Case> casesForUpdate = new List<Case>();
        List<String> caseIds = new List<String>();
        Map<Id, BAF_Adjustment_Request__c> BAFByIds = new Map<Id, BAF_Adjustment_Request__c>();

        for (BAF_Adjustment_Request__c BAFItem : newObjects) {
            if (isNeedPopulateCaseBusinessAccount(BAFItem, oldObjectsMap)) {
                caseIds.add(BAFItem.Case__c);
                BAFByIds.put(BAFItem.Case__c, BAFItem);
            }
        }

        if (!caseIds.isEmpty()) {
            caseRecords = [
                SELECT Id, Business_Account__c 
                FROM Case 
                WHERE Id IN :caseIds AND Business_Account__c = null
            ];
    
            if(!caseRecords.isEmpty()) {
                for (Case caseItem : caseRecords) {
                    Case caseForUpdate = new Case();
                    caseForUpdate.Id = caseItem.Id;
                    caseForUpdate.Business_Account__c = BAFByIds.get(caseItem.Id).Business_Account__c;
                    casesForUpdate.add(caseForUpdate);
                }
    
                update casesForUpdate;
            }
        }
    }

    private Boolean isNeedPopulateCaseBusinessAccount(BAF_Adjustment_Request__c newBAF, Map<Id, BAF_Adjustment_Request__c> oldObjectsMap) {
        Boolean needPopulated = false;
        Boolean isBAanCaseLinkPopulated = (newBAF.Business_Account__c != null) && (newBAF.Case__c != null);

        if (isBAanCaseLinkPopulated) {
            if (oldObjectsMap == null) {
                needPopulated = (newBAF.Status__c != 'Draft') && (newBAF.Status__c != 'Cancelled');
            } else {
                needPopulated = (newBAF.Status__c != 'Draft') && (newBAF.Status__c != 'Cancelled') && oldObjectsMap.containsKey(newBAF.Id) && (oldObjectsMap.get(newBAF.Id).Status__c == 'Draft');
            }
        }

        return needPopulated;

    }



}