GearsetPOC/force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <displayFormat>C{000000000}</displayFormat>
        <label>Compensation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <formula>IF( AND(NOT( ISBLANK( Train__c )), NOT( ISBLANK( Train__r.Carrier__c )), NOT(Train__r.Carrier__c == &#39;Purple&#39;))  , 
Train__r.Carrier__c, 
IF( AND(NOT( ISBLANK(  Ticket__c )) ,NOT( TEXT( Ticket__r.Carrier__c ) == &#39;&#39;), NOT(TEXT(Ticket__r.Carrier__c) == &#39;Purple&#39;))  , 
TEXT(Ticket__r.Carrier__c), 
IF( AND(NOT( ISBLANK(  Case__c )) ,NOT( TEXT( Case__r.Carrier__c ) == &#39;&#39;), NOT(TEXT(Case__r.Carrier__c) == &#39;Purple&#39;))  , 
TEXT(Case__r.Carrier__c), 
IF( AND(NOT( ISBLANK(  CreatedById )) , NOT( TEXT( CreatedBy.Train_Service__c  ) == &#39;&#39;),  NOT(TEXT(CreatedBy.Train_Service__c ) == &#39;Purple&#39;)) ,
TEXT(CreatedBy.Train_Service__c ),
&#39;Blue&#39;))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Carrier</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Carrier_was_defaulted__c.field-meta.xml
<CustomField>
    <fullName>Carrier_was_defaulted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Carrier was defaulted</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/eVoucher__c/eVoucher__c.object-meta.xml
<CustomObject>
    <label>eVoucher</label>
    <nameField>
        <displayFormat>eV{000000000}</displayFormat>
        <label>eVoucher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eVouchers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/eVoucher__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <label>Carrier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blue</fullName>
                <default>true</default>
                <label>Blue</label>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/eVoucher__c/fields/Compensation__c.field-meta.xml
<CustomField>
    <fullName>Compensation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compensation</label>
    <referenceTo>Compensation__c</referenceTo>
    <relationshipLabel>eVouchers</relationshipLabel>
    <relationshipName>eVouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/eVoucher__c/fields/Handled_by_Mass_Compensation__c.field-meta.xml
<CustomField>
    <fullName>Handled_by_Mass_Compensation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Handled by Mass Compensation</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/DLT_EVoucherTriggerHandler.cls
public without sharing class DLT_EVoucherTriggerHandler {
    
    public static Boolean isDisabled = false;

    public static void run() {
        if (!System.Trigger.isExecuting || isDisabled) { return; }

        if (System.Trigger.isBefore) {
            if (System.Trigger.isInsert) {
                updateCarrierValues((List<eVoucher__c>)Trigger.new);
            }

            if (System.Trigger.isUpdate) {
            }
        }

        if (System.Trigger.isAfter) {
            if (System.Trigger.isInsert) {
            }

            if (System.Trigger.isUpdate) {
            }
        }
    }

    private static void updateCarrierValues(List<eVoucher__c> eVoucherList){

        Set<Id> compensationIds = new Set<Id>();

        for(eVoucher__c eV : eVoucherList){
            compensationIds.add(eV.Compensation__c);
        }

        Map<Id, Compensation__c> compensationMap = new Map<Id,Compensation__c>([
            SELECT Id, Carrier__c, Carrier_was_defaulted__c, Handled_by_Mass_Compensation__c
            FROM Compensation__c 
            WHERE Id IN :compensationIds]);

        for(eVoucher__c eVoucher : eVoucherList){

            if(eVoucher.recordTypeId != Schema.SObjectType.EVoucher__c.getRecordTypeInfosByName().get(DLT_EVoucherConstants.RECORDTYPE_SERVICE_RECOVERY).getRecordTypeId()) continue;

            eVoucher.Carrier_was_defaulted__c =
                compensationMap.containsKey(eVoucher.Compensation__c) 
                ? compensationMap.get(eVoucher.Compensation__c).Carrier_was_defaulted__c
                : false;

            eVoucher.Carrier__c = (
                compensationMap.containsKey(eVoucher.Compensation__c) 
                && (compensationMap.get(eVoucher.Compensation__c).Carrier__c == DLT_CompensationConstants.CARRIER_RED
                    || compensationMap.get(eVoucher.Compensation__c).Carrier__c == DLT_CompensationConstants.CARRIER_BLUE)) 
                ? compensationMap.get(eVoucher.Compensation__c).Carrier__c
                : DLT_CompensationConstants.CARRIER_BLUE;
            
            eVoucher.Handled_by_Mass_Compensation__c = 
                compensationMap.containsKey(eVoucher.Compensation__c) 
                ? compensationMap.get(eVoucher.Compensation__c).Handled_by_Mass_Compensation__c 
                : false;

        }
        
    }

}