GearsetPOC/force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <displayFormat>C{000000000}</displayFormat>
        <label>Compensation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Compensation</relationshipLabel>
    <relationshipName>Compensations</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Claim_Status__c.field-meta.xml
<CustomField>
    <fullName>Claim_Status__c</fullName>
    <label>Claim Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Claimed</fullName>
            </value>
            <value>
                <fullName>Error Occured</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Claimed_Compensation_Type__c.field-meta.xml
<CustomField>
    <fullName>Claimed_Compensation_Type__c</fullName>
    <label>Claimed Compensation Form</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Voucher</fullName>
            </value>
            <value>
                <fullName>Points</fullName>
            </value>
            <value>
                <fullName>PRR</fullName>
            </value>
            <value>
                <fullName>Voyager Voucher</fullName>
            </value>
            <value>
                <fullName>Business Account</fullName>
            </value>
            <value>
                <fullName>Voyager Points</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Compensation_Type__c.field-meta.xml
<CustomField>
    <fullName>Compensation_Type__c</fullName>
    <description>Returns the name of the Record Type</description>
    <formula>RecordType.Name</formula>
    <label>Compensation Type</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>CustomerC__r.Account.DELTA_Loyalty_Member__r.MembershipNumber</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Points_Amount__c.field-meta.xml
<CustomField>
    <fullName>Points_Amount__c</fullName>
    <label>Points Amount</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/recordTypes/Online.recordType-meta.xml
<RecordType>
    <fullName>Online</fullName>
    <active>true</active>
    <description>Record type for Online compensation</description>
    <label>Online</label>
</RecordType>

GearsetPOC/force-app/main/default/objects/Compensation__c/recordTypes/Points.recordType-meta.xml
<RecordType>
    <fullName>Points</fullName>
    <active>true</active>
    <description>Loyalty Points</description>
    <label>Points</label>
</RecordType>

GearsetPOC/force-app/main/default/objects/TransactionJournal/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Transaction Journals</relationshipLabel>
    <relationshipName>Transaction_Journals</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/TransactionJournal/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/OSF_Compensation_TriggerHandler.cls
public without sharing class OSF_Compensation_TriggerHandler {
    private static String JOURNAL_TYPE_NAME = Test.isRunningTest() ? 'AccrualTest' : 'Accrual';

    public static void createTransactionJournals(List<Compensation__c> newList, Map<Id, Compensation__c> oldMap) {
        if (!OSF_Utility.isActive('OSF_Compensation_TriggerHandler', 'createTransactionJournals') && !Test.isRunningTest()) {
            return;
        }
        List<TransactionJournal> lstTransactionJournals = new List<TransactionJournal>();
        Map<String, Compensation__c> mapMembershipNumbersToCompensations = new Map<String, Compensation__c>();
        System.Debug('### in createTransactionJournals');
        try {
            for (Compensation__c c : newList) {
                system.debug('line:13');
            if (((!String.isBlank(c.Compensation_Type__c) && c.Compensation_Type__c.toLowerCase() == 'points') || (!String.isBlank(c.Claimed_Compensation_Type__c) && c.Claimed_Compensation_Type__c.toLowerCase() == 'points' && (!String.isBlank(c.Compensation_Type__c) && c.Compensation_Type__c.toLowerCase() == 'online'))) && c.Claim_Status__c == 'Claimed' && (oldMap==null || (oldMap!=null && oldMap.get(c.Id).Claim_Status__c != 'Claimed'))) {
                    mapMembershipNumbersToCompensations.put(c.Membership_Number__c, c);
                }
            }
            system.debug('line:18'+mapMembershipNumbersToCompensations);
            if (mapMembershipNumbersToCompensations.size() > 0) {
                	system.debug('line:20');
                	JournalType jt = [SELECT Id FROM JournalType WHERE Name =: JOURNAL_TYPE_NAME];
                    system.debug('line:22'+jt);
                    JournalSubType jst = [SELECT Id FROM JournalSubType WHERE Name = 'Compensation'];
                     system.debug('line:25'+jst);
                        System.Debug('### mapMembershipNumbersToCompensations: ' + mapMembershipNumbersToCompensations);
                    for (LoyaltyProgramMember lpm :[SELECT Id, MembershipNumber, ProgramId FROM LoyaltyProgramMember WHERE MembershipNumber IN :mapMembershipNumbersToCompensations.keySet()]) {
                        System.debug('### in for');
                        TransactionJournal tj = new TransactionJournal();
                        tj.MemberId = lpm.Id;
                        tj.LoyaltyProgramId = lpm.ProgramId;
                        tj.ActivityDate = System.today();
                        tj.Status = 'Pending';
                        tj.JournalTypeId = jt.Id;
                        tj.JournalSubTypeId = jst.Id;
                        tj.Case__c = mapMembershipNumbersToCompensations.get(lpm.MembershipNumber).Case__c;
                        tj.Points__c = mapMembershipNumbersToCompensations.get(lpm.MembershipNumber).Points_Amount__c;
                        lstTransactionJournals.add(tj);
                    }
                    System.Debug('### lstTransactionJournals: ' + lstTransactionJournals);
                    if (!lstTransactionJournals.isEmpty()) {
                        system.debug('Inserted');
                        insert lstTransactionJournals;
                    }
            }
            
        } catch(Exception e) {
            system.debug('ex'+e);
            OSF_ErrorLogHandler.logError(e, 'OSF_Compensation_TriggerHandler');
        } finally {
            OSF_ErrorLogHandler.saveErrors();
        }
    }
}