GearsetPOC/force-app/main/default/objects/Account/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Business_Account__c.ParentId__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Business_Account__c</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/Business_Account__c.object-meta.xml
<CustomObject>
    <description>Custom Business Account object created as part of Eurostar Delta migration project. Eurostar Jira ref DEIS-281</description>
    <label>Business Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Contracted</fullName>
            </value>
            <value>
                <fullName>Softly Managed</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Unmanaged</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/Blue_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Blue_Account_Type__c</fullName>
    <description>Used to classify the agents based on the Red corporate framework. Each level of classification gives various benefits</description>
    <label>Blue Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/Corporate_Code_Active__c.field-meta.xml
<CustomField>
    <fullName>Corporate_Code_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Corporate Code Active</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/FCE_Continent_Active__c.field-meta.xml
<CustomField>
    <fullName>FCE_Continent_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FCE Continent Active</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/FCE_London_Active__c.field-meta.xml
<CustomField>
    <fullName>FCE_London_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FCE London Active</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/GDS_Code_Active__c.field-meta.xml
<CustomField>
    <fullName>GDS_Code_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>GDS Code Active</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/GND_BE_Continent_Active__c.field-meta.xml
<CustomField>
    <fullName>GND_BE_Continent_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>GND BE Continent Active</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/GND_BE_London_Active__c.field-meta.xml
<CustomField>
    <fullName>GND_BE_London_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>GND BE London Active</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/GND_NL_Continent_Active__c.field-meta.xml
<CustomField>
    <fullName>GND_NL_Continent_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>GND NL Continent Active</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/GND_NL_London_Active__c.field-meta.xml
<CustomField>
    <fullName>GND_NL_London_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>GND NL London Active</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/Is_Continent_Duplicated__c.field-meta.xml
<CustomField>
    <fullName>Is_Continent_Duplicated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Continent Duplicated</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/Is_London_Duplicated__c.field-meta.xml
<CustomField>
    <fullName>Is_London_Duplicated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is London Duplicated</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to main parent account</description>
    <label>Main Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>Business_Account__c.RecordTypeId</valueField>
        </filterItems>
        <infoMessage>Allows only selection of records of the same record type as current record</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Business_Account__c</referenceTo>
    <relationshipLabel>Business Accounts</relationshipLabel>
    <relationshipName>Business_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/Red_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Red_Account_Type__c</fullName>
    <description>Used to classify the agents based on the Red corporate framework. Each level of classification gives various benefits</description>
    <label>Red Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TCF1</fullName>
            </value>
            <value>
                <fullName>TCF2</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
                <isActive>false</isActive>
                <label>OTHER</label>
            </value>
            <value>
                <fullName>PROSPECT</fullName>
                <isActive>false</isActive>
                <label>PROSPECT</label>
            </value>
            <value>
                <fullName>Unmanaged</fullName>
                <isActive>false</isActive>
                <label>Unmanaged</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Contract__c/Business_Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Business Contract object created as part of Eurostar Delta migration project. Eurostar Jira ref DEIS-283</description>
    <label>Business Contract</label>
    <nameField>
        <displayFormat>CO-{000000}</displayFormat>
        <label>Contract Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/classes/DLT_BusinessAccountService.cls
public inherited sharing class DLT_BusinessAccountService {
    public static Id getMainAccountId(Business_Account__c businessAccount) {
        Id mainAccountId;

        if (businessAccount?.ParentId__r?.ParentId__r?.ParentId__r?.ParentId__r?.ParentId__r?.ParentId__c != null) {
            mainAccountId = businessAccount.ParentId__r.ParentId__r.ParentId__r.ParentId__r.ParentId__r.ParentId__c;
        } else if (businessAccount?.ParentId__r?.ParentId__r?.ParentId__r?.ParentId__r?.ParentId__c != null) {
            mainAccountId = businessAccount.ParentId__r.ParentId__r.ParentId__r.ParentId__r.ParentId__c;
        } else if (businessAccount?.ParentId__r?.ParentId__r?.ParentId__r?.ParentId__c != null) {
            mainAccountId = businessAccount.ParentId__r.ParentId__r.ParentId__r.ParentId__c;
        } else if (businessAccount?.ParentId__r?.ParentId__r?.ParentId__c != null) {
            mainAccountId = businessAccount.ParentId__r.ParentId__r.ParentId__c;
        } else if (businessAccount?.ParentId__r?.ParentId__c != null) {
            mainAccountId = businessAccount.ParentId__r.ParentId__c;
        } else if (businessAccount?.ParentId__c != null) {
            mainAccountId = businessAccount.ParentId__c;
        }

        return mainAccountId == null ? businessAccount.Id : mainAccountId;
    }

    public static Boolean isNotAllowedContract(Business_Account__c account, Business_Contract__c childContract) {
        return (!isCorporate(account) || !isContracted(account))
            || (DLT_BusinessContractService.isContinent(childContract) && !(isActiveContinent(account) && isTCF(account)))
            || (DLT_BusinessContractService.isLondon(childContract) && !(isActiveLondon(account) && isGoldOrPlatinum(account)));
    }

    public static Boolean isAllowedContractContinent(Business_Account__c account) {
        return isCorporate(account) && isContracted(account) && isActiveContinent(account) && isTCF(account);
    }

    public static Boolean isAllowedContractLondon(Business_Account__c account) {
        return isCorporate(account) && isContracted(account) && isActiveLondon(account) && isGoldOrPlatinum(account);
    }

    private static Boolean isActiveContinent(Business_Account__c account) {
        return account.FCE_Continent_Active__c ||
            account.GDS_Code_Active__c ||
            account.GND_BE_Continent_Active__c ||
            account.GND_NL_Continent_Active__c;
    }

    private static Boolean isActiveLondon(Business_Account__c account) {
        return account.FCE_London_Active__c ||
            account.Corporate_Code_Active__c ||
            account.GND_BE_London_Active__c ||
            account.GND_NL_London_Active__c;
    }

    private static Boolean isTCF(Business_Account__c account) {
        return isTCF1(account) || isTCF2(account);
    }

    private static Boolean isGoldOrPlatinum(Business_Account__c account) {
        return isGold(account) || isPlatinum(account);
    }

    public static Boolean isCorporate(Business_Account__c account) {
        return account?.RecordTypeId == DLT_BusinessAccountConstants.CORPORATE_ACCOUNT_INFO.getRecordTypeId();
    }

    public static Boolean isContracted(Business_Account__c account) {
        return account?.Account_Status__c == DLT_BusinessAccountConstants.STATUS_CONTRACTED;
    }

    public static Boolean isTCF1(Business_Account__c account) {
        return account?.Red_Account_Type__c == DLT_BusinessAccountConstants.RED_ACCOUNT_TYPE_TCF1;
    }

    public static Boolean isTCF2(Business_Account__c account) {
        return account?.Red_Account_Type__c == DLT_BusinessAccountConstants.RED_ACCOUNT_TYPE_TCF2;
    }

    public static Boolean isGold(Business_Account__c account) {
        return account?.Blue_Account_Type__c == DLT_BusinessAccountConstants.BLUE_ACCOUNT_TYPE_GOLD;
    }

    public static Boolean isPlatinum(Business_Account__c account) {
        return account?.Blue_Account_Type__c == DLT_BusinessAccountConstants.BLUE_ACCOUNT_TYPE_PLATINUM;
    }

    public static Boolean isContinentDuplicated(Business_Account__c account) {
        return account == null ? false : account?.Is_Continent_Duplicated__c;
    }

    public static Boolean isLondonDuplicated(Business_Account__c account) {
        return account == null ? false : account?.Is_London_Duplicated__c;
    }
}