GearsetPOC/force-app/main/default/objects/Account/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Business_Account__c.ParentId__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Business_Account__c</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/Business_Account__c.object-meta.xml
<CustomObject>
    <description>Custom Business Account object created as part of Eurostar Delta migration project. Eurostar Jira ref DEIS-281</description>
    <label>Business Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/Blue_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Blue_Account_Type__c</fullName>
    <description>Used to classify the agents based on the Red corporate framework. Each level of classification gives various benefits</description>
    <label>Blue Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/Red_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Red_Account_Type__c</fullName>
    <description>Used to classify the agents based on the Red corporate framework. Each level of classification gives various benefits</description>
    <label>Red Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TCF1</fullName>
            </value>
            <value>
                <fullName>TCF2</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
                <isActive>false</isActive>
                <label>OTHER</label>
            </value>
            <value>
                <fullName>PROSPECT</fullName>
                <isActive>false</isActive>
                <label>PROSPECT</label>
            </value>
            <value>
                <fullName>Unmanaged</fullName>
                <isActive>false</isActive>
                <label>Unmanaged</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Airline</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Groups / Tours / Niche</fullName>
            </value>
            <value>
                <fullName>Inbounders / DMC</fullName>
            </value>
            <value>
                <fullName>Influencers</fullName>
            </value>
            <value>
                <fullName>Institutional Partners</fullName>
            </value>
            <value>
                <fullName>Leisure Agent</fullName>
            </value>
            <value>
                <fullName>OTA</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Prof. Association</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Suppliers</fullName>
            </value>
            <value>
                <fullName>Techno Providers</fullName>
            </value>
            <value>
                <fullName>TMC</fullName>
            </value>
            <value>
                <fullName>Tour Operator</fullName>
            </value>
            <value>
                <fullName>Tourist Office</fullName>
            </value>
            <value>
                <fullName>Travel Trade Press</fullName>
            </value>
            <value>
                <fullName>Reward Redemption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/recordTypes/Agency_Account.recordType-meta.xml
<RecordType>
    <fullName>Agency_Account</fullName>
    <active>true</active>
    <label>Agency Account</label>
</RecordType>

GearsetPOC/force-app/main/default/objects/Business_Account__c/recordTypes/Business_Accounts.recordType-meta.xml
<RecordType>
    <fullName>Business_Accounts</fullName>
    <active>true</active>
    <label>Business Accounts</label>
</RecordType>

GearsetPOC/force-app/main/default/objects/Business_Account__c/recordTypes/Corporate_Account.recordType-meta.xml
<RecordType>
    <fullName>Corporate_Account</fullName>
    <active>true</active>
    <label>Corporate Account</label>
</RecordType>

GearsetPOC/force-app/main/default/objects/Business_Account__c/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>Accounts that are not clients</description>
    <label>Other</label>
</RecordType>

GearsetPOC/force-app/main/default/classes/DLT_BusinessAccountConstants.cls
public inherited sharing class DLT_BusinessAccountConstants {
    
    public static final Schema.RecordTypeInfo CORPORATE_ACCOUNT_INFO = Schema.SObjectType.Business_Account__c.getRecordTypeInfosByDeveloperName().get('Corporate_Account');
    public static final Schema.RecordTypeInfo AGENCY_ACCOUNT_INFO = Schema.SObjectType.Business_Account__c.getRecordTypeInfosByDeveloperName().get('Agency_Account');
    public static final Schema.RecordTypeInfo BUSINESS_ACCOUNTS_INFO = Schema.SObjectType.Business_Account__c.getRecordTypeInfosByDeveloperName().get('Business_Accounts');
    public static final Id RECORD_TYPE_ID_AGENCY = AGENCY_ACCOUNT_INFO.getRecordTypeId();
    public static final Id RECORD_TYPE_ID_CORPORATE = CORPORATE_ACCOUNT_INFO.getRecordTypeId();
    public static final Id RECORD_TYPE_ID_BUSINESS = BUSINESS_ACCOUNTS_INFO.getRecordTypeId();

    //Status__c picklist
    public static final String STATUS_CONTRACTED = 'Contracted';

    //Red_Account_Type__c picklist
    public static final String RED_ACCOUNT_TYPE_TCF1 = 'TCF1';
    public static final String RED_ACCOUNT_TYPE_TCF2 = 'TCF2';

    //Blue_Account_Type__c picklist
    public static final String BLUE_ACCOUNT_TYPE_GOLD = 'Gold';
    public static final String BLUE_ACCOUNT_TYPE_PLATINUM = 'Platinum';

    //Type__c picklist
    public static final String TYPE_OTHER = 'Other';

    //Account Number prexif by type
    public static final Map<String,String> TYPE_TO_PREFIX = new Map<String,String>{
        'Airline' => 'AL',
        'Tour Operator' => 'TO',
        'Leisure Agent' => 'LA',
        'Distributor' => 'DI',
        'Groups / Tours / Niche' => 'GT',
        'Inbounders / DMC' => 'IN',
        'TMC' => 'GD',
        'Reward Redemption' => 'RR',
        'OTA' => 'OT',
        'Retail' => 'RE',
        'Other' => 'OO',
        null => ''
    };
}