GearsetPOC/force-app/main/default/objects/Account/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Business_Account__c.ParentId__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Business_Account__c</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_AccountCTC__c/B2b_AccountCTC__c.object-meta.xml
<CustomObject>
    <description>Junction Object delivered to support New Corporate Offer Project May /June 2024</description>
    <label>Account CTC</label>
    <nameField>
        <displayFormat>CTC-{0000}</displayFormat>
        <label>Account CTC</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account CTCs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/B2b_AccountCTC__c/fields/B2b_AccountId__c.field-meta.xml
<CustomField>
    <fullName>B2b_AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Account</label>
    <referenceTo>Business_Account__c</referenceTo>
    <relationshipLabel>Account CTCs</relationshipLabel>
    <relationshipName>Account_CTCs</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_AccountCTC__c/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <formula>B2b_AccountId__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Account</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_AccountCTC__c/fields/Corp_Tracking_Type_And_Code__c.field-meta.xml
<CustomField>
    <fullName>Corp_Tracking_Type_And_Code__c</fullName>
    <label>Corporate Code</label>
    <referenceTo>Corp_Tracking_Type_and_Code__c</referenceTo>
    <relationshipLabel>Account CTCs</relationshipLabel>
    <relationshipName>Account_CTCs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/B2b_NrDetails__c.object-meta.xml
<CustomObject>
    <description>Custom object migrated from Thango as part of Eurostar Delta migration project. Eurostar Jira ref DEIS-320</description>
    <label>Negotiated Rate</label>
    <nameField>
        <displayFormat>NR-{0000}</displayFormat>
        <label>Negotiated Rates SF Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Negotiated Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>this is to Support the Negotiated Rates List Views</description>
    <formula>CASESAFEID(ContractID__r.AccountId__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AccountId</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/fields/B2b_RouteEndDate__c.field-meta.xml
<CustomField>
    <fullName>B2b_RouteEndDate__c</fullName>
    <label>Route End Date</label>
    <type>Date</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/fields/B2b_Status__c.field-meta.xml
<CustomField>
    <fullName>B2b_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>To be Extracted</fullName>
            </value>
            <value>
                <fullName>Extracted</fullName>
            </value>
            <value>
                <fullName>Integrated</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>To be Approved</fullName>
            </value>
            <value>
                <fullName>New - Default</fullName>
                <isActive>false</isActive>
                <label>New - Default</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/B2b_NrDetails__c/fields/ContractID__c.field-meta.xml
<CustomField>
    <fullName>ContractID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Business_Contract__c</referenceTo>
    <relationshipLabel>Negotiated Rates</relationshipLabel>
    <relationshipName>Negotiated_Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Account__c/Business_Account__c.object-meta.xml
<CustomObject>
    <description>Custom Business Account object created as part of Eurostar Delta migration project. Eurostar Jira ref DEIS-281</description>
    <label>Business Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Business_Account__c/fields/No_Continent_Account_CTC__c.field-meta.xml
<CustomField>
    <fullName>No_Continent_Account_CTC__c</fullName>
    <label>No. Continent Account CTC</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Contract__c/Business_Contract__c.object-meta.xml
<CustomObject>
    <description>Custom Business Contract object created as part of Eurostar Delta migration project. Eurostar Jira ref DEIS-283</description>
    <label>Business Contract</label>
    <nameField>
        <displayFormat>CO-{000000}</displayFormat>
        <label>Contract Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Business_Contract__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Business_Account__c</referenceTo>
    <relationshipLabel>Business Contracts (Account Name)</relationshipLabel>
    <relationshipName>Business_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Contract__c/fields/B2b_Status__c.field-meta.xml
<CustomField>
    <fullName>B2b_Status__c</fullName>
    <label>Status (delete)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Contract__c/fields/End_of_Contract__c.field-meta.xml
<CustomField>
    <fullName>End_of_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Manually set by the Account Manager to confirm the contract has ended</description>
    <label>End of Contract</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Business_Contract__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Corp_Tracking_Type_and_Code__c/Corp_Tracking_Type_and_Code__c.object-meta.xml
<CustomObject>
    <label>Corporate Tracking</label>
    <nameField>
        <label>Corporate Tracking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corporate Trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/NR_to_AccountCTC__c/NR_to_AccountCTC__c.object-meta.xml
<CustomObject>
    <description>Junction Object delivered to support New Corporate Offer Project May /June 2024</description>
    <label>NR to Account CTC</label>
    <nameField>
        <displayFormat>NRC-{000000}</displayFormat>
        <label>NR to Account CTC</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NR to Account CTCs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/NR_to_AccountCTC__c/fields/Account_CTC__c.field-meta.xml
<CustomField>
    <fullName>Account_CTC__c</fullName>
    <label>Account CTC</label>
    <referenceTo>B2b_AccountCTC__c</referenceTo>
    <relationshipLabel>NR to Account CTCs</relationshipLabel>
    <relationshipName>NR_to_Account_CTCs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/NR_to_AccountCTC__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF(
    NOT(Account_CTC__r.Active__c), 
    FALSE, 
    IF(
        AND(
            OR(
                Account_CTC__r.Code_Record_Type__c = &#39;Corporate code Amadeus&#39;,
                Account_CTC__r.Code_Record_Type__c = &#39;Corporate code Apollo&#39;,
                Account_CTC__r.Code_Record_Type__c = &#39;Corporate code Galileo&#39;,
                Account_CTC__r.Code_Record_Type__c = &#39;Corporate code Sabre&#39;
            ), 
            Account_CTC__r.Corp_Tracking_Type_And_Code__r.Active_Account_PCCs__c = 0
        ), 
        FALSE, 
        TRUE
    )
)</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/NR_to_AccountCTC__c/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <formula>Account_CTC__r.Business_Account__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Account</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/NR_to_AccountCTC__c/fields/Negotiated_Rate__c.field-meta.xml
<CustomField>
    <fullName>Negotiated_Rate__c</fullName>
    <label>Negotiated Rate</label>
    <referenceTo>B2b_NrDetails__c</referenceTo>
    <relationshipLabel>NR to Account CTCs</relationshipLabel>
    <relationshipName>NR_to_Account_CTCs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/AccountCtcTriggerHandler.cls
public without sharing class AccountCtcTriggerHandler {
    public static Boolean isDisabled = false;

    public static void run() {
        if (!System.Trigger.isExecuting || isDisabled) { return; }

        if (System.Trigger.isAfter) {
            if (System.Trigger.isInsert) {
                createNRtoAccountCTCs(Trigger.new);
                updateRelatedNegotiatedRates(Trigger.new);
                updateRelatedBusinessAccounts(Trigger.new);
            }

            if (System.Trigger.isUpdate) {
                updateRelatedNegotiatedRates(Trigger.new, (Map<Id, B2b_AccountCTC__c>) Trigger.oldMap);
                updateRelatedBusinessAccounts(Trigger.old, (Map<Id, B2b_AccountCTC__c>) Trigger.newMap);
            }

            if (System.Trigger.isDelete) {
                updateRelatedBusinessAccounts(Trigger.old);
            }

            if (System.Trigger.isUndelete) {
                updateRelatedBusinessAccounts(Trigger.new);
            }
        }
    }

    private static void createNRtoAccountCTCs(List<B2b_AccountCTC__c> newAccountCTCs) {
        Set<Id> businessAccountIds = new Set<Id>();
        List<B2b_AccountCTC__c> accountCTCsToProcess = new List<B2b_AccountCTC__c>();

        for (B2b_AccountCTC__c actc : newAccountCTCs) {
            if (actc.B2b_AccountId__c != null) {
                businessAccountIds.add(actc.B2b_AccountId__c);
                accountCTCsToProcess.add(actc);
            }
        }

        if (businessAccountIds.isEmpty()) { return; }

        Map<Id, Business_Contract__c> activeContracts = new Map<Id, Business_Contract__c>([
            SELECT Id
            FROM Business_Contract__c
            WHERE AccountId__c IN :businessAccountIds
            AND (EndDate__c = NULL OR EndDate__c > TODAY)
            AND End_of_Contract__c = FALSE
        ]);

        if (activeContracts.isEmpty()) { return; }

        List<B2b_NrDetails__c> ratesToProcess = [
            SELECT ContractId__r.AccountId__c
            FROM B2b_NrDetails__c
            WHERE ContractId__c IN :activeContracts.keySet()
            AND (B2b_RouteEndDate__c = NULL OR B2b_RouteEndDate__c > TODAY)
        ];

        if (ratesToProcess.isEmpty()) { return; }

        List<NR_to_AccountCTC__c> nrToAccountCTCs = new List<NR_to_AccountCTC__c>();

        for (B2b_AccountCTC__c accountCTC : accountCTCsToProcess) {
            for (B2b_NrDetails__c nr : ratesToProcess) {
                if (accountCTC.B2b_AccountId__c == nr.ContractId__r.AccountId__c) {
                    nrToAccountCTCs.add(new NR_to_AccountCTC__c(
                        Account_CTC__c = accountCTC.Id,
                        Negotiated_Rate__c = nr.Id
                    ));
                }
            }
        }

        if (!nrToAccountCTCs.isEmpty()) {
            insert nrToAccountCTCs;
        }
    }

    private static void updateRelatedNegotiatedRates(List<B2b_AccountCTC__c> accountCtcList, Map<Id, B2b_AccountCTC__c> oldAccountCtcMap) {
        List<B2b_AccountCTC__c> accountCTCsChangedList = new List<B2b_AccountCTC__c>();
        for (B2b_AccountCTC__c accountCtc : accountCtcList) {
            if (accountCtc.Active__c != oldAccountCtcMap.get(accountCtc.Id).Active__c) {
                accountCTCsChangedList.add(accountCtc);
            }
        }

        if (!accountCTCsChangedList.isEmpty()) {
            updateRelatedNegotiatedRates(accountCTCsChangedList);
        }
    }

    private static void updateRelatedNegotiatedRates(List<B2b_AccountCTC__c> accountCtcList) {
        Set<Id> accountIds = new Set<Id>();
        for (B2b_AccountCTC__c accountCtc : accountCtcList) {
            if (accountCtc.B2b_AccountId__c != null) {
                accountIds.add(accountCtc.B2b_AccountId__c);
            }
        }

        if (accountIds.isEmpty()) { return; }

        List<B2b_NrDetails__c> rates = [
            SELECT ContractID__r.AccountId__c
            FROM B2b_NrDetails__c
            WHERE ContractID__r.AccountId__c IN : accountIds
                AND ContractID__r.End_of_Contract__c = false
                AND (B2b_RouteEndDate__c = null
                    OR B2b_RouteEndDate__c = TODAY
                    OR B2b_RouteEndDate__c > TODAY)
        ];

        if (rates.isEmpty()) { return; }

        for (B2b_NrDetails__c rate : rates) {
            rate.B2b_Status__c = DLT_NegotiatedRateConstants.STATUS_TO_BE_EXTRACTED;
        }

        update rates;
    }

    private static void updateRelatedBusinessAccounts(List<B2b_AccountCTC__c> accountCtcList) {
        Set<Id> businessAccountIds = new Set<Id>();
        for (B2b_AccountCTC__c ctc : accountCtcList) {
            if (ctc.B2b_AccountId__c != null) {
                businessAccountIds.add(ctc.B2b_AccountId__c);
            }
        }

        updateAccountCTCsCount(businessAccountIds);
        DLT_BusinessAccountService.updateMissingAccPccCodesCount(businessAccountIds);
    }

    private static void updateRelatedBusinessAccounts(List<B2b_AccountCTC__c> oldAccountCtcList, Map<Id, B2b_AccountCTC__c> newAccountCtcMap) {
        Set<Id> businessAccountIds = new Set<Id>();
        for (B2b_AccountCTC__c oldCtc : oldAccountCtcList) {
            B2b_AccountCTC__c newCtc = newAccountCtcMap.get(oldCtc.Id);
            if (oldCtc.B2b_AccountId__c != newCtc.B2b_AccountId__c || oldCtc.Active__c != newCtc.Active__c) {
                if (newCtc.B2b_AccountId__c != null) {
                    businessAccountIds.add(newCtc.B2b_AccountId__c);
                }
                if (oldCtc.B2b_AccountId__c != null && newCtc.B2b_AccountId__c == null) {
                    businessAccountIds.add(oldCtc.B2b_AccountId__c);
                }
            }
        }

        updateAccountCTCsCount(businessAccountIds);
        DLT_BusinessAccountService.updateMissingAccPccCodesCount(businessAccountIds);
    }

    private static void updateAccountCTCsCount(Set<Id> businessAccountIds) {
        if (businessAccountIds == null || businessAccountIds.isEmpty()) { return; }

        List<AggregateResult> results = [
            SELECT B2b_AccountId__c, COUNT(Id)
            FROM B2b_AccountCTC__c
            WHERE B2b_AccountId__c IN :businessAccountIds
              AND Active__c = true
              AND Corp_Tracking_Type_and_Code__r.RecordTypeId IN :DLT_CorporateTrackingConstants.NCO_RECORD_TYPE_IDS
            GROUP BY B2b_AccountId__c
        ];

        Map<Id, Integer> accountCtcCountMap = new Map<Id, Integer>();
        //save into the map the count of active Account CTCs
        for (AggregateResult ar : results) {
            Id accountId = (Id) ar.get('B2b_AccountId__c');
            Integer count = (Integer) ar.get('expr0');
            accountCtcCountMap.put(accountId, count);
        }

        //add to map the businesss account ids with no active Account CTCs
        for (Id accountId : businessAccountIds) {
            if(!accountCtcCountMap.containsKey(accountId)) {
                accountCtcCountMap.put(accountId, 0);
            }
        }

        List<Business_Account__c> accountsToUpdate = new List<Business_Account__c>();
        for (Id accountId : accountCtcCountMap.keySet()) {
            Business_Account__c account = new Business_Account__c(
                Id = accountId,
                No_Continent_Account_CTC__c = accountCtcCountMap.get(accountId)
            );
            accountsToUpdate.add(account);
        }

        if (!accountsToUpdate.isEmpty()) {
            update accountsToUpdate; //we should not disable a Business Account trigger as this update needs to trigger the duplication logic
        }
    }
}