GearsetPOC/force-app/main/default/objects/Account/fields/Country_B__c.field-meta.xml
<CustomField>
    <fullName>Country_B__c</fullName>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Account/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Customer_Email is email and External ID. Kept in sync with the standard Email field.  The Customer Email will not appear on page layouts, it is for integration matching only.</description>
    <externalId>true</externalId>
    <label>Customer Email_</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

GearsetPOC/force-app/main/default/objects/Account/fields/E4A_Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>E4A_Customer_Type__c</fullName>
    <label>E4A Company Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Airline</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Distributor (rail operator)</fullName>
            </value>
            <value>
                <fullName>Distributors (Train operating company)</fullName>
                <isActive>false</isActive>
                <label>Distributors (Train operating company)</label>
            </value>
            <value>
                <fullName>Groups</fullName>
            </value>
            <value>
                <fullName>Inbounder</fullName>
            </value>
            <value>
                <fullName>Leisure Agent</fullName>
            </value>
            <value>
                <fullName>MICE</fullName>
            </value>
            <value>
                <fullName>Online Travel Agencies (OTA)</fullName>
                <isActive>false</isActive>
                <label>Online Travel Agencies (OTA)</label>
            </value>
            <value>
                <fullName>Online Travel Agent</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Reward Redemption</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>Technical provider</fullName>
            </value>
            <value>
                <fullName>TMC</fullName>
            </value>
            <value>
                <fullName>Tour Operator</fullName>
            </value>
            <value>
                <fullName>Travel Management Company</fullName>
                <isActive>false</isActive>
                <label>Travel Management Company</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Account/fields/E4A_Newsletter_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>E4A_Newsletter_Opt_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>E4A Subscriber</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Account/fields/E4A_Opt_Out_Other_Reason__c.field-meta.xml
<CustomField>
    <fullName>E4A_Opt_Out_Other_Reason__c</fullName>
    <label>E4A Opt Out Other Reason</label>
    <type>TextArea</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Account/fields/E4A_Opt_Out_Reason__c.field-meta.xml
<CustomField>
    <fullName>E4A_Opt_Out_Reason__c</fullName>
    <label>E4A Opt Out Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>I receive too many emails</fullName>
            </value>
            <value>
                <fullName>The emails are not relevant to me</fullName>
            </value>
            <value>
                <fullName>Uninteresting or repetetive content</fullName>
            </value>
            <value>
                <fullName>The format is not easy to read</fullName>
            </value>
            <value>
                <fullName>I can&#39;t properly view the emails</fullName>
            </value>
            <value>
                <fullName>I don&#39;t remember subscribing</fullName>
            </value>
            <value>
                <fullName>Other (please explain)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Account/fields/E4A_Subscriber_Status__c.field-meta.xml
<CustomField>
    <fullName>E4A_Subscriber_Status__c</fullName>
    <label>E4A Subscriber Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Account/fields/Indirect_Sales_Topics__c.field-meta.xml
<CustomField>
    <fullName>Indirect_Sales_Topics__c</fullName>
    <label>Indirect Sales Topics</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Corporate Newsletter</fullName>
            </value>
            <value>
                <fullName>Disruption - Continental</fullName>
            </value>
            <value>
                <fullName>Disruption - London</fullName>
            </value>
            <value>
                <fullName>E4A Topics</fullName>
                <isActive>false</isActive>
                <label>E4A Topics</label>
            </value>
            <value>
                <fullName>E4B Newsletter</fullName>
            </value>
            <value>
                <fullName>Leisure Newsletter</fullName>
            </value>
            <value>
                <fullName>MICE</fullName>
            </value>
            <value>
                <fullName>Miscellaneous topics</fullName>
                <isActive>false</isActive>
                <label>Miscellaneous topics</label>
            </value>
            <value>
                <fullName>Partner API Comms</fullName>
            </value>
            <value>
                <fullName>Promo &amp; OOS</fullName>
            </value>
            <value>
                <fullName>Promo Live</fullName>
            </value>
            <value>
                <fullName>Promo Testing</fullName>
            </value>
            <value>
                <fullName>RIT Comms</fullName>
            </value>
            <value>
                <fullName>Strike</fullName>
                <isActive>false</isActive>
                <label>Strike</label>
            </value>
            <value>
                <fullName>Timetable</fullName>
                <isActive>false</isActive>
                <label>Timetable</label>
            </value>
            <value>
                <fullName>TMC newsletter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Account/fields/Other_Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Other_Customer_Type__c</fullName>
    <label>Other Customer Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Account/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <formula>TEXT(Preferred_Language__pc)</formula>
    <label>Preferred Language</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <formula>Contact.Customer_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Email</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/E4A_Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>E4A_Customer_Type__c</fullName>
    <label>E4A Customer Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tour Operator</fullName>
            </value>
            <value>
                <fullName>Travel Management Company</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>Distributors (Train operating company)</fullName>
            </value>
            <value>
                <fullName>Online Travel Agencies (OTA)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/E4A_Opt_Out_Other_Reason__c.field-meta.xml
<CustomField>
    <fullName>E4A_Opt_Out_Other_Reason__c</fullName>
    <label>E4A Opt Out Other Reason</label>
    <type>TextArea</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/E4A_Opt_Out_Reason__c.field-meta.xml
<CustomField>
    <fullName>E4A_Opt_Out_Reason__c</fullName>
    <label>E4A Opt Out Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>I receive too many emails</fullName>
            </value>
            <value>
                <fullName>The emails are not relevant to me</fullName>
            </value>
            <value>
                <fullName>Uninteresting or repetetive content</fullName>
            </value>
            <value>
                <fullName>The format is not easy to read</fullName>
            </value>
            <value>
                <fullName>I can&#39;t properly view the emails</fullName>
            </value>
            <value>
                <fullName>I don&#39;t remember subscribing</fullName>
            </value>
            <value>
                <fullName>Other (please explain)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/E4A_Subscriber_Status__c.field-meta.xml
<CustomField>
    <fullName>E4A_Subscriber_Status__c</fullName>
    <label>E4A Subscriber Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Opted Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/New_Customer__c.field-meta.xml
<CustomField>
    <fullName>New_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Customer</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Other_Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Other_Customer_Type__c</fullName>
    <label>Other Customer Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
            <value>
                <fullName>English (UK)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Receive_Communications_on__c.field-meta.xml
<CustomField>
    <fullName>Receive_Communications_on__c</fullName>
    <label>Receive Communications on</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Disruption - Continental</fullName>
            </value>
            <value>
                <fullName>Disruption - London</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/DLT_Settings__c/DLT_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Delta Settings</label>
</CustomObject>

GearsetPOC/force-app/main/default/objects/DLT_Settings__c/fields/Eurostar_for_Agents_OrgWideEmail_Name__c.field-meta.xml
<CustomField>
    <fullName>Eurostar_for_Agents_OrgWideEmail_Name__c</fullName>
    <defaultValue>&#39;Eurostar_for_Agents&#39;</defaultValue>
    <label>Eurostar For Agents OrgWideEmail Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

GearsetPOC/force-app/main/default/classes/DLT_CaseService.cls
public inherited sharing class DLT_CaseService {

    private static Map<String,BusinessHours> serviceDeskHoursByName = new Map<String,BusinessHours>();
    private static Map<String,SlaProcess> caseProductivityProcessByName = new Map<String,SlaProcess>();

    public static List<Case> filterCasesE4A(List<Case> cases) {
        List<Case> e4aCases = new List<Case>();

        for (Case c : cases) {
            if (c.RecordTypeId == DLT_CaseConstants.RT_ID_E4A_SUBSCRIBER_REQUEST
                && c.SuppliedEmail != null
            ) {
                e4aCases.add(c);
            }
        }

        return e4aCases;
    }

    public static SlaProcess selectEntitlementProcessByName(String name) {
        if (String.isBlank(name)) { return null; }

        if (!caseProductivityProcessByName.containsKey(name)) {
            List<SlaProcess> slas = [
                SELECT Id, Name
                FROM SlaProcess
                WHERE Name = :name
                    AND IsActive = true
                ORDER BY CreatedDate, VersionNumber DESC
                LIMIT 1
            ];
            caseProductivityProcessByName.put(name, !slas.isEmpty() ? slas[0] : null);
        }

        return caseProductivityProcessByName.get(name);
    }

    public static BusinessHours selectBusinessHoursByName(String name) {
        if (String.isBlank(name)) { return null; }

        if (!serviceDeskHoursByName.containsKey(name)) {
            List<BusinessHours> bhs =  [
                SELECT Id, Name
                FROM BusinessHours
                WHERE Name =: name
                ORDER BY CreatedDate DESC
                LIMIT 1
            ];
            serviceDeskHoursByName.put(name, !bhs.isEmpty() ? bhs[0] : null);
        }

        return serviceDeskHoursByName.get(name);
    }

    public static List<Entitlement> selectEntitlementByCustomerIds(List<Id> customerIds) {
        if (customerIds.isEmpty()) { return new List<Entitlement>(); }

        return [
            SELECT Id, AccountId
            FROM Entitlement
            WHERE AccountId IN: customerIds
                AND Status = :DLT_CaseConstants.ENTITLMENT_STATUS_ACTIVE
        ];
    }

    public static List<Entitlement> selectEntitlementByEntitlementIds(List<Id> entitlementIds) {
        if (entitlementIds.isEmpty()) { return new List<Entitlement>(); }

        return [
            SELECT Id, StartDate, AccountId
            FROM Entitlement
            WHERE Id IN: entitlementIds
        ];
    }

    public static void handleLogicForE4A(List<Case> cases) {
        if (cases == null || cases.isEmpty()) { return; }

        Set<Case> e4aCases = new Set<Case>(filterCasesE4A(cases));
        Set<Case> e4aCasesWithNewCustomers = new Set<Case>();
        Map<String, Case> customerEmailToCase = new Map<String, Case>();
        Map<String, Account> customerEmailToCustomer = new Map<String, Account>();

        if (e4aCases.isEmpty()) { return; }

        // prepare the data
        for (Case c : e4aCases) {
            customerEmailToCase.put(c.SuppliedEmail, c);
        }

        // main logic
        for (String email : customerEmailToCase.keySet()) {
            Case e4aCase = customerEmailToCase.get(email);

            Account customerForUpsert = new Account(
                RecordtypeId = DLT_CustomerConstants.RT_ID_PERSON_ACCOUNT,
                PersonEmail = email,
                Customer_Email__c = email,
                Customer_Email__pc = email,
                FirstName = e4aCase.First_Name__c,
                LastName = e4aCase.Last_Name__c,
                Country_B__c = e4aCase.Country__c,
                Preferred_Language__pc = e4aCase.Preferred_Language__c,
                Company_Registered_Name__c = e4aCase.SuppliedCompany,
                E4A_Customer_Type__c = e4aCase.E4A_Customer_Type__c,
                Other_Customer_Type__c = e4aCase.Other_Customer_Type__c,
                Indirect_Sales_Topics__c = e4aCase.Receive_Communications_on__c
            );

            Boolean isNewCustomer        = e4aCase.New_Customer__c == true;
            Boolean isUnsubscribeRequest = e4aCase.Subject == DLT_CaseConstants.SUBJECT_E4A_UNSUBSCRIBE;

            if (isNewCustomer) {
                customerForUpsert.E4A_Newsletter_Opt_In__c = true;
                customerForUpsert.E4A_Subscriber_Status__c = DLT_CustomerConstants.E4A_SUBSCRIBER_STATUS_APPROVED;

                e4aCasesWithNewCustomers.add(e4aCase);
            } else if (isUnsubscribeRequest) {
                customerForUpsert = new Account(
                    Customer_Email__c = email,
                    E4A_Subscriber_Status__c = DLT_CustomerConstants.E4A_SUBSCRIBER_STATUS_OPTED_OUT,
                    E4A_Opt_Out_Reason__c = e4aCase.E4A_Opt_Out_Reason__c,
                    E4A_Opt_Out_Other_Reason__c = e4aCase.E4A_Opt_Out_Other_Reason__c
                );
            }

            customerEmailToCustomer.put(email, customerForUpsert);
        }

        if (!customerEmailToCustomer.isEmpty()) {
            upsert customerEmailToCustomer.values() Customer_Email__c;
        }

        if (!e4aCasesWithNewCustomers.isEmpty()) {
            sendWelcomeEmailsE4A(e4aCasesWithNewCustomers);
        }

    }

    // HELPERS
    private static void sendWelcomeEmailsE4A(Set<Case> e4aCasesWithNewCustomers) {
        OrgWideEmailAddress owea = new OrgWideEmailAddress();

        Map<String, String> casePrefLangToTemplateDevName = new Map<String, String>{
            DLT_CaseConstants.PREF_LANG_EN => DLT_CaseConstants.EMAIL_TEMPLATE_DEVNAME_E4A_WELCOME_EN,
            DLT_CaseConstants.PREF_LANG_DE => DLT_CaseConstants.EMAIL_TEMPLATE_DEVNAME_E4A_WELCOME_DE,
            DLT_CaseConstants.PREF_LANG_FR => DLT_CaseConstants.EMAIL_TEMPLATE_DEVNAME_E4A_WELCOME_FR,
            DLT_CaseConstants.PREF_LANG_NL => DLT_CaseConstants.EMAIL_TEMPLATE_DEVNAME_E4A_WELCOME_NL,
            null => DLT_CaseConstants.EMAIL_TEMPLATE_DEVNAME_E4A_WELCOME_EN
        };

        Map<String, Id> templateDevNameToTemplateId = new Map<String, Id>();

        for (EmailTemplate et : [
            SELECT Id, DeveloperName
            FROM EmailTemplate
            WHERE DeveloperName IN :casePrefLangToTemplateDevName.values()
        ]) {
            templateDevNameToTemplateId.put(et.DeveloperName, et.Id);
        }

        if (templateDevNameToTemplateId.isEmpty()) { return; }

        if(!Test.isRunningTest()){
            owea = [
                SELECT Id, Address, DisplayName
                FROM OrgWideEmailAddress
                WHERE DisplayName = :DLT_Settings__c.getInstance().Eurostar_for_Agents_OrgWideEmail_Name__c
                LIMIT 1
            ];
        }

        List<Messaging.SingleEmailMessage> emailMessages = new List<Messaging.SingleEmailMessage>();

        for (case c : e4aCasesWithNewCustomers) {
            if (c.ContactId == null) { continue; }

            Messaging.SingleEmailMessage emailMessage = new Messaging.SingleEmailMessage();

            emailMessage.setOrgWideEmailAddressId(owea.Id);
            emailMessage.setTargetObjectId(c.ContactId);
            emailMessage.setWhatId(c.Id);
            emailMessage.setTemplateId(
                templateDevNameToTemplateId.get(casePrefLangToTemplateDevName.get(c.Preferred_Language__c))
            );

            emailMessages.add(emailMessage);
        }

        if (!Test.isRunningTest()) { Messaging.sendEmail(emailMessages); }
    }
}