GearsetPOC/force-app/main/default/objects/Account/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Customer_Email is email and External ID. Kept in sync with the standard Email field.  The Customer Email will not appear on page layouts, it is for integration matching only.</description>
    <externalId>true</externalId>
    <label>Customer Email_</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <displayFormat>C{000000000}</displayFormat>
        <label>Compensation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Name__c</fullName>
    <label>Bank Account Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <formula>CustomerC__r.Customer_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Email</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/CustomerC__c.field-meta.xml
<CustomField>
    <fullName>CustomerC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Customer PersonAccount lookup to Contact record</description>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Compensations can only be linked to Customers (with person accounts) NOT Contacts</errorMessage>
        <filterItems>
            <field>Contact.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Compensation</relationshipLabel>
    <relationshipName>Compensations</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Paypal_email__c.field-meta.xml
<CustomField>
    <fullName>Paypal_email__c</fullName>
    <description>This may be different from contact email address</description>
    <label>Paypal email</label>
    <type>Email</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/recordTypes/Paypal.recordType-meta.xml
<RecordType>
    <fullName>Paypal</fullName>
    <active>true</active>
    <description>Paypal transfer: processed on the Paypal website.</description>
    <label>Paypal</label>
</RecordType>

GearsetPOC/force-app/main/default/objects/Contact/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Customer Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

GearsetPOC/force-app/main/default/classes/compensationCustomerNameUpdate.cls
public class compensationCustomerNameUpdate {

     //For Compensation [Bank Transfer] records validations , [Jira  Id : SFDCI-789]
     
    @InvocableMethod ()
    public Static void UpdateCustName(List<Id> ids){ 
        system.debug('compIds : '+ids );
		List<Compensation__c> CompList = [SELECT Id,Name,CustomerC__r.Customer_Email__c,CustomerC__r.LastName,CustomerC__r.FirstName,
                                          CustomerC__c,Bank_Account_Name__c,RecordType.Name,Paypal_email__c FROM Compensation__c where id in :ids];
		system.debug('CompList : '+CompList );

		Contact contactObj;
        List<Compensation__c> CompensationList = new List<Compensation__c> ();
        if(CompList != null ){
            for(Compensation__c compObj :  CompList){
                system.debug('compObj : '+compObj );
                contactObj = new Contact();
                
                String lastName = compObj.CustomerC__r.LastName != null ? compObj.CustomerC__r.LastName : '' ; 
                String firstName = compObj.CustomerC__r.FirstName != null ? compObj.CustomerC__r.FirstName : '';
                String paypalEmail = compObj.Paypal_email__c != null ? compObj.Paypal_email__c : '';
                system.debug(' contactObj.custname : '+ (firstName+''+lastName).deleteWhitespace().toLowerCase() );
                
                if((firstName+''+lastName).deleteWhitespace().toLowerCase().contains('missingsurname')){

                    //if Customer name equals Missing Surname, deriving the customer name from bank account name or paypal email
                	if(compObj.RecordType.Name == 'Bank Transfer'){
                        contactObj.LastName = (compObj.Bank_Account_Name__c).replaceAll('[0-9!#$%&\'*+/=?^_`{|}~@"]', '');
                    	contactObj.FirstName = '';

                	}else if(compObj.RecordType.Name == 'Paypal'){
                        contactObj.LastName = (paypalEmail.split('@').get(0)).replaceAll('[0-9!#$%&\'*+/=?^_`{|}~@"]', '');
                    	contactObj.FirstName = '';
                	}
                }else{
                    //Removing special characters and numbers from customer name
                 	if(compObj.CustomerC__r.LastName != null ){
                     	contactObj.LastName = compObj.CustomerC__r.LastName.replaceAll('[0-9!#$%&\'*+/=?^_`{|}~@"]', '');
                 	}

                 	if(compObj.CustomerC__r.FirstName != null ){
                 		contactObj.FirstName = compObj.CustomerC__r.FirstName.replaceAll('[0-9!#$%&\'*+/=?^_`{|}~@"]', '');
                 	}
                
                }
                
                 system.debug('contactObj.LastName  : '+contactObj.LastName  );
                 system.debug('contactObj.FirstName  : '+contactObj.FirstName  );

                
               
                contactObj.id = compObj.CustomerC__c;
                CompensationList.add(compObj);
                update contactObj;
            }
            update CompensationList;
        }
    }

}