GearsetPOC/force-app/main/default/objects/Account/fields/Delta_Loyalty_Tier__c.field-meta.xml
<CustomField>
    <fullName>Delta_Loyalty_Tier__c</fullName>
    <label>Delta Loyalty Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delta_Loyalty_Tier</valueSetName>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <description>Supplied as a part of CoronaVirus webform voucher compensation request</description>
    <label>TCN/Train Departure date</label>
    <type>Date</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Initial_Reason_For_Contact__c.field-meta.xml
<CustomField>
    <fullName>Initial_Reason_For_Contact__c</fullName>
    <label>Initial Reason For Contact</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy or Book</fullName>
            </value>
            <value>
                <fullName>Change</fullName>
            </value>
            <value>
                <fullName>Cancel or Refund</fullName>
            </value>
            <value>
                <fullName>Info or Advice or Confirmation</fullName>
            </value>
            <value>
                <fullName>Disruption or Compensation</fullName>
            </value>
            <value>
                <fullName>Phone Case - please complete</fullName>
            </value>
            <value>
                <fullName>Package_Outbound_Calling</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Standalone hotel add on request</fullName>
            </value>
            <value>
                <fullName>Package add on request</fullName>
            </value>
            <value>
                <fullName>Disruption</fullName>
            </value>
            <value>
                <fullName>Package hotel exchange</fullName>
            </value>
            <value>
                <fullName>Standalone hotel exchange</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Standalone hotel refund</fullName>
            </value>
            <value>
                <fullName>Customer Room Booking</fullName>
            </value>
            <value>
                <fullName>Social media - please review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <label>PNR</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <label>Topic</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accessibility</fullName>
            </value>
            <value>
                <fullName>Additional Charges</fullName>
            </value>
            <value>
                <fullName>Amenities</fullName>
            </value>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>Assistance dog</fullName>
            </value>
            <value>
                <fullName>Bikes</fullName>
            </value>
            <value>
                <fullName>Booking Confirmation</fullName>
            </value>
            <value>
                <fullName>Brexit</fullName>
            </value>
            <value>
                <fullName>Catering</fullName>
            </value>
            <value>
                <fullName>Check-In Or Security</fullName>
            </value>
            <value>
                <fullName>Children &amp; Infants</fullName>
            </value>
            <value>
                <fullName>Club Eurostar</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Connections</fullName>
            </value>
            <value>
                <fullName>Credit Notes</fullName>
            </value>
            <value>
                <fullName>Destination Info</fullName>
            </value>
            <value>
                <fullName>Disruption</fullName>
            </value>
            <value>
                <fullName>Documents Or Paperwork</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>General feedback</fullName>
            </value>
            <value>
                <fullName>Health and Safety</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>Invoices</fullName>
            </value>
            <value>
                <fullName>Lounge</fullName>
            </value>
            <value>
                <fullName>Luggage</fullName>
            </value>
            <value>
                <fullName>Medical Supplies</fullName>
            </value>
            <value>
                <fullName>Musical Instruments</fullName>
            </value>
            <value>
                <fullName>Names</fullName>
            </value>
            <value>
                <fullName>Onboard experience</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Train__c.field-meta.xml
<CustomField>
    <fullName>Train__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Train at the origin of the case</description>
    <inlineHelpText>Train at the origin of the case</inlineHelpText>
    <label>Disruption Train</label>
    <referenceTo>Train__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <displayFormat>C{000000000}</displayFormat>
        <label>Compensation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Compensation</relationshipLabel>
    <relationshipName>Compensations</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <label>PNR</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Compensations</relationshipLabel>
    <relationshipName>Compensations</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Train__c.field-meta.xml
<CustomField>
    <fullName>Train__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Train</label>
    <referenceTo>Train__c</referenceTo>
    <relationshipLabel>Compensations</relationshipLabel>
    <relationshipName>Compensations</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>TCN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Train Cancelled</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Cancelled_By_Customer__c.field-meta.xml
<CustomField>
    <fullName>Cancelled_By_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ticket Cancelled</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Cancelled_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Cancelled_DateTime__c</fullName>
    <description>Cancelled DateTime</description>
    <label>Cancelled DateTime</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <formula>DATEVALUE(MID(Travel_DateTime__c,7,4)+&quot;-&quot;+MID(Travel_DateTime__c,4,2)+&quot;-&quot;+MID(Travel_DateTime__c,1,2))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Departure Date (formatted)</label>
    <type>Date</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <label>PNR</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Ticket_Status__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Status__c</fullName>
    <label>Ticket Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Exchanged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Train__c.field-meta.xml
<CustomField>
    <fullName>Train__c</fullName>
    <label>Train</label>
    <referenceTo>Train__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/Train__c.object-meta.xml
<CustomObject>
    <label>Train</label>
    <nameField>
        <label>Train ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Train was cancelled</description>
    <label>Cancelled</label>
    <type>Checkbox</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Train__c/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <formula>DATEVALUE(Departure_Date_Time_Format__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Departure Date (formatted)</label>
    <type>Date</type>
</CustomField>

GearsetPOC/force-app/main/default/globalValueSets/Delta_Loyalty_Tier.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>No Profile</fullName>
        <default>true</default>
        <label>No Profile</label>
    </customValue>
    <customValue>
        <fullName>Classique</fullName>
    </customValue>
    <customValue>
        <fullName>Avantage</fullName>
    </customValue>
    <customValue>
        <fullName>Carte Blanche</fullName>
    </customValue>
    <customValue>
        <fullName>Etoile</fullName>
    </customValue>
    <customValue>
        <fullName>Elite</fullName>
    </customValue>
    <masterLabel>Delta Loyalty Tier</masterLabel>
</GlobalValueSet>

GearsetPOC/force-app/main/default/classes/Eins_CasePriorityHelper.cls
public without sharing class Eins_CasePriorityHelper {
    private static Map<String, String> casesWithLoyaltyStatus = new Map<String, String>();
    private static Map<String, Boolean> cancelledTicketsByPNR = new Map<String, Boolean>();
    private static Map<String, List<Ticket__c>> ticketsByTrain = new Map<String, List<Ticket__c>>();
    private static Map<String, List<Ticket__c>> ticketsByPNR = new Map<String, List<Ticket__c>>();
    private static Map<String, Train__History> fieldHistoryByTrainId = new Map<String, Train__History>();
    private static List<Ticket__c> ticketsAndTrains = new  List<Ticket__c>();
    private static Map<String, List<Compensation__c>> casesWithCompensations = new Map<String, List<Compensation__c>>();

    public static final String DELTA_LOYALTY_TIER_CLASSIQUE = 'Classique';
    public static final String DELTA_LOYALTY_TIER_AVANTAGE = 'Avantage';
    public static final String DELTA_LOYALTY_TIER_CARTE_BLANCHE = 'Carte Blanche';
    public static final String DELTA_LOYALTY_TIER_ETOILE = 'Etoile';
    public static final String DELTA_LOYALTY_TIER_ELITE = 'Elite';
    public static final String DELTA_LOYALTY_TIER_NO_PROFILE = 'No Profile';

    public static final String CASE_PRIORITY_HIGH = 'High';
    public static final String CASE_PRIORITY_MEDIUM = 'Medium';
    public static final String CASE_PRIORITY_LOW = 'Low';

    private static final String INITIAL_REASON_FOR_CONTACT_DISRUPTION = 'Disruption';

    private static final String CASE_STATUS_CLOSED = 'Closed';

    private static final String CASE_TOPIC_URGENT = 'Urgent';



    public static List<Case> prioritiseAllCases(List<Case> cases) {
        getLoyaltyStatuses(cases);
        getCancelledTrains(cases);
        getCompensations(cases);
        for (Case caseItem : cases) {
            if (caseItem.Status != CASE_STATUS_CLOSED) {
                Date closestDate;
                Date futureDate;
                if (ticketsByPNR.get(caseItem.PNR__c) != null && String.isNotBlank(caseItem.PNR__c)) {
                    closestDate = ticketsByPNR.get(caseItem.PNR__c)[ticketsByPNR.get(caseItem.PNR__c).size() - 1].Departure_Date__c;
                    futureDate = ticketsByPNR.get(caseItem.PNR__c)[0].Departure_Date__c;
                    if (closestDate != null && futureDate != null) {
                        if ((Date.today().daysBetween(closestDate) < 0) && (Date.today().daysBetween(futureDate) < 0)) {
                                setCasePastDatePriority(caseItem);
                        } else if (((0 <= Date.today().daysBetween(closestDate)) && (Date.today().daysBetween(closestDate) < 4)) ||
                                (0 <= Date.today().daysBetween(futureDate) && (Date.today().daysBetween(futureDate) < 4))) {
                                        caseItem.Priority = CASE_PRIORITY_HIGH;
                        } else if (((3 < Date.today().daysBetween(closestDate)) && (Date.today().daysBetween(closestDate) <= 7)) ||
                                (3 < Date.today().daysBetween(futureDate) && (Date.today().daysBetween(futureDate) <= 7))) {
                                        travelMore3Less7(caseItem);
                        } else {
                            travelMore7(caseItem);
                        }
                    } else {
                        setCaseNoDatePriority(caseItem);
                    }
                } else {
                    setCaseNoDatePriority(caseItem);
                }
                highPriority(caseItem, closestDate, futureDate);
            }
        }
        return cases;
    }

    private static void getLoyaltyStatuses(List<Case> cases) {
        Map<String, String> customersWithLoyaltyStatus = new Map<String, String>();
        Set<Id> customersIds = new Set<Id>();
        for (Case caseItem : cases) {
            customersIds.add(caseItem.AccountId);
        }

        customersIds.remove(null);

        if (customersIds.isEmpty()) { return; }

        for (Account customer : [SELECT Id, Delta_Loyalty_Tier__c FROM Account WHERE Id IN :customersIds]) {
            customersWithLoyaltyStatus.put(customer.Id, customer.Delta_Loyalty_Tier__c);
        }
        for (Case caseItem : cases) {
            if (customersWithLoyaltyStatus.containsKey(caseItem.AccountId)) {
                if (String.isNotBlank(customersWithLoyaltyStatus.get(caseItem.AccountId))) {
                    casesWithLoyaltyStatus.put(caseItem.Id, customersWithLoyaltyStatus.get(caseItem.AccountId));
                }
            }
        }
    }

    private static void getCompensations(List<Case> cases) {
        Set<Id> caseIds = new Set<Id>();
        for (Case caseItem : cases) {
            caseIds.add(caseItem.Id);
        }

        caseIds.remove(null);

        if (caseIds.isEmpty()) { return; }

        for (Compensation__c compensationItem : [SELECT Id, Case__c FROM Compensation__c WHERE Case__c IN :caseIds AND CreatedDate = LAST_N_MONTHS:6]) {
            if (casesWithCompensations.get(compensationItem.Case__c) == null) {
                casesWithCompensations.put(compensationItem.Case__c, new List<Compensation__c>());
            }
            casesWithCompensations.get(compensationItem.Case__c).add(compensationItem);
        }
    }

    private static void travelMore3Less7(Case caseItem) {
        caseItem.Priority = CASE_PRIORITY_HIGH;
        if (casesWithLoyaltyStatus.containsKey(caseItem.Id)) {
            if (casesWithLoyaltyStatus.get(caseItem.Id).containsIgnoreCase(DELTA_LOYALTY_TIER_CLASSIQUE) ||
                casesWithLoyaltyStatus.get(caseItem.Id).containsIgnoreCase(DELTA_LOYALTY_TIER_AVANTAGE) ||
                !casesWithLoyaltyStatus.get(caseItem.Id).containsIgnoreCase(DELTA_LOYALTY_TIER_CARTE_BLANCHE)) {
                    caseItem.Priority = CASE_PRIORITY_MEDIUM;
            }
        } else {
            caseItem.Priority = CASE_PRIORITY_MEDIUM;
        }
        if (cancelledTicketsByPNR.get(caseItem.PNR__c) == true) {
                caseItem.Priority = CASE_PRIORITY_HIGH;
        }

    }

    private static void travelMore7(Case caseItem) {
        caseItem.Priority = CASE_PRIORITY_HIGH;
        if (casesWithLoyaltyStatus.containsKey(caseItem.Id)) {
            if (casesWithLoyaltyStatus.get(caseItem.Id).containsIgnoreCase(DELTA_LOYALTY_TIER_CLASSIQUE) ||
                casesWithLoyaltyStatus.get(caseItem.Id).containsIgnoreCase(DELTA_LOYALTY_TIER_AVANTAGE) ||
                casesWithLoyaltyStatus.get(caseItem.Id).containsIgnoreCase(DELTA_LOYALTY_TIER_CARTE_BLANCHE)) {
                    caseItem.Priority = CASE_PRIORITY_MEDIUM;
            }
        } else {
            caseItem.Priority = CASE_PRIORITY_LOW;
        }

        if (caseItem.Initial_Reason_For_Contact__c == INITIAL_REASON_FOR_CONTACT_DISRUPTION) {
            if (casesWithCompensations.get(caseItem.Id) != null) {
                if (casesWithCompensations.get(caseItem.Id).size() < 4) {
                    caseItem.Priority = CASE_PRIORITY_MEDIUM;
                }
            }
        }
        if (cancelledTicketsByPNR.get(caseItem.PNR__c) == true) {
                caseItem.Priority = CASE_PRIORITY_HIGH;
        }
    }

    private static void setCaseNoDatePriority(Case caseItem) {
        caseItem.Priority = CASE_PRIORITY_MEDIUM;
        if (casesWithLoyaltyStatus.containsKey(caseItem.Id)) {
            if (casesWithLoyaltyStatus.get(caseItem.Id).containsIgnoreCase(DELTA_LOYALTY_TIER_CLASSIQUE) ||
                casesWithLoyaltyStatus.get(caseItem.Id).containsIgnoreCase(DELTA_LOYALTY_TIER_AVANTAGE) ||
                !casesWithLoyaltyStatus.get(caseItem.Id).containsIgnoreCase(DELTA_LOYALTY_TIER_CARTE_BLANCHE)) {
                    caseItem.Priority = CASE_PRIORITY_LOW;
            }
        } else {
            caseItem.Priority = CASE_PRIORITY_LOW;
        }
        if (cancelledTicketsByPNR.get(caseItem.PNR__c) == true) {
                caseItem.Priority = CASE_PRIORITY_MEDIUM;
        }
    }

    private static void setCasePastDatePriority(Case caseItem) {
        caseItem.Priority = CASE_PRIORITY_MEDIUM;
        if (casesWithLoyaltyStatus.containsKey(caseItem.Id)) {
            if (casesWithLoyaltyStatus.get(caseItem.Id).containsIgnoreCase(DELTA_LOYALTY_TIER_CLASSIQUE) ||
                casesWithLoyaltyStatus.get(caseItem.Id).containsIgnoreCase(DELTA_LOYALTY_TIER_AVANTAGE) ||
                !casesWithLoyaltyStatus.get(caseItem.Id).containsIgnoreCase(DELTA_LOYALTY_TIER_CARTE_BLANCHE)) {
                    caseItem.Priority = CASE_PRIORITY_LOW;
            }
        } else {
            caseItem.Priority = CASE_PRIORITY_LOW;
        }
        if (caseItem.Initial_Reason_For_Contact__c == INITIAL_REASON_FOR_CONTACT_DISRUPTION) {
            if (casesWithCompensations.get(caseItem.Id) != null) {
                if (casesWithCompensations.get(caseItem.Id).size() < 4) {
                    caseItem.Priority = CASE_PRIORITY_LOW;
                }
            }
        }
        if (cancelledTicketsByPNR.get(caseItem.PNR__c) == true) {
                caseItem.Priority = CASE_PRIORITY_MEDIUM;
        }
    }

    private static void highPriority(Case caseItem, Date closestDate, Date futureDate) {
        if (casesWithLoyaltyStatus.containsKey(caseItem.Id)) {
            if (casesWithLoyaltyStatus.get(caseItem.Id).containsIgnoreCase(DELTA_LOYALTY_TIER_ELITE) ||
                casesWithLoyaltyStatus.get(caseItem.Id).containsIgnoreCase(DELTA_LOYALTY_TIER_ETOILE)) {
                    caseItem.Priority = CASE_PRIORITY_HIGH;
            }
        }

        if (String.isNotBlank(caseItem.Topic__c) && caseItem.Topic__c.containsIgnoreCase(CASE_TOPIC_URGENT)) {
            if (closestDate != null && futureDate != null) {
                caseItem.Priority = CASE_PRIORITY_HIGH;
                if ((Date.today().daysBetween(closestDate) < 0) && (Date.today().daysBetween(futureDate) < 0)) {
                    caseItem.Priority = CASE_PRIORITY_MEDIUM;
                }
            } else {
                caseItem.Priority = CASE_PRIORITY_HIGH;
            }
        }

        if (cancelledTicketsByPNR.get(caseItem.PNR__c) == true) {
                caseItem.Priority = CASE_PRIORITY_HIGH;
        }
    }

    private static void getCancelledTrains(List<Case> cases) {
        String searchPNRString = '\'';
        Set<String> pnrs = new Set<String>();
        for (Integer i = 0; i < cases.size(); i++) {
            pnrs.add(cases[i].PNR__c);
            if (i != cases.size() - 1) {
                searchPNRString += cases[i].PNR__c + ' OR ';
            } else {
                searchPNRString += ' ' + cases[i].PNR__c + '\'';
            }
        }

        pnrs.remove(null);
        pnrs.remove('');
        pnrs.remove('null');

        if (!pnrs.isEmpty()) {
            String searchQuery = 'FIND ' + searchPNRString + ' IN ALL FIELDS RETURNING Ticket__c(Id, Train__c, Ticket_Status__c, Train__r.Cancelled__c, PNR__c, Cancelled_DateTime__c, Cancelled_By_Customer__c, Departure_Date__c ORDER BY Departure_Date__c DESC)'; 
            List<List<SObject>> searchList = search.query(searchQuery);
            ticketsAndTrains = (Ticket__c[]) searchList[0];
            Set<Id> trainIds = new Set<Id>();
            for (Ticket__c ticketItem : ticketsAndTrains) {
                trainIds.add(ticketItem.Train__c);
                if (ticketsByTrain.get(ticketItem.Train__c) == null) {
                    ticketsByTrain.put(ticketItem.Train__c, new List<Ticket__c>());
                }
                ticketsByTrain.get(ticketItem.Train__c).add(ticketItem);
                if (ticketItem.Ticket_Status__c != 'Cancelled') {
                    if (ticketsByPNR.get(ticketItem.PNR__c) == null) {
                        ticketsByPNR.put(ticketItem.PNR__c, new List<Ticket__c>());
                    }
                    ticketsByPNR.get(ticketItem.PNR__c).add(ticketItem);
                }
            }
            List<Train__History> cancelledFieldHistory = [
                SELECT ParentId, OldValue, NewValue, Field, CreatedById, CreatedDate 
                FROM Train__History 
                WHERE Field = 'Cancelled__c' 
                    AND ParentId IN : trainIds
                    AND CreatedDate = LAST_N_MONTHS:6
                ORDER BY CreatedDate DESC
            ];
            for (Train__History fieldHistory : cancelledFieldHistory) {
                if (ticketsByTrain.get(fieldHistory.ParentId) != null) {
                    List<Ticket__c> tickets = ticketsByTrain.get(fieldHistory.ParentId);
    
                    if (fieldHistory.NewValue == 'true') {
                        if (fieldHistoryByTrainId.get(fieldHistory.ParentId) == null) {
                            fieldHistoryByTrainId.put(fieldHistory.ParentId, fieldHistory);
                        }
                        for (Ticket__c ticketItem : tickets) {
                            DateTime cancelledTicketDate = getDateFromCancelledDateTime(ticketItem.Cancelled_DateTime__c);
                            if (cancelledTicketsByPNR.get(ticketItem.PNR__c) == null) {
                                if (cancelledTicketDate < fieldHistory.CreatedDate) {
                                    cancelledTicketsByPNR.put(ticketItem.PNR__c, false);
                                } else {
                                    cancelledTicketsByPNR.put(ticketItem.PNR__c, true);
                                }
                            } else if (cancelledTicketsByPNR.get(ticketItem.PNR__c)) {
                                continue;
                            }
                        }
                    }
                }
            }
        }
    }

    @TestVisible
    private static DateTime getDateFromCancelledDateTime(String cancelledDateTime) {
        DateTime cancelledDateFromField;
        if (cancelledDateTime.contains('/')) {
            String cancelledDate = cancelledDateTime.substringBefore(' ');
            String cancelledTime = cancelledDateTime.substringAfter(' ');
            String departureMonth = cancelledDate.substringBetween('/','/');
            cancelledDate = cancelledDate.replace('/' + departureMonth, '');
            cancelledDate = departureMonth + '/' + cancelledDate;
            String departureYear = cancelledDate.substringAfterLast('/');
            cancelledDate = cancelledDate.replace('/' + departureYear, '');
            cancelledDate = departureYear + '/' + cancelledDate;
            cancelledDate = cancelledDate.replace('/', '-');
            cancelledDateFromField = DateTime.valueOf(cancelledDate + ' ' + cancelledTime);
        }
        return cancelledDateFromField;
    }
}