GearsetPOC/force-app/main/default/objects/Account/fields/DELTA_Loyalty_Member__c.field-meta.xml
<CustomField>
    <fullName>DELTA_Loyalty_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loyalty Member</label>
    <referenceTo>LoyaltyProgramMember</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Account/fields/Delta_Loyalty_Tier__c.field-meta.xml
<CustomField>
    <fullName>Delta_Loyalty_Tier__c</fullName>
    <label>Delta Loyalty Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delta_Loyalty_Tier</valueSetName>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Loyalty_Integration__e/Loyalty_Integration__e.object-meta.xml
<CustomObject>
    <label>Loyalty Integration</label>
    <pluralLabel>Loyalty Integrations</pluralLabel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Loyalty_Integration__e/fields/AccountRecordId__c.field-meta.xml
<CustomField>
    <fullName>AccountRecordId__c</fullName>
    <label>Account Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Loyalty_Integration__e/fields/DeltaLoyaltyTier__c.field-meta.xml
<CustomField>
    <fullName>DeltaLoyaltyTier__c</fullName>
    <label>Delta Loyalty Tier</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Loyalty_Integration__e/fields/EnrollmentDate__c.field-meta.xml
<CustomField>
    <fullName>EnrollmentDate__c</fullName>
    <label>Enrollment Date</label>
    <type>Date</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Loyalty_Integration__e/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>First Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Loyalty_Integration__e/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Last Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Loyalty_Integration__e/fields/MembershipNumber__c.field-meta.xml
<CustomField>
    <fullName>MembershipNumber__c</fullName>
    <label>Membership Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Loyalty_Integration__e/fields/MemberStatus__c.field-meta.xml
<CustomField>
    <fullName>MemberStatus__c</fullName>
    <label>Member Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/globalValueSets/Delta_Loyalty_Tier.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>No Profile</fullName>
        <default>true</default>
        <label>No Profile</label>
    </customValue>
    <customValue>
        <fullName>Classique</fullName>
    </customValue>
    <customValue>
        <fullName>Avantage</fullName>
    </customValue>
    <customValue>
        <fullName>Carte Blanche</fullName>
    </customValue>
    <customValue>
        <fullName>Etoile</fullName>
    </customValue>
    <customValue>
        <fullName>Elite</fullName>
    </customValue>
    <masterLabel>Delta Loyalty Tier</masterLabel>
</GlobalValueSet>

GearsetPOC/force-app/main/default/classes/DLT_AccountService.cls
public inherited sharing class DLT_AccountService {

    public static Loyalty_Integration__e createLoyaltyEventInstance(Account acc) {
        return new Loyalty_Integration__e(
            AccountRecordId__c = acc.Id,
            FirstName__c = acc.FirstName,
            LastName__c = acc.LastName,
            DeltaLoyaltyTier__c = acc.Delta_Loyalty_Tier__c,
            MembershipNumber__c = acc.DELTA_Loyalty_Member__r.MembershipNumber,
            MemberStatus__c = acc.DELTA_Loyalty_Member__r.MemberStatus,
            EnrollmentDate__c = acc.DELTA_Loyalty_Member__r.EnrollmentDate
        );
    }

    public static void fireLoyaltyEvents(List<Account> newAccounts) {
        if (newAccounts == null || newAccounts.isEmpty()) { return; }

        fireLoyaltyEvents(new Map<Id, Account>(newAccounts).keySet());
    }


    public static void fireLoyaltyEvents(List<Account> newAccounts, Map<Id,Account> oldAccountMap) {
        if(newAccounts == null || oldAccountMap == null || newAccounts.isEmpty() || oldAccountMap.isEmpty()) { return; }

        Set<Id> changedCustomerIds = new Set<Id>();
        List<Schema.FieldSetMember> TACTfieldSet = DLT_Utils.getFieldSetMembers(
            DLT_CustomerConstants.OBJECT_NAME,
            DLT_CustomerConstants.TACT_FIELD_SET_NAME
        );

        for (Account acc : newAccounts) {
            if (acc.RecordTypeId != DLT_CustomerConstants.RT_ID_PERSON_ACCOUNT) { continue; }

            for (Schema.FieldSetMember field : TACTfieldSet) {
                if (acc.get(field.getSObjectField()) != oldAccountMap.get(acc.Id).get(field.getSObjectField())) {
                    changedCustomerIds.add(acc.Id);
                    break;
                }
            }
        }

        fireLoyaltyEvents(changedCustomerIds);
    }

    public static void fireLoyaltyEvents(Set<Id> customerIds) {
        if (customerIds == null || customerIds.isEmpty()) { return; }

        List<Loyalty_Integration__e> events = new List<Loyalty_Integration__e>();

        for (Account acc : [
            SELECT Id,
                FirstName,
                LastName,
                Delta_Loyalty_Tier__c,
                DELTA_Loyalty_Member__r.MembershipNumber,
                DELTA_Loyalty_Member__r.MemberStatus,
                DELTA_Loyalty_Member__r.EnrollmentDate
            FROM Account
            WHERE Id IN :customerIds
                AND RecordTypeId = :DLT_CustomerConstants.RT_ID_PERSON_ACCOUNT
        ]) {
            events.add(createLoyaltyEventInstance(acc));
        }

        if (!events.isEmpty()) {
            EventBus.publish(events);
        }
    }
}