GearsetPOC/force-app/main/default/objects/Account/fields/Last_Survey_Sent__c.field-meta.xml
<CustomField>
    <fullName>Last_Survey_Sent__c</fullName>
    <label>Last Survey Sent</label>
    <type>Date</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Account/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <formula>TEXT(Preferred_Language__pc)</formula>
    <label>Preferred Language</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/CSAT_Survey_Sent__c.field-meta.xml
<CustomField>
    <fullName>CSAT_Survey_Sent__c</fullName>
    <label>CSAT Survey Sent</label>
    <type>Date</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
            <value>
                <fullName>English (UK)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/CSAT_Email__mdt/CSAT_Email__mdt.object-meta.xml
<CustomObject>
    <label>CSAT Email</label>
    <pluralLabel>CSAT Emails</pluralLabel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/CSAT_Email__mdt/fields/Default_Email_Template__c.field-meta.xml
<CustomField>
    <fullName>Default_Email_Template__c</fullName>
    <label>Default Email Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/CSAT_Email__mdt/fields/Dutch_Email_Template__c.field-meta.xml
<CustomField>
    <fullName>Dutch_Email_Template__c</fullName>
    <label>Dutch Email Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/CSAT_Email__mdt/fields/English_Email_Template__c.field-meta.xml
<CustomField>
    <fullName>English_Email_Template__c</fullName>
    <label>English Email Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/CSAT_Email__mdt/fields/Excluded_Case_Origins__c.field-meta.xml
<CustomField>
    <fullName>Excluded_Case_Origins__c</fullName>
    <label>Excluded Case Origins</label>
    <type>TextArea</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/CSAT_Email__mdt/fields/Excluded_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>Excluded_Record_Types__c</fullName>
    <label>Excluded Record Types</label>
    <type>TextArea</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/CSAT_Email__mdt/fields/French_Email_Template__c.field-meta.xml
<CustomField>
    <fullName>French_Email_Template__c</fullName>
    <label>French Email Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/CSAT_Email__mdt/fields/German_Email_Template__c.field-meta.xml
<CustomField>
    <fullName>German_Email_Template__c</fullName>
    <label>German Email Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/CSAT_Email__mdt/fields/No_days_to_exclude_CSAT_send__c.field-meta.xml
<CustomField>
    <fullName>No_days_to_exclude_CSAT_send__c</fullName>
    <label>No days to exclude CSAT send</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/SendCSATEmailController.cls
public with sharing class SendCSATEmailController {

    @AuraEnabled
    public static Map<String, String> prepareSendCSATMessage(Id caseId, Id userId) {
        try {
            CSAT_Email__mdt emailMetadata = metadataSelector();
            Case recordCase = currentCaseRecordSelector(caseId, emailMetadata.Excluded_Case_Origins__c.split(';'),
                                                            emailMetadata.Excluded_Record_Types__c.split(';'));
            return calculateCSATSendEmailoperations(emailMetadata, recordCase, userId);
        } catch (Exception e) {
            Map<String, String> returnResultMap = new Map<String, String>();
            returnResultMap.put('Error', 'CSAT cannot be sent for this case');
            return returnResultMap;
        }
    }

    public static CSAT_Email__mdt metadataSelector() {
        CSAT_Email__mdt csatEmail;
        if (Test.isRunningTest()) {
            csatEmail = metadataCreation();
        } else {
            csatEmail = [
                SELECT Id, Sender_Email__c, English_Email_Template__c, French_Email_Template__c,
                    German_Email_Template__c, Dutch_Email_Template__c, Default_Email_Template__c,
                    No_days_to_exclude_CSAT_send__c, Excluded_Case_Origins__c, Excluded_Record_Types__c
                FROM CSAT_Email__mdt LIMIT 1
            ];
        }
        return csatEmail;
    }

    public static void sendEmailMessages(List<Case> caseRecords) {
        Map<String, Object> params = new Map<String, Object>();
        params.put('caseRecords', caseRecords);
        Flow.Interview.Send_CSAT_Email_Flow yourFlow = new Flow.Interview.Send_CSAT_Email_Flow(params);
        if (!Test.isRunningTest()) {
            yourFlow.start();
        }
    }

    @InvocableMethod(label='Update Case/Account records')
    public static void preapreAccountCaseToUpdate(List<Case> caseUpdates) {
        Set<Account> accountToUpdate = new Set<Account>();
        Set<Case> caseToUpdate = new Set<Case>();
        for (Case caseRecord : caseUpdates) {
            caseToUpdate.add(new Case(
                Id = caseRecord.Id,
                CSAT_Survey_Sent__c = System.today()
            ));
            accountToUpdate.add(new Account(
                Id = caseRecord.AccountId,
                Last_Survey_Sent__c = System.today()
            ));
        }
        update new List<Account>(accountToUpdate);
        update new List<Case>(caseToUpdate);
    }

    private static Map<String, String> calculateCSATSendEmailoperations(CSAT_Email__mdt emailMetadata, Case caseRecord, Id userId) {
        Map<String, String> returnResultMap = new Map<String, String>();
        Double countDateFromLastSent = caseRecord.Account?.Last_Survey_Sent__c == null ?
                                        emailMetadata.No_days_to_exclude_CSAT_send__c + 2 :
                                        Date.valueOf(caseRecord.Account?.Last_Survey_Sent__c)
                                                .daysBetween(Date.valueOf(System.today()));
        if (emailMetadata.No_days_to_exclude_CSAT_send__c < countDateFromLastSent) {
            sendEmailMessages(new List<Case>{caseRecord});
            preapreAccountCaseToUpdate(new List<Case> {caseRecord});
            VonageCallTriggerHandler.updateUserCSATNumbersOfSending(new List<Id>{userId});
            returnResultMap.put('Success',
                                'CSAT Email has sent.'
            );
        } else {
            returnResultMap.put('Error',
                                'Please pay attention that previous CSAT Email was sent '
                                    + Integer.valueOf(countDateFromLastSent) + ' days ago.'
                                    + ' You don\'t have a permission to send messages often.'
            );
        }
        return returnResultMap;
    }

    private static Case currentCaseRecordSelector(Id caseId, List<String> caseOriginExcluded, List<String> caseRTExcluded) {
        return [
            SELECT Id, AccountId, Account.Last_Survey_Sent__c, Origin,
                RecordType.DeveloperName, Preferred_language__c, ContactEmail
            FROM Case
            WHERE AccountId != null AND Account.CSAT_Opt_Out__c = FALSE
                AND RecordType.DeveloperName NOT IN : caseRTExcluded
                AND Origin NOT IN : caseOriginExcluded AND Id =: caseId
        ];
    }

    private static CSAT_Email__mdt metadataCreation() {
        CSAT_Email__mdt csatEmail = new CSAT_Email__mdt(
            English_Email_Template__c = 'test EN',
            French_Email_Template__c = 'test FR',
            German_Email_Template__c = 'test GR',
            Dutch_Email_Template__c = 'test DU',
            Default_Email_Template__c = 'test Default',
            No_days_to_exclude_CSAT_send__c = 7,
            Excluded_Case_Origins__c = 'Email Lost Property;Email Exec;Email SpecialServices',
            Excluded_Record_Types__c = 'B2B_group_booking;DPAX;Disruption_Case;E4A_Subscriber_Request;Fraud_Audit;GDPR;GDS_HelpDesk;MICE_Booking;PRR_Case;Trade'
        );
        return csatEmail;
    }
}