GearsetPOC/force-app/main/default/objects/Account/fields/Last_Survey_Sent__c.field-meta.xml
<CustomField>
    <fullName>Last_Survey_Sent__c</fullName>
    <label>Last Survey Sent</label>
    <type>Date</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Account/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <formula>TEXT(Preferred_Language__pc)</formula>
    <label>Preferred Language</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Case/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Dutch</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
            <value>
                <fullName>English (UK)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/CSAT_Email__mdt/CSAT_Email__mdt.object-meta.xml
<CustomObject>
    <label>CSAT Email</label>
    <pluralLabel>CSAT Emails</pluralLabel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/CSAT_Email__mdt/fields/Excluded_Record_Types__c.field-meta.xml
<CustomField>
    <fullName>Excluded_Record_Types__c</fullName>
    <label>Excluded Record Types</label>
    <type>TextArea</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/CSAT_Email__mdt/fields/No_days_to_exclude_CSAT_send__c.field-meta.xml
<CustomField>
    <fullName>No_days_to_exclude_CSAT_send__c</fullName>
    <label>No days to exclude CSAT send</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/User/fields/Number_of_CSAT_s_sent__c.field-meta.xml
<CustomField>
    <fullName>Number_of_CSAT_s_sent__c</fullName>
    <label>Number of CSAT’s sent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/VonageCallTriggerHandler.cls
public with sharing class VonageCallTriggerHandler {

    private static final String PHONE_CASE_ORIGIN = 'Phone';
    private static final String STATUS_CASE_CLOSED = 'Closed';
    private static final String UPDATE_ACC_ERROR_MESSAGE = 'VonageCallTriggerHandler: Last Survey Sent field on Account was not update successfully';

    public static void senCSATEmailAfterVonageCall(Map<Id, NVMStatsSF__NVM_Call_Summary__c> odlVonageCalls, List<NVMStatsSF__NVM_Call_Summary__c> vonageCalls) {
        List<Id> relatedIdCases = new List<Id>();
        List<Id> userIds = new List<Id>();
        for (NVMStatsSF__NVM_Call_Summary__c vonageCall : vonageCalls) {
            if (((odlVonageCalls == null || odlVonageCalls.get(vonageCall.Id)?.NVMStatsSF__Call_Transcription__c == null)
                    && vonageCall?.NVMStatsSF__Call_Transcription__c != null) && vonageCall?.NVMStatsSF__Related_Case__c != null
            ) {
                relatedIdCases.add(vonageCall.NVMStatsSF__Related_Case__c);
                userIds.add(vonageCall.NVMStatsSF__Agent__c);
            }
        }
        if (relatedIdCases.isEmpty()) {
            return;
        }

        CSAT_Email__mdt emailMetadata = SendCSATEmailController.metadataSelector();
        List<String> caseRTExcluded = emailMetadata.Excluded_Record_Types__c.split(';');

        List<Id> accountUpdateIds = new List<Id>();
        List<Case> caseUpdates = new List<Case>();
        for (Case caseRecord : [SELECT Id, AccountId, Account.Last_Survey_Sent__c, Origin,
                                    RecordType.DeveloperName, Preferred_language__c, ContactEmail,
                                        (SELECT Id FROM NVMStatsSF__NVM_Call_Summaries__r)
                                FROM Case
                                WHERE AccountId != null AND Account.CSAT_Opt_Out__c = FALSE
                                    AND RecordType.DeveloperName NOT IN : caseRTExcluded
                                    AND Origin =: PHONE_CASE_ORIGIN AND Status =: STATUS_CASE_CLOSED
                                    AND Id =: relatedIdCases]
        ) {
            if (caseRecord.NVMStatsSF__NVM_Call_Summaries__r.size() == 1) {
                Double countDateFromLastSent = caseRecord.Account?.Last_Survey_Sent__c == null ?
                                        emailMetadata.No_days_to_exclude_CSAT_send__c + 2 :
                                        Date.valueOf(caseRecord.Account?.Last_Survey_Sent__c).daysBetween(Date.valueOf(System.today()));
                if (emailMetadata.No_days_to_exclude_CSAT_send__c < countDateFromLastSent) {
                    accountUpdateIds.add(caseRecord.AccountId);
                    caseUpdates.add(caseRecord);
                }
            }
        }
        if (caseUpdates.isEmpty()) {
            return;
        }

        try {
            SendCSATEmailController.sendEmailMessages(caseUpdates);
            SendCSATEmailController.preapreAccountCaseToUpdate(caseUpdates);
            updateUserCSATNumbersOfSending(userIds);
        } catch(Exception e) {
            throw new SendCSATEmailException(UPDATE_ACC_ERROR_MESSAGE);
        }
    }

    @InvocableMethod(label='Update User CSAT Numbers')
    public static void updateUserCSATNumbersOfSending(List<Id> userIds) {
        List<User> usersToUpdate = new List<User>();
        for (User currentUser : [SELECT Id, Number_of_CSAT_s_sent__c FROM User WHERE Id IN: userIds]) {
            currentUser.Number_of_CSAT_s_sent__c = currentUser.Number_of_CSAT_s_sent__c == null
                                                    ? 1 : currentUser.Number_of_CSAT_s_sent__c + 1;
            usersToUpdate.add(currentUser);
        }
        if (!usersToUpdate.isEmpty() && !System.isFuture() && !System.isBatch()) {
            update usersToUpdate;
        }
    }

    private class SendCSATEmailException extends Exception {}
}