GearsetPOC/force-app/main/default/objects/Account/fields/Raw_Telephone_Number__c.field-meta.xml
<CustomField>
    <fullName>Raw_Telephone_Number__c</fullName>
    <label>Raw Telephone Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <displayFormat>C{000000000}</displayFormat>
        <label>Compensation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Compensation__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Compensations</relationshipLabel>
    <relationshipName>Compensations</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Loyalty_Info_Update_Status__c/Loyalty_Info_Update_Status__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loyalty Info Update Status</label>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>TCN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Booker__c.field-meta.xml
<CustomField>
    <fullName>Booker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booker</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tickets (Booker)</relationshipLabel>
    <relationshipName>TicketList</relationshipName>
    <type>Lookup</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Contact_Phone_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Phone_Type__c</fullName>
    <label>Contact Phone Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Line</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Fixed Line or Mobile</fullName>
            </value>
            <value>
                <fullName>Toll Free</fullName>
            </value>
            <value>
                <fullName>Premium Rate</fullName>
            </value>
            <value>
                <fullName>Shared Cost</fullName>
            </value>
            <value>
                <fullName>VOIP</fullName>
            </value>
            <value>
                <fullName>Personal Number</fullName>
            </value>
            <value>
                <fullName>Pager</fullName>
            </value>
            <value>
                <fullName>UAN</fullName>
            </value>
            <value>
                <fullName>VoiceMail</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/ETAP_Phone__c.field-meta.xml
<CustomField>
    <fullName>ETAP_Phone__c</fullName>
    <label>ETAP_Phone</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Loyalty_Tier__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Tier__c</fullName>
    <description>Populated from Redshift - iLoyal (legacy) Data - NOT accurate
CC - Carte Classique
CB - Carte Blanche
CBE - Carte Blanche Elite</description>
    <inlineHelpText>NOTE: This field contains iLoyal Data and is NOT an accurate source of loyalty tier. Please check Booker  Loyalty Member Tier Description</inlineHelpText>
    <label>Booker Loyalty Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Carte Blanche</fullName>
            </value>
            <value>
                <fullName>Carte Blanche (Corporate)</fullName>
            </value>
            <value>
                <fullName>Carte Blanche (Elite)</fullName>
            </value>
            <value>
                <fullName>Carte Blanche (Eurostar Staff)</fullName>
            </value>
            <value>
                <fullName>Carte Blanche (VIP)</fullName>
            </value>
            <value>
                <fullName>Carte Classique</fullName>
            </value>
            <value>
                <fullName>Carte Classique (Corporate)</fullName>
            </value>
            <value>
                <fullName>Carte Classique (Eurostar Staff)</fullName>
            </value>
            <value>
                <fullName>EPP Default Tier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Loyalty_Tier_ICLP__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Tier_ICLP__c</fullName>
    <formula>IF( Booker__c &lt;&gt; NULL, Booker__r.Loyalty_Tier__pc, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Booker Loyalty Tier</label>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Phone_Locale__c.field-meta.xml
<CustomField>
    <fullName>Phone_Locale__c</fullName>
    <label>Marketing Cloud Phone Locale</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/raw_ETAP_Phone__c.field-meta.xml
<CustomField>
    <fullName>raw_ETAP_Phone__c</fullName>
    <label>raw ETAP Phone</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/raw_telephone_number__c.field-meta.xml
<CustomField>
    <fullName>raw_telephone_number__c</fullName>
    <description>Field to store original number</description>
    <label>raw telephone number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Telephone_Number__c.field-meta.xml
<CustomField>
    <fullName>Telephone_Number__c</fullName>
    <label>Telephone Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/Ticket__c/fields/Travel_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Travel_DateTime__c</fullName>
    <description>Travel DateTime</description>
    <externalId>true</externalId>
    <label>Departure DateTime</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

GearsetPOC/force-app/main/default/objects/TicketUpdateSetting__c/TicketUpdateSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TicketUpdateSetting</label>
</CustomObject>

GearsetPOC/force-app/main/default/objects/TicketUpdateSetting__c/fields/EmailRecipients__c.field-meta.xml
<CustomField>
    <fullName>EmailRecipients__c</fullName>
    <defaultValue>&#39;eilsupport@vrpconsulting.com&#39;</defaultValue>
    <label>EmailRecipients</label>
    <type>TextArea</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/TicketTriggerHandler.cls
public with sharing class TicketTriggerHandler {
    public static TicketTriggerHandler instance;
    public static Boolean isBatchUpdateSheduled;

    public static TicketTriggerHandler getInstance() {
        if (instance == null) {
            instance = new TicketTriggerHandler();
        }
        return instance;
    } 
    
     public static Boolean getIsBatchUpdateSheduled() {
        if (isBatchUpdateSheduled == null || !isBatchUpdateSheduled) {
            Integer jobsCount = [SELECT COUNT() FROM AsyncApexJob WHERE JobType in ('BatchApexWorker','ScheduledApex') AND ApexClass.Name = 'TicketUpdateBatchScheduler' AND Status = 'Queued' ];
            isBatchUpdateSheduled = jobsCount > 0;
        }
        return isBatchUpdateSheduled;
    }
    
    /**
    * @description fired on before insert event
    * @return void
    * @param newObjects: trigger.new - list of all records to insert
    */
    public void onBeforeInsert(final List<Ticket__c> newObjects) {
        PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
        onBeforeInsertUpdateCommon(newObjects, phoneUtil);
    }

    //IF(ISBLANK(ETAP_Phone__c), IF(ISBLANK(Telephone_Number__c), Booker__r.PersonHomePhone , Telephone_Number__c), ETAP_Phone__c)

    /**
    * @description fired on after insert event
    * @return void
    * @param newObjects: trigger.new - list of all records that were inserted
    * @param newObjectsMap: trigger.new - map of all records that were inserted
    */
    public void onAfterInsert(List<Ticket__c> newObjects, Map<Id, Ticket__c> newObjectsMap){
        /*system.debug('I enter on after insert method in ticket trigger handler');
        CompApp_TriggerUtils.upsertCompensations(
                                            CompApp_TriggerUtils.getCompensationCreationData(newObjects, newObjectsMap)
                                        );*/
        AccountingSyncHelper.startSync(
            Trigger.newMap.keySet(), AccountingSyncHelper.TICKET_OBJECT_NAME, AccountingSyncHelper.CREATE_OPERATION
        );
    }


    /**
    * @description fired on before update event
    * @return void
    * @param oldObjects: trigger.old - list of all records before the change to update
    * @param oldObjectsMap: trigger.oldMap - map of all records before the change to update
    * @param newObjects: trigger.new - list of all changed records to update
    * @param newObjectsMap: trigger.newMap - map of all changed records to update
    */
    public void onBeforeUpdate(final List<Ticket__c> oldObjects, final Map<Id, Ticket__c> oldObjectsMap,
                               final List<Ticket__c> newObjects, final Map<Id, Ticket__c> newObjectsMap) {
        PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
        onBeforeInsertUpdateCommon(newObjects, phoneUtil);
    }

    /**
    * @description fired on after update event
    * @return void
    * @param oldObjects: trigger.old - list of all records before the change to update
    * @param oldObjectsMap: trigger.oldMap - map of all records before the change to update
    * @param newObjects: trigger.new - list of all changed records to update
    * @param newObjectsMap: trigger.newMap - map of all changed records to update
    */
    public void onAfterUpdate(final List<Ticket__c> oldObjects, final Map<Id, Ticket__c> oldObjectsMap,
                              final List<Ticket__c> newObjects, final Map<Id, Ticket__c> newObjectsMap) {

        /*List<Ticket__c> departuredYesterdayOrEarlier = new List<Ticket__c>();

        Date departureDate;
        for (Ticket__c ticket : newObjects) {
            String tempDate = ticket.Travel_DateTime__c.substring(0, 10);
            departureDate = Date.newInstance(Integer.valueOf(tempDate.substring(6, 10)), Integer.valueOf(tempDate.substring(3, 5)), Integer.valueOf(tempDate.substring(0, 2)));
            if (departureDate < Date.Today()) {
                departuredYesterdayOrEarlier.add(ticket);
            }
        }
        Map<Id, Ticket__c> departuredYesterdayOrEarlierMap = new Map<Id, Ticket__c>(departuredYesterdayOrEarlier);
        System.Debug('BEFORE COMPENSATION');
        if (departuredYesterdayOrEarlier.size() > 0) {
            System.Debug('ENTERED COMPENSATION');
            CompApp_TriggerUtils.upsertCompensations(
                    CompApp_TriggerUtils.getCompensationCreationData(departuredYesterdayOrEarlier, departuredYesterdayOrEarlierMap)
            );
        }*/
        AccountingSyncHelper.startSync(
                Trigger.newMap.keySet(), AccountingSyncHelper.TICKET_OBJECT_NAME, AccountingSyncHelper.UPDATE_OPERATION
        );
        System.debug('------------------CPU Time upon exiting onAfterUpdate of TicketTriggerHandler: ' + Limits.getCpuTime());
    }

    /**
    * @description fired on before delete event, deletes all the attached documents and sets the application active to false
    * @return void
    * @param oldObjects: trigger.old - list of all records before tdelete
    * @param oldObjectsMap: trigger.oldMap - map of all records before delete
    */
    public void onBeforeDelete(final List<Ticket__c> oldObjects, final Map<Id, Ticket__c> oldObjectsMap) {
        
    }

    /**
    * @description fired on after delete event
    * @return void
    * @param oldObjects: trigger.old - list of all records after tdelete
    * @param oldObjectsMap: trigger.oldMap - map of all records after delete
    */
    //public void onAfterDelete(final List<Ticket__c> oldObjects, final Map<Id, Ticket__c> oldObjectsMap) {
    //    delete [SELECT Id FROM Compensation__c where Ticket__c IN : oldObjects];
    //}

    public void onAfterDelete(final List<Ticket__c> oldObjects, final Map<Id, Ticket__c> oldObjectsMap) {
        AccountingSyncHelper.startSync(
            Trigger.oldMap.keySet(), AccountingSyncHelper.TICKET_OBJECT_NAME, AccountingSyncHelper.DELETE_OPERATION
        );
    }

    /**
    * @description fired on after undelete event
    * @return void
    * @param newObjects: trigger.new - list of all records that are undeleted
    * @param newObjectsMap: trigger.new - map of all records that are undeleted
    */
    public void onAfterUndelete(final List<Ticket__c> newObjects, final Map<Id, Ticket__c> newObjectsMap) {
    }

    public void onBeforeInsertUpdateCommon(List<Ticket__c> newObjects, PhoneNumberUtil phoneUtil) {

        Map<Integer, PhoneNumber> phoneNumbersAsContact = new Map<Integer, PhoneNumber>();
        Map<Id, List<Integer>> bookerIdsWithRecordIndexesForHomePhone = new Map<Id, List<Integer>>();
        Set<Id> allPersonIds = new Set<Id>();

        for (Integer i = 0; i < newObjects.size(); i++) {
            Ticket__c ticket = newObjects[i];
            allPersonIds.add(ticket.Booker__c);
            PhoneNumber currentPhoneContact = null;

            PhoneNumber parsedNumber;
            if (ticket.Telephone_Number__c != null && ticket.Telephone_Number__c.length() > 0) {
                ticket.raw_telephone_number__c = ticket.Telephone_Number__c;
                parsedNumber = phoneUtil.parseAndValidateUsingCorrectionAlgo(ticket.Telephone_Number__c);
                if (parsedNumber.countryCode != 0 && parsedNumber.nationalNumber != 0) {
                    ticket.Telephone_Number__c = String.valueOf(parsedNumber.countryCode) + ' ' + parsedNumber.nationalNumber;
                    currentPhoneContact = parsedNumber;
                } else {
                    ticket.Telephone_Number__c = null;
                }
            }

            PhoneNumber parsedETAPNumber = null;
            if (ticket.ETAP_Phone__c != null && ticket.ETAP_Phone__c.length() > 0) {
                ticket.raw_ETAP_Phone__c = ticket.ETAP_Phone__c;
                parsedETAPNumber = phoneUtil.parseAndValidateUsingCorrectionAlgo(ticket.ETAP_Phone__c);
                if (parsedETAPNumber.countryCode != 0 && parsedETAPNumber.nationalNumber != 0) {
                    ticket.ETAP_Phone__c = String.valueOf(parsedETAPNumber.countryCode) + ' ' + parsedETAPNumber.nationalNumber;
                    currentPhoneContact = parsedETAPNumber;
                } else {
                    ticket.ETAP_Phone__c = null;
                }
            }




            if (currentPhoneContact != null) {
                phoneNumbersAsContact.put(i, currentPhoneContact);
            } else {
                List<Integer> indexes = bookerIdsWithRecordIndexesForHomePhone.get(ticket.Booker__c);
                if (indexes == null) {
                    indexes = new List<Integer>();
                    bookerIdsWithRecordIndexesForHomePhone.put(ticket.Booker__c, indexes);
                }
                indexes.add(i);
            }

        }

        Set<Id> bookersWithHomePhoneAsContact = bookerIdsWithRecordIndexesForHomePhone.keySet();
        List<Account> bookersInfo = [SELECT Id, PersonHomePhone
            //, Loyalty_Status__pc 
            FROM Account WHERE Id IN :allPersonIds];
        for (Account accountRec : bookersInfo) {
            if (bookersWithHomePhoneAsContact.contains(accountRec.Id)) {
                if (accountRec.PersonHomePhone != null && accountRec.PersonHomePhone.length() > 0) {
                    List<Integer> indexes = bookerIdsWithRecordIndexesForHomePhone.get(accountRec.Id);
                    PhoneNumber parsedPersonHomePhone = phoneUtil.parseAndValidateUsingCorrectionAlgo(accountRec.PersonHomePhone);
                    for (Integer index : indexes) {
                        phoneNumbersAsContact.put(index, parsedPersonHomePhone);
                    }
                }
            }
        }

        for (Integer index : phoneNumbersAsContact.keySet()) {
            PhoneNumber nextNumber = phoneNumbersAsContact.get(index);
            Ticket__c nextTicket = newObjects[index];
            if (nextNumber.nationalNumber != 0 && nextNumber.countryCode != 0) {
                nextTicket.Contact_Phone_Type__c = phoneUtil.getNumberType(nextNumber);
                if (nextTicket.Contact_Phone_Type__c.contains('Mobile')) {
                    nextTicket.Phone_Locale__c = phoneUtil.getRegionCodeForCountryCode(nextNumber.countryCode);
                } else {
                    nextTicket.Phone_Locale__c = '';
                }
            }
        }

        System.debug('------------------CPU Time upon exiting onBeforeInsertUpdateCommon of TicketTriggerHandler: ' + Limits.getCpuTime());

        //put on ticket loyalty tier from account - obsolete due to new formula field introduction - Loyalty_Tier_ICLP__c
        /*
        Loyalty_Info_Update_Status__c loyaltyUpdateStatus = Loyalty_Info_Update_Status__c.getOrgDefaults();
        if (loyaltyUpdateStatus.Update_Loyalty_On_Ticket__c != null && loyaltyUpdateStatus.Update_Loyalty_On_Ticket__c) {
            Map<Id, Account> mappedBookersInfo = new Map<Id, Account>(bookersInfo);
            for (Ticket__c ticket : newObjects) {
                ticket.Loyalty_Tier__c = mappedBookersInfo.get(ticket.Booker__c).Loyalty_Tier__pc;
            }
        }
        */
    }
    
    public static void sendExceptionMessage(Exception e, TicketUpdateSetting__c ticketUpdateSetting){
        System.debug(e.getMessage());
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.toAddresses = ticketUpdateSetting.EmailRecipients__c.split(',');
        message.subject = 'Trigger Update Batch Schedule Failure';
        message.plainTextBody = 'An issue has occured during TrigerUpdateBatchSchedule. \n' + e.getMessage() + '\n'
            + 'Line number' + e.getLineNumber() + '\n'
            + 'Type ' + e.getTypeName() + '\n'
            + ' Stacktrace ' + e.getStackTraceString();
        Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage> {message};
        Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
    }
}