GearsetPOC/force-app/main/default/objects/Salesforce_Support_Request__c/Salesforce_Support_Request__c.object-meta.xml
<CustomObject>
    <description>Salesforce and Marketing Cloud Support Request management</description>
    <label>Salesforce Support Request</label>
    <nameField>
        <displayFormat>SFDC-{0000}</displayFormat>
        <label>Salesforce Support Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Support Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

GearsetPOC/force-app/main/default/objects/Salesforce_Support_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>In progress2</fullName>
            </value>
            <value>
                <fullName>Referred to Requester</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Under Development</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Delta Freeze</fullName>
            </value>
            <value>
                <fullName>Pending Internal Information</fullName>
            </value>
            <value>
                <fullName>Pending Team Resource</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected - other</fullName>
            </value>
            <value>
                <fullName>Rejected - request inaccurate</fullName>
            </value>
            <value>
                <fullName>Rejected - already exists</fullName>
            </value>
            <value>
                <fullName>Rejected - duplicate</fullName>
            </value>
            <value>
                <fullName>Rejected - inaccurate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GearsetPOC/force-app/main/default/objects/Salesforce_Support_Request__c/fields/Status_Tracker__c.field-meta.xml
<CustomField>
    <fullName>Status_Tracker__c</fullName>
    <label>Status Tracker</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

GearsetPOC/force-app/main/default/classes/DLT_SFSupportRequestTriggerHandler.cls
public without sharing class DLT_SFSupportRequestTriggerHandler {
    
    public static Boolean isDisabled = false;

    public static void run() {
        if (!System.Trigger.isExecuting || isDisabled) { return; }

        if (System.Trigger.isBefore) {

            List<Salesforce_Support_Request__c> filteredRecords = filterRecordsByRecordType((List<Salesforce_Support_Request__c>) System.Trigger.new);

            if (System.Trigger.isInsert) {
               assignToGroup(filteredRecords);
            }
            if (System.Trigger.isUpdate) {
               updateStatusTracker(filteredRecords, (Map<Id, Salesforce_Support_Request__c>) System.Trigger.oldMap);
               blockOwnershipChangeIfNotCreator(filteredRecords, (Map<Id, Salesforce_Support_Request__c>) System.Trigger.oldMap);
            }
            
        }
    }

    public static void assignToGroup(List<Salesforce_Support_Request__c> sFSRequestList){

        Map<String, Id> groupNameToId = new Map<String,Id>();

        for(Group g : [SELECT Id, Name FROM Group WHERE Name IN :DLT_SFSupportRequestConstants.recordTypeToGroup.values() AND Type = 'Queue']){
            groupNameToId.put(g.Name, g.Id);
        }

        for(Salesforce_Support_Request__c request : sFSRequestList){
            request.OwnerId = groupNameToId.get(DLT_SFSupportRequestConstants.recordTypeToGroup.get(request.RecordTypeId));
        }
    }

    public static void updateStatusTracker(List<Salesforce_Support_Request__c> sFSRequestList, Map<Id, Salesforce_Support_Request__c> sFSRequestOldMap){

        for(Salesforce_Support_Request__c request : sFSRequestList){
            if(request.Status__c != sFSRequestOldMap.get(request.Id).Status__c){

                if(request.Last_Status_Change__c == null) request.Last_Status_Change__c = request.CreatedDate;

                Decimal statusDurationInMinutes = (Datetime.now().getTime() - request.Last_Status_Change__c.getTime())/(1000*60);
                
                String duration = calculateDuration(statusDurationInMinutes);

                request.Status_Tracker__c = request.Status_Tracker__c == null ? 
                    sFSRequestOldMap.get(request.Id).Status__c + duration :
                    sFSRequestOldMap.get(request.Id).Status__c + duration + '\n' + request.Status_Tracker__c;
                request.Last_Status_Change__c = Datetime.now();
            }
        }
    }

    public static String calculateDuration(Decimal statusDurationInMinutes){

        Integer statusDurationInHours = 0;
        Integer statusDurationInDays = 0;

        if(statusDurationInMinutes > 60){
            statusDurationInHours = Integer.valueOf(statusDurationInMinutes/60);
            statusDurationInMinutes = statusDurationInMinutes - statusDurationInHours*60;
        }

        if(statusDurationInHours > 24){
            statusDurationInDays = Integer.valueOf(statusDurationInHours/24);
            statusDurationInHours = statusDurationInHours - statusDurationInDays*24;
        }

        return ' - ' + statusDurationInDays + ' days ' + statusDurationInHours + ' hours ' + statusDurationInMinutes + ' minutes';
    }

    public static List<Salesforce_Support_Request__c> filterRecordsByRecordType(List<Salesforce_Support_Request__c> newRecordsList){
        
        List<Salesforce_Support_Request__c> filteredRecords = new List<Salesforce_Support_Request__c>();

        for(Salesforce_Support_Request__c request : newRecordsList){
            if(DLT_SFSupportRequestConstants.feedbackRecordTypeIds.contains(request.RecordTypeId)){
                filteredRecords.add(request);
            }
        }

        return filteredRecords;
    }

    public static void blockOwnershipChangeIfNotCreator(List<Salesforce_Support_Request__c> sFSRequestList, Map<Id, Salesforce_Support_Request__c> sFSRequestOldMap){

        Boolean userHasFeedbackPermission = DLT_Constants.IS_FEEDBACK_USER || DLT_Constants.IS_ADMIN;

        for(Salesforce_Support_Request__c request : sFSRequestList){
            if(request.OwnerId != sFSRequestOldMap.get(request.Id).OwnerId && !userHasFeedbackPermission && request.CreatedById != UserInfo.getUserId()){

                request.addError('Only record creator or user with Feedback Permission can change ownership of a record');

            }
        }
    }
}